### ISSUE TITLE
Unable to create a QVariant for gui.QColor and gui.QFont

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#101]
I can't figure out how to create a `QVariant` for either a `gui.QColor` or a `gui.QFont`.

Is it simply that the necessary `NewQVariant...` functions are missing from the library? Or are they present but I'm not looking properly?

**Comment by pekim** [comment]
Thinking about this more, I realise that it might not be straightforward. `core.go` cannot import `github.com/therecipe/qt/gui` as that would introduce a circular dependency. So any solution would have to be in the gui package.

**Comment by pekim** [comment]
This seems to work for `QColor`. And presumably something similar would work for `QFont`.

`gui.h`
```c
void* QColor_ToQVariant(void* color);
```

`gui.cpp`
```cpp
void* QColor_ToQVariant(void* color)
{
	return new QVariant(*static_cast<QColor*>(color));
}
```

`gui.go`
```go
func (p *QColor) ToQVariant() *core.QVariant {
	var tmpValue = core.NewQVariantFromPointer(C.QColor_ToQVariant(p.Pointer()))
	runtime.SetFinalizer(tmpValue, (*core.QVariant).DestroyQVariant)
	return tmpValue
}
```

I based it heavily on various `core.NewQVariant...` functions. Is this a reasonable approach?

**Comment by therecipe** [comment]
Hey


Yes, it's perfect.
I merged it, thank you :)


As you said earlier, the core package would have to include the gui package and therefore those methods are missing.
Here are some infos in the docs, how it's handled in C++ http://doc.qt.io/qt-5/qvariant.html#a-note-on-gui-types


Unfortunately your changes will be currently lost after running `qtsetup`.
Because the core, gui, ... *.go, *.h and *.cpp files are always re-generated during the setup.


But I will make them persistent and plan to also add the following additional functions:
```go
(*QVariant).ToQColor() unsafe.Pointer
(*QVariant).ToQFont() unsafe.Pointer
(*QVariant).ToQImage() unsafe.Pointer

NewQVariantFromQColor(unsafe.Pointer) *QVariant
NewQVariantFromQFont(unsafe.Pointer) *QVariant
NewQVariantFromQImage(unsafe.Pointer) *QVariant
```

It will then be possible to feed those functions an `(*QColor).Pointer()` and get an `*QVariant`.
Or receive an `*QColor` by using `gui.NewQColorFromPointer((*QVariant).ToQColor())`.

And I previously planned to support the `QVariant::setValue`, `QVariant::value` and `qvariant_cast` functions (as these are the functions that are usually used in such cases), but they use generics and I don't want to deduce all the possible types from an interface{}.

**Comment by therecipe** [comment]
The QVariant help functions are now available, even after running the setup https://github.com/therecipe/qt/commit/286a4dc68424892cc66002bda1dc0aa05f93af17

I made some minor changes, hope you don't mind. (Trimmed the `Q` prefix, to make it more Qt like.)
So, these are the new functions:

```go
(*gui.QFont).ToVariant() *core.QVariant
(*gui.QColor).ToVariant() *core.QVariant
(*gui.QImage).ToVariant() *core.QVariant

(*core.QVariant).ToFont() unsafe.Pointer
(*core.QVariant).ToColor() unsafe.Pointer
(*core.QVariant).ToImage() unsafe.Pointer
```

**Comment by pekim** [comment]
Dropping the `Q` seems reasonable.

After looking at your commit, I see that I need to look more closely at `internal/binding/...` to understand what's going on there.

It works fine for my app. Unfortunately there are some build errors for some of the examples.
```
# github.com/therecipe/qt/gui
../../../../gui/gui-minimal.go:319: undefined: core.QVariant
../../../../gui/gui-minimal.go:321: undefined: core.NewQVariantFromPointer
../../../../gui/gui-minimal.go:501: undefined: core.QVariant
../../../../gui/gui-minimal.go:503: undefined: core.NewQVariantFromPointer
../../../../gui/gui-minimal.go:915: undefined: core.QVariant
../../../../gui/gui-minimal.go:917: undefined: core.NewQVariantFromPointer
```

https://ci.appveyor.com/project/therecipe/qt

**Comment by therecipe** [comment]
Fixed it with https://github.com/therecipe/qt/commit/c61a787766c9bdb6168e5d443977858743d5981e

The export value defines if a function should be created/generated while using "qtminimal" and should only be set to `true` directly by "qtminimal". (I used copy & paste and didn't pay attention to that ...)

Sorry for almost not commenting anything in the "binding" folder, but the general flow of the data is:
`parser -> templater -> template_*.go -> function_*.go <-> converter <-> header/body/ ...`

To add the helper functions, I simply created new functions in the `parser` phase and made small changes in the `converter/output.go` file to customize the behavior of the added functions (on the C++ side).

Hope you can make some sense out of it.
The easiest way to test your changes is to simply re-compile `qtsetup` after you made changes and then run `qtsetup generate` to look how the generated files changed.
