### ISSUE TITLE
Warning during qtdeploy and qtsetup

### ISSUE THREAD

**Issue by cfanatic** [therecipe/qt#1012]
Hey!

I get a strange warning whenever I call `qtdeploy` or `qtsetup`. Please check the output below:

```
→ qtsetup check desktop
WARN[0000] failed to create env symlink; fallback to patching binaries instead (this won't work for go modules)
please open an issue  error="symlink /Users/cfanatic/Coding/Go/src/github.com/therecipe/env_darwin_amd64_513 /Applications/.env_darwin_amd64: permission denied"
INFO[0000] running: 'qtsetup check darwin' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'darwin'        
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.13.3'      
INFO[0000] GOROOT:                   *  '/usr/local/opt/go/libexec' 
INFO[0000] GOPATH:                   *  '/Users/cfanatic/Coding/Go' 
INFO[0000] GOBIN:                    *  '/Users/cfanatic/Coding/Go/bin' 
INFO[0000] GOMOD:                       ''              
INFO[0000] QT_HASH:                     '18864661ae4f85eef37265d355124a97798fa2b7' 
INFO[0000] QT_API:                      ''              
INFO[0000] QT_VERSION:                  '5.13.0'        
INFO[0000] QT_DIR:                   *  '/Users/cfanatic/Coding/Go/src/github.com/therecipe/env_darwin_amd64_513' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_HOMEBREW:                 'false'         
INFO[0000] QT_MACPORTS:                 'false'         
INFO[0000] QT_NIX:                      'false'         
INFO[0000] QT_FELGO:                    'false'         
INFO[0000] XCODE_DIR:                   '/Applications/Xcode.app' 
INFO[0000] QT_PKG_CONFIG:               'false'    
```

I am running macOS.

Can you tell me how to get rid of warning WARN[0000]? Thanks!

**Comment by therecipe** [comment]
Hey

The warning is now hidden for non module (i.e. GOPATH) builds with https://github.com/therecipe/qt/commit/6e660afb3df7b12dbe1c0c1f3cf45cb289e47bb3#diff-1630b82908dbc9a3aae774d5e2f6afa8.

The only other way to get rid of it would be to use an admin account.
I don't think you changed the default permission of the `/Applications` folder or?
`ls -l / | grep Applications` should usually return `drwxrwxr-x+ 32 root  admin`

And if you want to check if you are using an admin account you can run something like this
```
if id -Gn $(id -un) | grep -q -w admin; then echo "you are admin"; fi
```

The warning basically means that you can't simply `go run/build` your application if you use go modules, but in any other case you should be fine. So qtdeploy should work in GOPATH and module mode, and `go run/build` should work in GOPATH mode as well.

But I will see if there is some other folder than `/Applications` that is always writeable, and that I can use to make `go run/build` work in module mode for non admin accounts as well.

**Comment by cfanatic** [comment]
> The warning is now hidden for non module (i.e. GOPATH) builds with 6e660af#diff-1630b82908dbc9a3aae774d5e2f6afa8.
I have updated the master branch and now the issue is solved. Thanks.

> The warning basically means that you can't simply go run/build your application if you use go modules
Could you explain this? To be frank, I still do not really understand this Go module concept. And that was probably one of the reasons why I was confused by the warning.

> But I will see if there is some other folder than /Applications that is always writeable
No idea if it is applicable or even possible, but my first shot would have been something like /tmp.

**Comment by therecipe** [comment]
The problem underneath this warning is, that Qt requires to know where it's located during development. This information is hardcoded inside the binaries and usually, patched during the installation of Qt (and also during deployments) to point to the right directory. But since the go module support requires all "pinned" files to stay un-modificated, the only way to work around this is to patch the files to point to a location that is always write able and then symlink the "random" Qt directory to the directory hardcoded inside the Qt binaries at some point later. If this work around now fails, you won't be able to go run/build your application since Qt can't find it's own location.

But now that I think about it, I think the warning is wrong.
You will still be able to go run/build your application in go module mode, because you always clone the Qt installation (env) when using modules anyway. And the cloned installation inside the vendor dir can be simply patched.
I probably wrote the warning before figuring out, that you can't really pin the Qt env like I initially planned to do with go modules. I will change the warning.

And yeah, `/tmp` would probably work, but I hoped to find a more permanent location to create the symlink, otherwise it could be that your application might suddenly stop working during development. Which would be pretty confusing.

But it seems like I can use `/var/tmp` like I do on Linux already: https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/RaceConditions.html

**Comment by cfanatic** [comment]
Thanks for the feedback. Great framework, btw.
