### ISSUE TITLE
examples/quick/dynamic can't run on Android

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#110]
Logcat show:

```
GoLog   : failed with status: 3
```

for https://github.com/therecipe/qt/blob/master/internal/examples/quick/dynamic/dynamic.go#L27

I don't know what the problem is as it's only a single number value

**Comment by arknable** [comment]
Code 3 is error. I think it would be nice if we can grab the error message during component creation.

**Comment by therecipe** [comment]
Should be fixed with https://github.com/therecipe/qt/commit/37329a0a706d50e47ba88fb84070546d20abe759

This was the same bug as on macOS.
The dummy *.qml file needed one more line: `Item {}` to make it work ...

@arknable 
I just added partial `QList<T>` support yesterday and updated the example to print the errors from http://doc.qt.io/qt-5/qqmlcomponent.html#errors.

**Comment by arknable** [comment]
@therecipe ah I see, you already support error list from QQmlComponent. thanks.

**Comment by therecipe** [comment]
@arknable Only since yesterday :)

**Comment by bclermont** [comment]
Solved, thanks
