### ISSUE TITLE
@therecipe - we are so happy to see you back!

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#1123]
I just wanted to say that I have been following and using this github project for a long time now, and @therecipe has basically supported it single handedly. At the risk of sounding like I'm invading your private life, it's very relieving to see your committing again. At the very least because its a fantastic bit of work, but more importantly that you are safe! Hope all's ok!

**Comment by muesli** [comment]
I can only join in and say thank you as well! I admit I got really worried due to the prolonged radio silence, and I'm really relieved this project hasn't been abandoned. Thank you for all the ongoing work you put into this project!

**Comment by therecipe** [comment]
Hey @amlwwalker @muesli and anybody else reading

Thank you for the heartwarming words and sorry for the worries, I hope you didn't worry to much.
I was well in the last few month, and just needed a little break after working most of Dec/Jan. After the break I got busy with work again and then sidetracked during the pandemic.
I probably should have left a note to let you know that I'm well, and that I just took some time off.

However, I'm back for now and will let you know in advance if/when I plan to stay away for some time in the future. Also, there is no need to worry that I'm going to abandon the project, it's somewhat my "sagrada familia". And in case anything happens to me, then chances are great that one of my relatives would inform you. But I'm young and afaik healthy, so no need to worry about that.

Hope you were all safe in the last month as well, and the pandemic didn't caused you to much trouble. I will try to catch-up with the gh mentions and slack dm's in the next few days, but can't promise a quick turnaround time because I'm currently also working on a new feature that I want to get done with asap.

**Comment by amlwwalker** [comment]
Very pleased to hear you're well, I am aware from previous conversations you like your digital privacy (well done for keeping it *so* solid!). 
I have continued to be using this project for my projects so naturally I have 1000 questions, but I am holding off until i see you have caught up with the issues.

The only one I may put here (and I am going to close the issue as a sign that there is no need to respond now) but the one thing that I have a general interest in is compile time. In another of my issues, ([that is really just news that I built a fully fledged project](https://github.com/therecipe/qt/issues/1108)) - while building that the real killer to productivity was compile time.

I wondered if you keep a blog or something that keeps track of this project outside of issues - its got to such a mature state that its hard to know if there is a roadmap etc from issues and I would personally be interested to know if compile time a) has room for improvement, and b) is on the road map to be improved.

I once asked about using Go plugins for this project, because I thought that one approach would be to build plugins so that the whole app doesn't always need compiling, but I'm not sure thats the best approach and maybe you had better ideas going forward.

Excellent to hear this project isn't going anywhere, I did have a look at flutter while you were gone, but its just not a patch on this.
