### ISSUE TITLE
Renderer Example: option 3 and above not working (Windows)

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#125]
Just a heads up. I've installed it on two separate machines. First 2 examples work. Ex 3 and up crash (window disappears, process ends).

**Comment by therecipe** [comment]
Hey

Thanks for the info :)
It seems to crash if it's compile for windows/386 but works when it's compiled for windows/amd64 (msys2).
I will look into this.

**Comment by therecipe** [comment]
Okay, I looked into this again.
The problems seems to be here: https://github.com/fogleman/pt/blob/master/pt/scene.go#L32
This will crash on 32-bit systems in combination with cgo.

And here are some infos I gathered about the issue:
https://golang.org/pkg/sync/atomic/#pkg-note-BUG
https://github.com/golang/go/issues/9959
https://groups.google.com/forum/#!topic/etcd-dev/CmYma0-eFDo

If you re-order the struct https://github.com/fogleman/pt/blob/master/pt/scene.go#L5-L13 and move `rays` to the top it solves the problem for example 4 and 5.
Example 3 still won't work through. (But it doesn't even really work on windows/amd64 either)

I will fill an issue, so that this will hopefully get fixed upstream.

**Comment by 5k3105** [comment]
No worries. Thanks!
