### ISSUE TITLE
QByteArray_ITF

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#126]
Hi,

This was working previously. Now does not. How should I convert this from string (http://doc.qt.io/qt-5/qimagereader.html#supportedImageFormats)?

https://github.com/5k3105/Pipeline-Editor/blob/master/gfxcanvas/gfxcanvas.go#L356

```
github.com/5k3105/Pipeline-Editor/gfxcanvas\ngfxcanvas\\gfxcanvas.go:356: cannot use filetype (type string) as type core.QByteArray_ITF
```

Thanks

**Comment by therecipe** [comment]
Hey

Sorry for the API break.
This had to be done in order to fix https://github.com/therecipe/qt/issues/98.
Hope that doesn't break to much of your code.

You can create a `core.QByteArray` from a string like this:
`core.NewQByteArray2(filetype, len(filetype))`

And `QImageReader::supportedImageFormats` should output a `[]*core.QByteArray` now.
You can get the string from a `core.QByteArray` like this`(*QByteArray).ConstData()`.
