### ISSUE TITLE
`QJsonObject` without `insert()` api

### ISSUE THREAD

**Issue by meomap** [therecipe/qt#133]
http://doc.qt.io/qt-5/qjsonobject.html#insert

There's no correspond api for inserting key/value into `*core.QJsonObject` 

or I have to create a `*core.QJsonDocument` from scratch ?

**Comment by therecipe** [comment]
Hey

The functions is currently not available because of the `iterator` output.
I could simply make the function available without the `iterator` output until there is general support for iterators.
Did you plan to make use of the iterator?

Otherwise your could also make use of `QJsonDocument` with http://doc.qt.io/qt-5/qjsondocument.html#fromJson and the Go json package, depending on your needs.

**Comment by meomap** [comment]
Hello, I have no plan to use the iterator yet, and the usage of `fromJson` is sufficient for me until now so I closed this request

**Comment by therecipe** [comment]
Okay :)
