### ISSUE TITLE
your application encountered a fatal error and cannot continue

### ISSUE THREAD

**Issue by mukhlesur-millon** [therecipe/qt#138]
i have installed stub version on ubuntu 16.04 (vm).

when i run app on android 4.2.2 (armv7-a) it shows `your application encountered a fatal error and cannot continue`
 logcat
```
E/linker  (18405): find_library(linker.cpp:901): "/data/app-lib/org.qtproject.example.go-1/libgo_base.so" failed to load previously
E/dalvikvm(18405): dlopen("/data/app-lib/org.qtproject.example.go-1/libgo_base.so") failed: Cannot load library: find_library(linker.cpp:901): "/data/app-lib/org.qtproject.example.go-1/libgo_base.so" failed to load previously
```

(no problem on desktop build.)

edit:
same result on windows with full install. works fIne if i use qt creator's cpp example

**Comment by therecipe** [comment]
Hey

Which examples did you test?
Do they all fail with just `your application encountered a fatal error and cannot continue` error message?

btw, Thanks for the PR :)

**Comment by mukhlesur-millon** [comment]
i used example from readme page, also by using `qtsetup android` in ubuntu16.04 and `%GOPATH%/bin/qtsetup android` in windows10 (when it was building example for testing)



also, there is a problem, i used `qtsetup` and `qtsetup android` the example folder become more than 1GB as test build was not cleaned automatically.

**Comment by therecipe** [comment]
Just tested the readme example and it works fine on android 6.0.0.
And it should work on 4.2.2 as well ...

Could you maybe post a more complete logcat? (Starting with `I Qt      : qt start`)
And if possible upload your example apk? So I can test if it works for me.

Also you could register here: http://developer.samsung.com/home.do and use the "remote test lab" to test if your apk works on various samsung devices.

**Comment by mukhlesur-millon** [comment]
log for `qtsetup` http://pastebin.com/tFfqrW2t
log for `qtsetup android` http://pastebin.com/DU6nd59k
logcat (used grep qt) http://pastebin.com/JgHCSE3S

app from `C:\Users\!!!!\go\src\github.com\therecipe\qt\internal\examples\widgets\line_edits\deploy\android_minimal\build\build\outputs\apk` https://drive.google.com/open?id=0B_Ox34u6ciCsUVAzVFNyVjRlWlU

i wasn't able to use http://developer.samsung.com/rtlLanding.do, may be am not allowed to open port  2600

**Comment by therecipe** [comment]
Thanks, I could reproduce it on my system. And it should be fixed with https://github.com/therecipe/qt/commit/9a9972953ee2763fb89d007df7f4d1942c5cc662

And for the "remote test lab", you probably need to register here first https://account.samsung.com/account/signUp.do
(I think the email has to be the only valid info)

**Comment by mukhlesur-millon** [comment]
reinstall it and result is same.

**Comment by mukhlesur-millon** [comment]
from C:\Users\Shovon\go\src\github.com\therecipe\qt\internal\examples\widgets\line_edits\deploy\android_minimal
android-libgo.so-deployment-settings.json
```json
{"qt":"C:/Qt/Qt5.7.0/5.7/android_armv7","sdk":"C:/android-sdk-windows","sdkBuildToolsRevision":"25.0.1","ndk":"C:/android-ndk-r12b","toolchain-prefix":"arm-linux-androideabi","tool-prefix":"arm-linux-androideabi","toolchain-version":"4.9","ndk-host":"windows-x86_64","target-architecture":"armeabi-v7a","android-extra-libs":"C:/Users/Shovon/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/deploy/android_minimal/libgo_base.so","android-package-source-directory":"C:/Users/Shovon/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/android","qml-root-path":"C:/Users/Shovon/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/qml","application-binary":"C:/Users/Shovon/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/deploy/android_minimal/libgo.so"}```

**Comment by mukhlesur-millon** [comment]
i have again cleaned everything and go get it and run. [
android_minimal.zip](https://drive.google.com/open?id=0B_Ox34u6ciCsN0NDc1owcE9kbDg)

**Comment by therecipe** [comment]
I just installed the `line_edits.apk` with adb and it works for me.
Does it still crash on your side?

**Comment by mukhlesur-millon** [comment]
![screenshot_2016-12-09-00-57-58 1](https://cloud.githubusercontent.com/assets/24350767/21023529/1ce4ba20-bdab-11e6-93d9-7d07e32b9a52.png)

**Comment by therecipe** [comment]
Okay, I think I could reproduce it on a `Galaxy S III` with 4.1.1.
I will look into this.

**Comment by mukhlesur-millon** [comment]
it works :smile_cat: i have copied `libQt5Widgets.so` from `/data/app-lib/org.qtproject.example.go-1/` to `/system/lib/`. i dont know what causes the problem. but it works :smile:

**Comment by therecipe** [comment]
Thank you :)
If this works for you, then the bug is in the code that copies the *.so files during the installation/first start of the *.apk.
I will check if there is something I can do, or if this is a bug that is already fixed in Qt 5.8.

**Comment by therecipe** [comment]
I updated the dependencies for android and using the new ndk version (r13b) solved the issue for me (on macOS, I will later test it on windows as well).

Could you test it with the new ndk/sdk version and report back?
You can find the new link here: https://github.com/therecipe/qt#android

**Comment by mukhlesur-millon** [comment]
do i need to update and rebuild everything?
i upgrade ndk and set ndk path and result is same.

when building the app, Qt doesn't check `libgo_base.so` for dependency.

i think for [these line](https://github.com/therecipe/qt/blob/master/cmd/qtdeploy/qtdeploy.go#L529-L537), the app isn't  aware of  `libQt5Widgets.so` and for that reason it try to search `libQt5Widgets.so` in `/system/lib/` instead of `/data/app-lib/org.qtproject.example.go-1/`. i am waiting for ministro to support Qt5.7.

**Comment by therecipe** [comment]
Thanks for reporting back :)

Just replacing the ndk should have been enough, no need to rebuild everything.

Yes, these lines are needed to copy the dependencies, because `androiddeployqt` that is used to bundle everything into a apk can't resolve the dependencies somehow.

But that let me have an idea, if the dependencies are not detected by `androiddeployqt`, then the code that copies the dependencies later on the phone (on the first start of the app) could be only partially working as well. (Because the code is generated by `androiddeyploqt`)

I will investigate further and report back.

**Comment by mukhlesur-millon** [comment]
> the code that copies the dependencies later on the phone (on the first start of the app) 

just to inform you (the thing i have noticed)
All libraries (matching cpu ABI) are extracted (usually at `/data/app-lib/package-*`) by `pm`, when `pm install package.apk` is used. at first start, database and other configurations are created at `/data/data/package/`

**Comment by therecipe** [comment]
Thanks for the info, so the bug was not in the phase of copying the dependencies but in the phase were the dependencies were loaded.

I think it's fixed with https://github.com/therecipe/qt/commit/8318f0c212c2d34a84e0bdaf6ece20dbc33670a1 now.

The problems was that `androiddeployqt` checked `libgo.so` for dependencies (which is only a small wrapper around Go's main function) and didn't found any dependencies there. So I had to let `androiddeployqt` check `libgo_base.so` instead.

`androiddeployqt` creates a list of dependencies to load during the start of the application here: `android_minimal/build/res/values/libs.xml`

Previously there were only `QtCore`, `QtGui`, some plugins  and `libgo_base` listed.
Now the file should contain`QtWidgets` and the rest of the needed libs as well.

**Comment by mukhlesur-millon** [comment]
sorry for wrong info. you are right. it copies some dependency to `/data/data/package/qt-reserved-files/` when starting.

**Comment by mukhlesur-millon** [comment]
![s](https://cloud.githubusercontent.com/assets/24350767/21325196/3e8d5022-c64f-11e6-8e08-d74bebd909bb.png)

**Comment by therecipe** [comment]
You are welcome :)

**Comment by m-kuhn** [comment]
As reference for others ending up here, this message is shown when a Qt app fails to load some libraries at startup. The best way to get insights into what's happening is to kill the app if it's still running and restart it while checking with `adb logcat` what's going on.
