### ISSUE TITLE
using golang GRPC with ios and android

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#142]
I am trying to work out how to get my ios and android qt app to use grpc (http://www.grpc.io)

The grpc is golang based

I found a protobuf implemention in c++, but thats c++ (not golang) and not using grpc, only protobuf
https://github.com/nsuke/protobuf-qml

any ideas ?

**Comment by jordanorelli** [comment]
I'm using grpc in a project with the Qt binding just fine (on OSX); I'm not quite sure what this thing you linked is or why it's required.

Have you gotten grpc working separately from Qt? This is a pretty good resource for getting that going: http://www.grpc.io/docs/quickstart/go.html

The protobuf compiler protoc is written in C++. When outputting Go, the protobuf compiler protoc uses protoc-gen-go (written in Go) as a subprocess. You have to install protoc, written in C++, and protoc-gen-go, written in Go, separately, before using gRPC.

**Comment by therecipe** [comment]
@joeblew99 

Hey

I used protobuf just 1-2 times a while ago, but my experience was similar to what jordanorelli said above.
You can basically use a program to create Go structs from *.protobuf files and use them to serialize you data.

But since you explicitly said you want to use it with iOS/Android you probably want to know how you can use gRPC from QML?
If that's the case then it's probably a bit more difficult.

You could either write a generic gRPC wrapper like the lib you linked to use gRPC from QML (which under the hoods calls Go).

Or use the linked lib directly. (You probably need to compile the *.cpp files into a plugin or something and then also bundle the protobuf-qml *.qml files + the compiled plugin with your app)

But I would probably just create a few signals/slots with qtmoc, to let Go and QML communicate and then simply use http://www.grpc.io on the Go side.

**Comment by joeblew99** [comment]
@jordanorelli, @therecipe 

thanks all for replies.

I would like to try to get this working and then put it up as a demo for everyone. GRPC is just so damn easy, and getting it working with QML for Desktop and Mobile will make writing apps with the same code a pleasure.

 @jordanorelli 
Great that you got it working on OSX.  i will try that for sure next before trying mobile.
If you have a basic demo on a repo let me know.

@therecipe 
Great points as always - really appreciate the tips.
I am not a c++ programmer.
I would like to get to the point where i can just use golang and QML.
Could we try to get a generic lib working in a example somewhere perhaps ?

**Comment by therecipe** [comment]
@joeblew99 
> Could we try to get a generic lib working in a example ? I suggested above i can put up my basic examples.

Sure, put them up :)

**Comment by joeblew99** [comment]
@therecipe 

Have a look at these and see what you think.

There are 2 ways this can be done, but i think 1 is what we should aim for.
1. Direct GRPC binding to QML
This example does it with a bit of java code.
https://github.com/kenshaw/go-jakarta/tree/master/02-gomobile-and-grpc

2. Using the grpc-gateway and exposing a rest service, which is not really what we want. But will link here to show it:
https://github.com/kenshaw/go-jakarta/tree/master/05-rest-to-grpc

The other  example is much bigger with 3 microservices. I think its too big for now.

I also noticed the bridge2 code in the examples of the repo today:
https://github.com/therecipe/qt/tree/master/internal/examples/quick/bridge2

Where do you want to put the example ?
https://github.com/therecipe/qt/tree/master/internal/examples/grpc ?

**Comment by jordanorelli** [comment]
ok so I had this problem too. I'm actually using gRPC in my Qt project and was having a lot of trouble getting it running on Windows (it's _still_ broken on Windows for me), so I wanted to figure out if I had the Qt and gRPC stuff correct, so I wrote this. Maybe it'll be useful for you?

https://github.com/jordanorelli/grpc-ui

^ you can use this to test your setup to see if you have the dependencies installed correctly and working. It doesn't do anything fancy at all, it just creates a label and make a gRPC call and update's the label's text on a timer based on the result of the gRPC calls.

Run the server (it's in cmd/count-server), then run the client (in cmd/count-client), and the client should display the value of a counter from the server. Every second, the client will request a new value from the server. You can start up a bunch of clients to see that they don't affect one another. You can also terminate the server and start it back up and the clients will automatically reconnect.

**Comment by joeblew99** [comment]
@jordanorelli 

nice.
Yeah i can imagine its not much fun on windows. I have seen some docker images just for code generating grpc code btw, which might make life easier.
I am on Mac, but used to use windows.

Your example worked for me.

Tomorrow i will try to get a bigger example working with QML bindings.

**Comment by jordanorelli** [comment]
I normally work on a Mac, but I'm trying to get my client to work on both platforms. Once I have the Windows toolchain all sorted out, I'll go back to avoiding Windows for everything but video games ;)

As for generating the protobuf stuff: you really only need protoc and protoc-gen-go on one machine, because you can just generate the `*.pb.go` stuff on your machine of choice and check it into git. The only reason I set it up on Windows, too, was so that I wouldn't have to switch between machines while working. Once you use it to generate the Go package on one platform, you can use that package on any platform, because the generated code is pure Go.

And once you get the hang of it, it's honestly easier than writing REST endpoints. The one major drawback that I've found so far is losing the ability to curl things by hand. I'm a huge fan so far.

**Comment by joeblew99** [comment]
I stopped using rest a year ago - GRPC all the way for me.
Once you go GRPC you never go back :) 
Hence why i am trying to get it fully working with qml :)

**Comment by therecipe** [comment]
@joeblew99 

I ported the first example, you can find it [here ](https://github.com/therecipe/qt/tree/master/internal/examples/grpc/hello_world)

But I wasn't sure, where you wanted to handle the gRPC logic part of the code.
So I just ported it as I saw it in the example, and so the "logic" lives inside a js function in the QML file.
And the signals/slots are just tiny wrappers around the functions calls and expose the "errors" back to QML.

But It's probably better if the "logic" and error handling of the gRPC code completely lives inside Go.
(Because you should generally write as less js code as possible, when working with QML.)
So you would ideally just update the QML state with some signals (which I haven't used in the example) and some slots.
I probably should create another hello_world example, to show this as well.

> Where do you want to put the example ?
https://github.com/therecipe/qt/tree/master/internal/examples/grpc ?

Yes, put it in `examples/grpc/your_example`

@jordanorelli 

Thank you :)
I got it working on macOS and linux with only `go get ...` and `go install ...`
On windows, I needed to run `qtdeploy` inside `cmd/count-client` to get it working.
(I did test it with MSYS2 mingw32 + mingw64)

> I'm actually using gRPC in my Qt project and was having a lot of trouble getting it running on Windows (it's still broken on Windows for me)

What issues are you facing?
Do you want to open a separate issue?

**Comment by joeblew99** [comment]
@therecipe 
thanks for integrating the 2 hello world examples - super excited.
This is going to make it really enjoyable to write bigger things with QT.

I will play around with those today.
I agree 100% with the design approach of putting all logic at the golang level too.
Impressive how easy you made it with the signal slots.

So, now i have a template I will extend from here adding some other GRPC things, and let you know, so you can include in the examples area if you want:
- tracing to open tracing (https://github.com/grpc-ecosystem/grpc-opentracing). You get a nice Web ui to see everything too.
- telemetry to Prometheus
- structured logging
- exposure to web using the grpc- gateway. This is an easy way to reuse your GRPC service to have a REST / JSON API, with Swagger. 
- exposure to web using the proto.js (JS), with the new grpc-bus (golang). This is a way to reuse your GRPC Service to have a web socket based communication with the browser.

The ones involving web might be useful for QTWeb perhaps.

Happy to hear everyones thoughts on this...

**Comment by therecipe** [comment]
@joeblew99

I like the ideas :)
Just send PRs and I will happily merge them.

**Comment by joeblew99** [comment]
great to hear...

first thing is  to get IOS and Android setup working first with test
Application before getting GRPC working.
i am raising issues as i hit them.

**Comment by joeblew99** [comment]
i am closing this.
GRPCS works on IOS and Android in the examples and for other apps. 
Great works all...
