### ISSUE TITLE
qtsetup manages dependencies in a highly irregular way

### ISSUE THREAD

**Issue by jordanorelli** [therecipe/qt#148]
part of the qtsetup process automatically pulls in the dependencies for the qt binding project. the way it goes about doing this is exceptionally non-standard. I describe it as exceptional because, in fact, it can break in weird ways.

```
jorelli@LAPTOP-6A5RC78H MINGW64 /c/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtsetup
$ qtsetup 2>&1 | sed 's/\\n/\n/g'
time="2016-12-14T15:24:49-06:00" level=info msg="running setup/prep"
time="2016-12-14T15:24:49-06:00" level=error msg="failed to run command" cmd="cmd /C mklink /H usr\\bin\\go.exe C:\\Go\\bin\\go.exe" error="exit status 1" func=RunCmdOptional name="create go symlink in your QT_MSYS2_DIR/usr/bin (C:\\msys64\\usr\\bin)" output="The system cannot find the path specified.\r
"
time="2016-12-14T15:24:52-06:00" level=panic msg="failed to run command" cmd="go get -u -v github.com/fogleman/ln/ln" error="exit status 1" func=RunCmd name="install fogleman/ln" output="github.com/fogleman/ln (download)
github.com/fogleman/gg (download)
# cd C:\\Users\\jorelli\\go\\src\\github.com\\fogleman\\gg; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
\tREADME.md
\tcontext.go
\tutil.go
Please commit your changes or stash them before you merge.
Aborting
Updating 19103e0..62c697d
package github.com/fogleman/gg: exit status 1
"
panic: (*logrus.Entry) (0x5da0c0,0xc042006ff0)

goroutine 1 [running]:
panic(0x5da0c0, 0xc042006ff0)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/Sirupsen/logrus.Entry.log(0xc042006280, 0xc04211a930, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc042037500, ...)
        C:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x42a
github.com/Sirupsen/logrus.(*Entry).Panic(0xc042006fa0, 0xc042037650, 0x1, 0x1)
        C:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x12b
github.com/therecipe/qt/internal/utils.RunCmd(0xc042070c60, 0x5e758d, 0x13, 0x4, 0x4)
        C:/Users/jorelli/go/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x575
main.prep()
        C:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtsetup/prep.go:22 +0x237
main.main()
        C:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtsetup/qtsetup.go:59 +0x39f
```

^ this is because of some nonsense in git, windows newlines, msys2, and some other noise that is honestly not of interest here. It's easy enough to fix on my own, but more to the point: the project shouldn't be attempting to modify the user's global Go packages, especially now that support for vendoring is built into the Go tool.

The dependencies for _this_ project should be managed by some sort of dependency management system. I strongly recommend [glide](http://glide.sh/). I'm happy to lead the charge on this so long as I know that the change is welcome.

**Comment by joeblew99** [comment]
i know what you mean, and also saw the same code in qtsetup
But, on OSX its happy to stomp on it every time.

If agree that vendoring should make things more stable and go idiomatic though.
And it seems windows users have a harder time of it then me on osx it seems

**Comment by therecipe** [comment]
I agree qtsetup shouldn't pull the deps for these examples.
https://github.com/therecipe/qt/commit/5751299dd523769695a2e8a2003dc62a68bf4fc1 removes the code and excludes the exampels from beeing build.
I really didn't thought about the possibility that these packages where already (maybe modified) present on the system.

About dependency management, I tried to avoid these in Go as I'm happy with using different GOPATHs and the possibility to vendor pkgs right now. (And I didn't wanted to use anything that was not official, or at least seemed somewhat future prof)

But after looking into glide, it seems like it can be useful. And as long as it is something optional to
`go get github.com/therecipe/qt/cmd/...` and doesn't break the "onboarding" for those without glide I'm open for the change.

Does glide support versioning of binaries? By passing the `-X` flag or something to `go build`? That would be useful for the cmd tools.

**Comment by joeblew99** [comment]
As far as i know glide does not support binaries at all. 

Regarding binaries and cross platform builds. i would also consider what they did in this repo.
https://github.com/andlabs/ui
- allows upsteamers (made up work) to have a much easier time of it.
- try it yourself

**Comment by therecipe** [comment]
@joeblew99 

Yes, making it work with a simple `go get` would be perfect.
But I don't know if this is possible, as there are a few problems.
On is the limitation that if you static compile Qt your need to open source your code under GPLv3 or buy a commercial license.
This is no real problem, but I would have to provide pre-build static versions of Qt for each platform + the used tools (cross compilers and such) and these things weight several gb per platform + I would have to keep them up to date too.
But there are changes coming with Qt 5.8 which maybe make these things simpler.

**Comment by gedw99** [comment]
Regarding the licensing , that is something that I was always wondering about. Good to know.

Based on that I feel it's best to leave it as it is.
This of course brings long build times though. The the first time as a golang programmer I am feeling like my mackbook is not fast enough :)
So I looked at how long your Travis builds are taking. A long time ! Just how it is though, but a VMware server is easy to rent these days with images for OSX, win10 and other desktops all preloaded. Just saying in case your curious because I am toying with it. It 20 to 40 a month.
Can you phone of link to the cha he's coming with QT 5.8 ? I

**Comment by therecipe** [comment]
@gedw99 
> Regarding the licensing , that is something that I was always wondering about. Good to know.

Please don't only take my word for it. IANAL and it's probably best to contact the Qt company directly if you want to have clarity.
For example there are modules supported in this binding that are only available under GPLv3 (charts, datavisualization). And deploying your application to iOS requieres a commercial license as well IIRC. Because there everything is static linked at the moment. (This might change someday though)
So there are a few pitfalls ...

> Can you phone of link to the cha he's coming with QT 5.8 ? I

> Configurability (Qt Lite project)
Qt 5.8 comes with a rewritten configuration system, that allows for easy customisation of your Qt build. The main focus of this feature is for the Device Creation, but it can also be used to tailor a Qt build for mobile or desktop. The system allows removing individual pieces of functionality and APIs from Qt, thus creating a more lightweight set of libraries for deployment.

Quote is taken from [here](https://wiki.qt.io/New_Features_in_Qt_5.8).

This could make it simpler to provide a lightweight version of Qt more easily. (For developing and later for deploying the application)
Like a base version, that only includes: core, gui, widgets

**Comment by joeblew99** [comment]
Yes, i will ask them myself too. 

i was watching their webinar and with QT 5.7, they seem to be cool with using it on desktops and mobile for free, but you need commercial license for doing embedded.
i am new to QT, but it seems that only "Device Creation" is not " open"

My source -  Go to 17 minutes mark:
https://www.youtube.com/watch?v=WiJEdvZSsQk

Its always tough to work this stuff out.

--

Regarding QT 5.8 and the new Configuration System, it sounds cool how you can essentially do "tree shaking" and so only ship the parts of QT that you need. But it it requires commercial licensing then i think we should stay away from it. I guess its a matter of seeing what it really is when it comes out.

The other additions in QT 5.8 look really useful though i must say. Especially in combination with golang. Http/2 sounds good, since modern golang IO uses it.

**Comment by therecipe** [comment]
Here are some additional infos regarding the licensing: https://www.qt.io/licensing/
And yes, the whole embedded device stuff that they provide as well (Boot2Qt and such) is sadly only for paying customers.

IIRC the Qt Lite project, is just a different implementation of the "configuration" system, that is used if you compile the Qt package from source. But since the binding uses the pre-build packages, that change shouldn't affect us. And I'm sure it won't come along with a license change or such.

But it could be interesting for making the binding `go get` able. (But that doesn't has a priority right now)

**Comment by joeblew99** [comment]
ok thanks.

@jordanorelli 

Well i think this issue has been all around the houses. Sorry about asking so many questions.
So whats the actions ?
- go glide for pulling dependencies ? The golang team are doing a complete overhaul of the vendoring system BTW, but it will be about 6 months before we see any of it. It will be part of the code golang install.

**Comment by joeblew99** [comment]
@jordanorelli  @therecipe 
Is this ready for closing ?
As i understand it golang is getting a totally new packaging & version system and we are waiting on that ?
https://github.com/golang/dep

**Comment by therecipe** [comment]
Here is the current roadmap for `golang/dep`: https://github.com/golang/dep/wiki/Roadmap
They have the cgo support on the radar (end 2017), so yeah we will have to wait for it.

>Is this ready for closing ?

I'm not sure, but the initial problem of this issue was resolved some time ago.
Lets wait for @jordanorelli 

Otherwise I will close this and the other resolved issues in one batch, when I'm making a cleanup.
