### ISSUE TITLE
Slot connection

### ISSUE THREAD

**Issue by Matt-Texier** [therecipe/qt#158]
Hi Guys,

Sorry but this is more some kind of a go question than a direct qt question ... Taking the line_edit example, I do have problem to understand this declaration:

`echoComboBox.ConnectCurrentIndexChanged(func(index int) { echoChanged(echoLineEdit, index) })`

The connectCurrentIndexChange prototype is asking for an int as parameter and by the magic of this declaration, it looks like you can replace the prototype with another function that is passing others parameter than the one declared in the prototype...

Same question for this one:

`Button.ConnectClicked(func(_ bool) { cmdNeighButtonClicked(logText) })`

I don't get how are used curly braces as well as the underscore ... and how this declaration works ... I am using it ... but would like to understand it !

Sorry for putting this question as an issue ...

Thanks for your help,
Matt.

**Comment by Matt-Texier** [comment]
Found the solution ...

**Comment by therecipe** [comment]
Hey

Yes, it's a bit irritating. I had the same difficulties with https://golang.org/pkg/net/http/#HandleFunc when I started with Go.

But it's rather simple.
`ConnectCurrentIndexChanged` (like all connect functions) has just one parameter which is a
`func(index int)`.
So you can pass any function that satisfies this parameter to `ConnectCurrentIndexChanged`.

In Go that can be a `func(index int)`, `func(_ int)` or `func(int)` (the last two functions can't access the `int` from within because the `int` parameter has no name).

So here are a few example, how you can use `ConnectCurrentIndexChanged`

```go
package main

type test struct{}

func (test) myClassFuntion(i int) { println(i) }

//

func myFunction(i int) { println(i) }

//

func someFunction() {

	//... create echoComboBox

	echoComboBox.ConnectCurrentIndexChanged(myFunction) //use the function from above

	//or

	var myFunction2 = func(i int) { println(i) }
	echoComboBox.ConnectCurrentIndexChanged(myFunction2) //use the created function

	//or

	echoComboBox.ConnectCurrentIndexChanged(func(i int) { println(i) }) //create a inline function, right where you need it

	//or

	var t = new(test)
	echoComboBox.ConnectCurrentIndexChanged(t.myClassFuntion) //use the class function

}
```

**Comment by Matt-Texier** [comment]
Yes, Thanks for your reply.

I finally decide to buy myself a good old paper book explaining golang. Funny enough, I found out that the same guy that teach me C language 20 years ago with the bible of C coders (C programming by Ritchie / Kernighan) is now teaching me golang: Go programming by Mr Donovan and Mr Kernighan ! So impressed by this person …  

Nice section in this book that explain “anonymous function” page 135 ! 

Thanks Matt.
