### ISSUE TITLE
Support for QJSValue

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#167]
Hi,

Do you have plan to support `QJSValue` (http://doc.qt.io/qt-5/qjsvalue.html) ?

Thanks.

**Comment by therecipe** [comment]
Hey

The class should be supported already.

Did you try one of these?

(From the `qml` package)
```go
func NewQJSValue(value QJSValue__SpecialValue) *QJSValue
func NewQJSValue10(value string) *QJSValue
func NewQJSValue2(other QJSValue_ITF) *QJSValue
func NewQJSValue3(other QJSValue_ITF) *QJSValue
func NewQJSValue4(value bool) *QJSValue
func NewQJSValue5(value int) *QJSValue
func NewQJSValue6(value uint) *QJSValue
func NewQJSValue7(value float64) *QJSValue
func NewQJSValue8(value string) *QJSValue
func NewQJSValue9(value core.QLatin1String_ITF) *QJSValue
```

**Comment by arknable** [comment]
ok, I'll try this today

**Comment by arknable** [comment]
Hi,

It looks like `QJSValue` binding doesn't have call method yet, I got following error when tried to use `call` or `Call`.

`./application.go:42: callback.Call undefined (type *qml.QJSValue has no field or method Call)`

This is using following sample: https://github.com/arknable/therecipe-issue

Thanks.

**Comment by therecipe** [comment]
I think that's because `QJSValue` is not derived from `QObject` and therefore the functions can't be called from QML directly, because they can't be signals/slots or made invokable with the Q_INVOKEABLE macro.

So you probably need a helper object with custom slots/signals to work around this and call the `Call` function in Go.

**Comment by arknable** [comment]
actually `call()` is c++ function, so it doesn't meant to be called from QML. in above sample, I'm trying to invoke `QJSValue::call`. could you please add that function ?

**Comment by therecipe** [comment]
Oh, sorry I somehow thought you wanted to use it from QML :D

Yeah, the function is not available for Go yet because of the generic list/container problem.
I'm halfway through that but stopped because it took me really long to get the first half of it working (converting from C++ QList<T> to Go []T for returns) and I was busy at the time.

But this is the next big thing I wanted to work on, after solving a few minor problems.
How important is this function?

**Comment by arknable** [comment]
ah ok. I'm using `QJSValue` to use threading on backend so UI doesn't freeze.

**Comment by arknable** [comment]
@therecipe just curious, does the feature still long down the road before you implemented it ?

**Comment by therecipe** [comment]
@arknable 
Hard to say, it has high priority to me but it will still take at least 2-3 weeks probably more.

**Comment by therecipe** [comment]
@arknable 

I partially implemented generic list / container support with https://github.com/therecipe/qt/commit/3456e5280a438b31c6c4529ef86e465ba190ef7d

here is also an example for them:
https://github.com/therecipe/qt/tree/master/internal/examples/quick/listview

**Comment by therecipe** [comment]
and `QJSValue::call` is now also supported with: https://github.com/therecipe/qt/commit/f9e97de97ee7dcda4abc5a3ad06e4035ffa4ff41

**Comment by arknable** [comment]
ah nice I really looking forward for abstract model support. I'll try them tomorrow.

**Comment by arknable** [comment]
@therecipe I can confirm that `QJSValue` is not callable. thank you :)
