### ISSUE TITLE
How to extend QObject to implement signals and slots

### ISSUE THREAD

**Issue by longlongh4** [therecipe/qt#18]
Thank you very much for making such an amazing library.
I ran into a problem today. I want to subclass a QObject to add some signals and slots and then pass the pointer to QmlEngine so I can call go functions from QML. This can be done easily in c++ , but how to do this with golang?

**Comment by therecipe** [comment]
Hey

Unfortunately, it's currently not possible to add your own signals or slots to existing classes.
The binding currently just allows you to use/override the existing signals or virtual functions.

The problem is, that if you would want to add new signals/slots to your own subclass, you would need to manually create the *.cpp, *.h and the *.go file and also run the http://doc.qt.io/qt-5/moc.html tool.

This could be automated (probably integrated into "qtdeploy"), with a function that parses the *.go files from your project and creates the missing files on the fly. But I haven't really looked into that yet.

However, if you just want to be able to call Go functions from Qml or Qml functions from Go, there is a dirty workaround :)

I added a new example, which demonstrates how you can do it. https://github.com/therecipe/qt/tree/master/internal/examples/quick/bridge (this example currently doesn't work on android because of the use of QQuickWidget, but it works with qt 5.6)

Calling Go functions from Qml, works by using a QWidget as a proxy to receive Json encoded messages from Qml.

Calling Qml functions from Go, works by setting a "onPropertyChanged" method to receive Json encoded messages from Go. (the QMetaObject::invokeMethod, is currently not usable)

If you got any questions or run into problems, feel free to ask.

**Comment by longlongh4** [comment]
Hi
   I have tried both, the second way seems confused when project grows larger.  So I think the first way is better (even though we must make our hand dirty with C++, but who cares ^_^ ), I have sent a pull request to add an example about how to mix QObject signals&slots with golang .

    How about implement a go generator to auto implement bridge c++ class to do this, like code below:
`
//go:generate goQt blahblah...
type SignalHandler interface {
	ReceiveValueFromQml(value string) `qSignal`
	SendValueToQml(value string) `qSlot`
}
`

**Comment by therecipe** [comment]
Hey

Thanks for the pull request :)
I started working on a way to auto implement new signals and slots.
The "qtdeploy" tool will now execute a new tool called "qtmoc", which parses the local files and creates the needed files on the fly. 

The syntax will look like this:
```go
type SignalHandler struct {
	core.QObject

	_ func(value string) `signal:sendToQml`
	_ func(value string) `slot:callbackFromQml`
}
```

You will also be able to subclass these classes, so something like this will work also:

```go
type TopSignalHandler struct {
	SignalHandler

	_ func(value string) `signal:sendToQml2`
	_ func(value string) `slot:callbackFromQml2`
}
```

**Comment by therecipe** [comment]
Okay, I pushed the changes.

You can now execute `qtmoc` to generate the needed files.
I also updated the example [quick/bridge](https://github.com/therecipe/qt/tree/master/internal/examples/quick/bridge) and [quick/bridge2](https://github.com/therecipe/qt/tree/master/internal/examples/quick/bridge2).

**Comment by longlongh4** [comment]
That's great, thank you!
