### ISSUE TITLE
Connecting events methods

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#181]
Hi tr,

Since go does not allow circular references, when dealing with two panel widgets I need to share info between them. In this case I want to select a color from the pallete panel (using on mouse click event), then click on grid of second panel to plot that color (another click event).

If I connect these events in their structs, I cannot propagate information between. So I wanted to connect events at the top /window/ level (in main).

Example here:

https://github.com/5k3105/Sprite-Editor

Notice I am attempting to use your parameter trick to connect the click event at the top level (```ConnectSpriteEvents```).

This did not work. Maybe I am not casting correctly in the function, however it compiles but either does not run or immediately crashes. Instructions to run on readme of page.

**Comment by therecipe** [comment]
Hey

Nice project :)
Is this going to be an editor for pixel art?

Also I looked into why it crashes, and it seems to happen while casting from `interface{}` to `*sped.SpriteCell` with `it.Value().(*sped.SpriteCell)`
This happens because you initially put a `*widgets.QGraphicsWidget` with `se.Cells.Put(z, scell)` in there.
(It crashes at runtime because casting from a blank `interface{}` can't be checked by the compiler)

So you just need to modify `NewSpriteCell` to return a `*sped.SpriteCell` instead, to be able to use the index later in the `ConnectMousePressEvent`.

**Comment by 5k3105** [comment]
Yes, pixel editor. Good catch on the cast. It compiles and runs now, but when  click there is no response on the statusbar :/

**Comment by therecipe** [comment]
It updates the info on the lower left corner for me, when I click on one of the left cells (on mac)

**Comment by therecipe** [comment]
Works on windows as well.
It seems like you just commented out `ConnectSpriteEvents` with https://github.com/5k3105/Sprite-Editor/commit/4e76ef98ed911c66c505b0aa0ce9387b27987421

**Comment by 5k3105** [comment]
lol! sorry..

**Comment by therecipe** [comment]
No problem :D
