### ISSUE TITLE
How to add application icon?

### ISSUE THREAD

**Issue by akamensky** [therecipe/qt#183]
Subj

In Qt Creator it is simple to do from `.pro` file. It will add corresponding icon file as application icon.

How would I add application icon using this library when calling `qtdeploy`?

In case of Linux/Darwin this is rather simple to do with some modifications on output of qtdeploy afterwards. On Windows however this is not possible to do after the resulting binary has been built (as icon is embedded into binary).

**Comment by therecipe** [comment]
Yes, icons are currently only somewhat handled for the android and sailfish target. (Because there they need to be bundled and can't be changed afterwards)

The other targets need to do it manually currently.
(I planned to automatically detect a `icon.*` file in the main project folder and then act accordingly: https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/deploy.go#L556-L576)
But as it is rather simple to do manually, I hadn't looked into that for a long time.

To bundle a icon on windows, you need to use `windres`.
I had to look it up again, but the process is rather simple.

1. Create a file called `icon.rc` with the following content: (in your main project folder)
```
IDI_ICON1 ICON DISCARDABLE "icon.ico"
```

2. Get an icon called `icon.ico` and place it alongside the `icon.rc`

3. Invoke windres like this:
```
path/to/windres path/to/project/icon.rc -o path/to/project/icon_windows.syso
```
(windres.exe can be found inside the same folder as `rcc` on a windows system, usually `Qt5.7.0/5.7/mingw53_32/bin/windres.exe`)

4. Use `qtdeploy` or `go build` as usuall, the `*.syso` file should be automatically detected and be compiled into the binary, also the `*_windows` suffix makes sure that this is only done when you compile for windows.

And here are some more infos:
http://doc.qt.io/qt-5/appicon.html

**Comment by RadhiFadlillah** [comment]
Closed since it's old and has been documented [here](https://github.com/therecipe/qt/wiki/Setting-the-Application-Icon).
