### ISSUE TITLE
Possible performance issues

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#185]
Hi tr,

The editor is working now! (yay!) Select a color on the right and plot it by clicking on the left panel.

Before adding this line ```spcan.Scene.Update(spcan.Scene.ItemsBoundingRect())``` in the click event (in main file) the editor (https://github.com/5k3105/Sprite-Editor) was almost unusably slow :( I guess scene/viewport updating is handled with a timer? Now it is better but still a little laggy.

Memory usage is low starting at ~30mb but increases slowly and never garbage collects. I have seen it go over 100mb.

Also, qt seems to ignore my ```window.ShowMaximized()``` line. I get a mini-window every time.

Thanks for your help!

**Comment by therecipe** [comment]
Hey

I looked into it, and it seems like the "paint" functions are called very often (haven't measured it, but they are called atleast one time by every item per second resulting in atleast 512 calls of the function)
And that's just for the `SpriteCells`, the `FcpCells` behave the same, resulting in atleast twice the amount of "paint" calls per second.
And the hover events update every cell manually on "enter" and "leave" (which is not that problematic, but this should only used when really needed, so probably only by the `FcpCells` to update the text)

And one thing to keep in mind, that if you call "update" for an item like this `e.Widget().Update3(e.Widget().Rect())` (for the whole item), it will trigger the paint event of all contained items.
So this probably shouldn't be called on an "enter" or "leave" event event by the `SpriteEditor`

So now that it's clear that the "paint" functions are heavily used, you should try to optimize them as much as possible.
Only call the really needed functions, probably only use the "painter" and **don't** create stuff with `NewQ*` if not really needed, Go will collect the garbage but not as fast as it is created by the "paint" functions.
So you should cache everything that is later needed in the "paint" functions and really only make use of the "painter" there.

These are the changes that I made to make it work probably. (I only worked on the two most called paint functions)


Brush is exported, because it's set by the click signal later in "main"

```
type SpriteCell struct {
	*widgets.QGraphicsWidget
	Index   int
	over    bool
	R, G, B int

	font  *gui.QFont
	qpf   *core.QPointF
	Brush *gui.QBrush
	path  *gui.QPainterPath
}
```

`font` and `qpf` can be probably shared with the other sprite cells as well and therefore don't really need to be created for every cell.

```
func NewSpriteCell(parent *SpriteEditor, idx int) *SpriteCell { //*widgets.QGraphicsWidget {

	sc := &SpriteCell{
		QGraphicsWidget: widgets.NewQGraphicsWidget(nil, 0), // parent, 0) // type widget
		Index:           idx,

		font: gui.NewQFont2("verdana", 7, 1, false),
		qpf:  core.NewQPointF3(1.0, 1.0),
		path: gui.NewQPainterPath(),
	}
	var color = gui.NewQColor3(sc.R, sc.G, sc.B, 255) // r, g, b, a
	sc.Brush = gui.NewQBrush3(color, 1)

	sc.SetAcceptHoverEvents(true)
	sc.ConnectPaint(sc.Paint)
	sc.ConnectHoverEnterEvent(sc.HoverEnter)
	sc.ConnectHoverLeaveEvent(sc.HoverLeave)

	return sc //.QGraphicsWidget
}
```

Only call what is really needed, and don't create new garbage

```
func (sc *SpriteCell) Paint(p *gui.QPainter, o *widgets.QStyleOptionGraphicsItem, w *widgets.QWidget) {

	if sc.path.IsEmpty() {
		sc.path.AddRect(core.NewQRectF5(o.Rect())) //will only be called once, with the first paint event (as the painter is always the same for each cell)
	}

	p.SetFont(sc.font)
	p.DrawPath(sc.path)
	p.FillPath(sc.path, sc.Brush)

	if sc.over {

		p.DrawText(sc.qpf, "")
		//p.DrawText(qpf, "r"+strconv.Itoa(sc.R)+"g"+strconv.Itoa(sc.G)+"b"+strconv.Itoa(sc.B))

	} else {
		p.DrawText(sc.qpf, "")
		//p.DrawText(qpf, strconv.Itoa(sc.Index))

	}

}
```

Set the new brush color directly here as well, so that it can be used inside the "paint" call

```
func SpriteCellClick(sc *sped.SpriteCell, spcan *sped.SpriteCanvas) func(event *widgets.QGraphicsSceneMouseEvent) {
	return func(event *widgets.QGraphicsSceneMouseEvent) {

		sc.R, sc.G, sc.B = r, g, b
		var color = gui.NewQColor3(sc.R, sc.G, sc.B, 255) // r, g, b, a
		sc.Brush.SetColor(color)

		spcan.Scene.Update(spcan.Scene.ItemsBoundingRect())

		statusbar.ShowMessage(strconv.Itoa(sc.Index), 0)
		sc.MousePressEventDefault(event)

	}
}
```

And I made similar changes for `FcpCell` as well

```
type FcpCell struct {
	*widgets.QGraphicsWidget
	Index   int
	over    bool
	R, G, B int

	font  *gui.QFont
	qpf   *core.QPointF
	brush *gui.QBrush
	path  *gui.QPainterPath
}
```

```
func NewFcpCell(cp *FullColorPallete, idx int) *FcpCell {

	fc := &FcpCell{
		QGraphicsWidget: widgets.NewQGraphicsWidget(nil, 0), //cp, 0) // type widget
		Index:           idx,
		R:               cp.pal.r[idx],
		G:               cp.pal.g[idx],
		B:               cp.pal.b[idx],

		font: gui.NewQFont2("verdana", 7, 1, false),
		qpf:  core.NewQPointF3(1.0, 1.0),
		path: gui.NewQPainterPath(),
	}
	var color = gui.NewQColor3(fc.R, fc.G, fc.B, 255) // r, g, b, a
	fc.brush = gui.NewQBrush3(color, 1)

	fc.SetAcceptHoverEvents(true)
	fc.ConnectPaint(fc.Paint)
	fc.ConnectHoverEnterEvent(fc.HoverEnter)
	fc.ConnectHoverLeaveEvent(fc.HoverLeave)

	return fc
}
```

```
func (fc *FcpCell) Paint(p *gui.QPainter, o *widgets.QStyleOptionGraphicsItem, w *widgets.QWidget) {

	if fc.path.IsEmpty() {
		fc.path.AddRect(core.NewQRectF5(o.Rect()))
	}

	p.SetFont(fc.font)
	p.DrawPath(fc.path)
	p.FillPath(fc.path, fc.brush)

	if fc.over {

		p.DrawText(fc.qpf, "r"+strconv.Itoa(fc.R)+"g"+strconv.Itoa(fc.G)+"b"+strconv.Itoa(fc.B))

	} else {

		p.DrawText(fc.qpf, strconv.Itoa(fc.Index))

	}
}
```

Hope that was everything I changed, can't really get a proper diff because of different line ending from windows.

Maybe create a counter to get a feeling about how often each function is called, you will probably be surprised (I was :D)

>Also, qt seems to ignore my window.ShowMaximized() line. I get a mini-window every time.

I will look into it.

**Comment by 5k3105** [comment]
Everything perfectly fixed!

Stays around 22.5MB. Speed is as fast as I can click.

Excellent work tr!

Thank you so much!
