### ISSUE TITLE
Installation in Windows 10: Unable to find the platform plugin.

### ISSUE THREAD

**Issue by CarmeloViavattene** [therecipe/qt#187]
Installation with: 
Install the official prebuilt package; you can also define a custom location with QT_DIR.
https://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-windows-x86-android-5.7.0.exe

C:\Mega\gopath\src>..\bin\qtsetup
time="2017-01-09T00:29:21+01:00" level=info msg="running setup/prep"
time="2017-01-09T00:29:21+01:00" level=info msg="running setup/check desktop"
time="2017-01-09T00:29:21+01:00" level=info msg="VERSION: 0.0.4"
time="2017-01-09T00:29:21+01:00" level=info msg="GOOS: windows"
time="2017-01-09T00:29:21+01:00" level=info msg="GOARCH: amd64"
time="2017-01-09T00:29:21+01:00" level=info msg="GOVERSION: go1.7.4"
time="2017-01-09T00:29:21+01:00" level=info msg="GOROOT: C:\\Go\\"
time="2017-01-09T00:29:21+01:00" level=info msg="GOPATH: C:\\Mega\\GOPATH\\"
time="2017-01-09T00:29:21+01:00" level=info msg="GOBIN: C:\\Mega\\GOPATH\\bin"
time="2017-01-09T00:29:22+01:00" level=info msg="HASH: 9d86d8aac3d6aecccc95f1755ab8fa15d6a21964"
time="2017-01-09T00:29:22+01:00" level=info msg="QT_VERSION: 5.7.0"
time="2017-01-09T00:29:22+01:00" level=info msg="QT_VERSION_MAJOR: 5.7"
time="2017-01-09T00:29:22+01:00" level=info msg="QT_DIR: C:\\Qt\\Qt5.7.0"
time="2017-01-09T00:29:22+01:00" level=info msg="QT_STUB: false"
time="2017-01-09T00:29:22+01:00" level=info msg="MSYSTEM: "
time="2017-01-09T00:29:22+01:00" level=info msg="QT_MSYS2: "
time="2017-01-09T00:29:22+01:00" level=info msg="QT_MSYS2_DIR: "
time="2017-01-09T00:29:22+01:00" level=info msg="IsMsys2QtDir: false"
time="2017-01-09T00:29:22+01:00" level=info msg="UseMsys2: false"
time="2017-01-09T00:29:22+01:00" level=info msg="running setup/generate"
time="2017-01-09T00:29:33+01:00" level=info msg="generating full qt/core"
time="2017-01-09T00:30:14+01:00" level=info msg="generating full qt/androidextras"
...
...
...
time="2017-01-09T00:55:28+01:00" level=info msg="installing full qt/quickcontrols2"
time="2017-01-09T00:55:33+01:00" level=info msg="installing full qt/sailfish"
time="2017-01-09T00:55:36+01:00" level=info msg="installing full qt/sailfish"
time="2017-01-09T00:55:37+01:00" level=info msg="installing full qt/sailfish"
time="2017-01-09T00:55:37+01:00" level=info msg="installing full qt/sailfish"
time="2017-01-09T00:55:38+01:00" level=info msg="installing full qt/sailfish"
time="2017-01-09T00:55:39+01:00" level=info msg="running setup/test desktop (~10min)"
time="2017-01-09T00:55:39+01:00" level=info msg="testing widgets\\line_edits"
time="2017-01-09T00:56:07+01:00" level=error msg="failed to run command" cmd="C:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\bin\\windeployqt C:\\Mega\\GOPATH\\src\\github.com\\therecipe\\qt\\internal\\examples\\widgets\\line_edits\\deploy\\windows_minimal\\line_edits.exe -qmldir=C:\\Mega\\GOPATH\\src\\github.com\\therecipe\\qt\\internal\\examples\\widgets\\line_edits -force" error="exit status 1" func=RunCmd name="depoy desktop on windows"
C:\Mega\GOPATH\src\github.com\therecipe\qt\internal\examples\widgets\line_edits\deploy\windows_minimal\line_edits.exe 32 bit, release executable
Direct dependencies: Qt5Core Qt5Gui Qt5Widgets
All dependencies   : Qt5Core Qt5Gui Qt5Widgets
To be deployed     : Qt5Core Qt5Gui Qt5Widgets
Unable to find the platform plugin.

Can You Help me?
can you explain how to solve this problem of the plugin?
from where and where to copy them?
or I have to set any environment variable?

Thank You

**Comment by therecipe** [comment]
Hey

This usually should work, because you already were able to successfully install the packages.
So there should no need to set any additional env variables or such.

Could you maybe try to build the examples manually with `qtdeploy build desktop path/to/example`?

Also you could try to use `C:\Qt\Qt5.7.0\5.7\mingw53_32\bin\windeployqt.exe path/to/project.exe` after you build you project with the usuall `go build -o project.exe` instead of `qtdeploy`

Also did you maybe moved you the Qt installation to `C:\Qt\Qt5.7.0`? Or did you really install it there?
`windeployqt.exe` maybe still uses the old path, if it was moved.

**Comment by CarmeloViavattene** [comment]
reinstalled in a new fresh Windows: All work

Only a problem: 

I try to compile Your example: with qtdeploy, it work.

If i want to use go, i see this error:

C:\MEGA\GOPATH\src\qtExample>go run main.go
# github.com/therecipe/qt/core
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

Can You help me?

Qt windows is 32 bit
Go is 64 bit "GOARCH: amd64"

Then, i think the the solution is:
1) install mingw-w64
2) not  Add the directory that contains gcc and g++ to your PATH C:\Qt\Qt5.7.0\Tools\mingw530_32\bin
3) Add the directory of mingw-w64 that contains gcc and g++ to your PATH
4) %GOPATH%\bin\qtsetup

Is correct?

**Comment by therecipe** [comment]
I'm not sure if `mingw-w64` works with the Qt libs, because those were compiled with mingw32.

On windows you need to set `GOARCH=386` and `CGO_ENABLED=1` first to let the go compiler work along with the "default" mingw32 gcc.

Here are the env variables `qtdeploy` uses for `go build` on windows: https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/deploy.go#L257-L271

Also you need to use `$QT_DIR/5.7/mingw32_53/bin/windeployqt.exe path/to/your/project.exe`
(hope `.../mingw32_53/...` is correct)

To get the *.dlls, which are needed for this to work on windows.
(on mac and linux you don't need to do that during development)

Also you can probably just call `windeployqt.exe` once, and then just `go build -o ...` the app in the dir with the *.dlls, so that you don't have to use `windeployqt.exe` everytime.
