### ISSUE TITLE
QAbstractTableModel: emit dataChanged

### ISSUE THREAD

**Issue by fabstu** [therecipe/qt#189]
Is it possible to emit dataChanged today?

**Comment by therecipe** [comment]
Hey

No, unfortunately http://doc.qt.io/qt-5/qabstractitemmodel.html#dataChanged is not available yet.
Because it uses the generic QVector class.
I already wrote a little about generic lists / containers a few days ago https://github.com/therecipe/qt/issues/140#issuecomment-270680060
And there are a few other issues related to this.

But to sum it up, support for these generic lists / containers has a high priority and I will continue to work on it asap.

**Comment by fabstu** [comment]
Very nice!

**Comment by therecipe** [comment]
@fabstu 

generic lists / containers are now supported with: https://github.com/therecipe/qt/commit/3456e5280a438b31c6c4529ef86e465ba190ef7d

here is also an example:
https://github.com/therecipe/qt/tree/master/internal/examples/quick/listview

**Comment by fabstu** [comment]
Very interesting, thank you!
