### ISSUE TITLE
Issues with porting over QML controls from cmake to golang

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#192]
i am trying to port over some QML controls from a c-make project, but i think some bits are missing:

i need the following primitive qml types:
qtbase - not sure
qtdeclarative - yes
qtgraphicaleffects - not in this repo
qtquickcontrols2 - fine
qtsvg - fine

So, qtgraphicaleffects is the main one missing.

Here are the QML controls btw:
https://github.com/lirios/fluid

What do you think ?

**Comment by therecipe** [comment]
Hey

>i need the following primitive qml types:
>qtbase - not sure
>qtgraphicaleffects - not in this repo

qtbase is just core, gui, widgets, network and some modules and these should be all available.
qtgraphicaleffects iirc is a qml only module, so it is available as well.

>What do you think ?
It looks good, it seems to be the successor of qml-material?

There are two things that I think can be problematic. (but maybe are not)
1. https://github.com/lirios/fluid/blob/f342b75c92bacd97c0a016e58c97b70ccb89ee07/controls/plugin.cpp#L22
There is the `Q_PLUGIN_METADATA` macro used, which is not available for the binding yet.
(But I can add it, so that's no big problem)

2. I'm not sure what is needed to deploy in the end to make this lib/module available for others to use. (In c++ you might need to deploy a *.so and the *.qml files, but I'm not really sure)

If you are lucky the *.qml can all be compiled inside your go package with the help of `qtrcc` and so someone who would want to use your packages just needs to import your package passively with
`_ github.com/joeblew99/fluid` or something. (and has no additional dependencies)

(Also there might be the need that people who want to use your package need to run `qtrcc` and/or `qtmoc` inside your package first before installing it with `go install`)

**Comment by joeblew99** [comment]
thanks.

Regarding your question...
Actually Google have a new project for Material Design, and call it "Material Components".
https://github.com/material-components
The Web, Android and IOS components are not the same name though, and i want a MC (Material Components) library that can be used on Desktop and Mobile with the same QML.

So then i found https://github.com/lirios/fluid, and noticed its designed for Desktop and Mobile.
So am trying those out, and wanted your opinion.
lirios is sponsored by Ubuntu from what i can see. I reckon Mark Shuttleworth is going all in on QT....
Could be wrong of course. Anyway...
---

I am wondering if its a smart move to setup a 2nd repo in therecipe with a  Material Component lib that supports Desktop and Mobile ? 
There are so many people reinventing the QML Material design wheel.
Or maybe someone else here if really up for it...

https://github.com/benlau/quickandroid/blob/master/README.md

https://github.com/evonove/mut

many more...

**Comment by therecipe** [comment]
>Actually Google have a new project for Material Design, and call it "Material Components".
https://github.com/material-components
The Web, Android and IOS components are not the same name though, and i want a MC (Material Components) library that can be used on Desktop and Mobile with the same QML.

Ah, thanks for clarifying that :)

>So then i found https://github.com/lirios/fluid, and noticed its designed for Desktop and Mobile.

Those screenshots look great https://liri.io/screenshots/

>I am wondering if its a smart move to setup a 2nd repo in therecipe with a Material Component lib that supports Desktop and Mobile ?
There are so many people reinventing the QML Material design wheel.
Or maybe someone else here if really up for it...

I will put it on my TODO list, but I'm not sure how long it would take me to start working on this.
As I pretty much have already planned this and the next month.

But as only 20% of the code in lirios/fluid is c++ it should be possible to port this over quickly once started.

**Comment by joeblew99** [comment]
maybe its best, since you have lots of other stuff to do ?
there is Gallery and drawer-Nav example for now.

**Comment by therecipe** [comment]
Just keep it open and I will comeback to it.
I'm currently busy working on a great reduction of the generated code.
When I'm done with that, I will update the readme and revisit the outstanding issues.

**Comment by joeblew99** [comment]
@therecipe saw the new qmake refactoring.

lirios also switched recently from cmake to qmake.
I think we should try out getting the fluid demo's going :)

**Comment by therecipe** [comment]
I will look into it later today.

**Comment by joeblew99** [comment]
thanks -  I am really interested to try out their components. They have a huge amount of momentum so we are no reinventing the wheel too much.
