### ISSUE TITLE
Can't Run qtsetup rpi2

### ISSUE THREAD

**Issue by gabeart10** [therecipe/qt#193]
I have tried reinstalling qt, rerunning the make, etc. However, I get the error below every time I run qtsetup rpi2

`# github.com/therecipe/qt/core
../../../../core/core-minimal.cpp:9:30: fatal error: QAbstractAnimation: No such file or directory
 #include <QAbstractAnimation>
                              ^
compilation terminated.`

**Comment by therecipe** [comment]
Hey

Did you setup arch on the rpi, pulled the sysroot and the compiled Qt with the cross compiler?
And now the only thing that is failing is `qtsetup`?

**Comment by gabeart10** [comment]
Yes, I have. However, I did them on the linux system because it never said to go back on the pi after the reboot. That might be my problem, but idk.

**Comment by therecipe** [comment]
No that was correct, you pull the sysroot from the rpi and then compile Qt and later cross compile on your desktop. (It probably would somehow work directly on rpi as well, but I haven't tested that)

And I haven't tested the rpi setup in a long time, so maybe there could be a bug that I need to fix first.

But the error above seems just like there is some mis-configuration with the `QT_DIR` or something.

Did you defined an alternative `QT_DIR`?
(If you did, then could you maybe symlink or move `/usr/local/Qt5.7.0/5.7/rpi2` into your real QT_DIR?
So that the rpi2 folder can be found in `QT_DIR/5.7/`?

Or if you didn't defined a `QT_DIR` at all, could you set it to `/usr/local/Qt5.7.0` and the try again?

**Comment by gabeart10** [comment]
Ok, so I did not change the QT_DIR. I did what you said and I think it work, but when I ran it install extremely fast. I do not know if that is normal?

**Comment by therecipe** [comment]
Yes, it will skip the installation for non desktop targets. (as it won't be really useful anyway)
Did the setup build the examples successfully?
And/or are you able to use `qtdeploy build rpi2 path/to/project` to compile an example successfully?

**Comment by gabeart10** [comment]
Got this `ERRO[0000] failed to run command                         cmd="/usr/local/Qt5.7.0/5.7/gcc_64/bin/rcc -project -o /home/gabe/go/src/test/rrc.qrc" error="fork/exec /usr/local/Qt5.7.0/5.7/gcc_64/bin/rcc: no such file or directory" func=RunCmd name="execute rcc.1 on linux"
`

**Comment by therecipe** [comment]
You probably didn't installed the desktop version of Qt first or?

You need to install the pre-build desktop version in `/usr/local/Qt5.7.0` as well.
So that you in the end you have the `gcc_64` and `rpi2` folder in  `/usr/local/Qt5.7.0/5.7/`.

You may need to manually merge the `rpi2` folder inside the desktop Qt installation now, because just installing Qt to `/usr/local/Qt5.7.0/` will probably remove the `rpi2` folder in `/usr/local/Qt5.7.0/5.7/`, but I'm not sure about that.

In the end you can verify that everything is correctly setup by running:
`qtsetup desktop && qtsetup rpi2`
or just
`qtsetup desktop test && qtsetup rpi2 test`
which is faster because it doesn't installs the packages for the desktop version

**Comment by gabeart10** [comment]
Quick question while I am doing this, but would it be possible to do this on macOS instead of linux. I can put this in a new issue if you would like.

**Comment by therecipe** [comment]
It would be possible, but I haven't tested that because there was no official cross compiler for macOS.
The only official ones are sadly only for linux https://github.com/raspberrypi/tools

So you would need to get some 3rd party cross compiler, iirc there are some here https://www.linaro.org/downloads/ but I didn't test them.

Btw, there are pre-build Qt packages for rpi now here: http://www.qtrpi.com/home
But I haven't tested them yet, and they also seem to use a raspbian sysroot instead of an arch one.

**Comment by gabeart10** [comment]
I will instead see if I can get your packages working with the qtrpi, I will report if I can get anything working.

**Comment by gabeart10** [comment]
I'm just going to try starting from scratch.

**Comment by therecipe** [comment]
Okay.
