### ISSUE TITLE
Compiles started giving "Warning: Unused paramater"

### ISSUE THREAD

**Issue by asakaplan** [therecipe/qt#206]
I seemingly randomly started to get a bunch of errors of the form 

```
/tmp/go-build182607415/github.com/therecipe/qt/core/_obj/_cgo_main.c: In function ‘_cgo_allocate’:
/tmp/go-build182607415/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:26: warning: unused parameter ‘a’ [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                          ^
/tmp/go-build182607415/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:33: warning: unused parameter ‘c’ [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                                 ^
/tmp/go-build182607415/github.com/therecipe/qt/core/_obj/_cgo_main.c: In function ‘_cgo_panic’:
/tmp/go-build182607415/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:23: warning: unused parameter ‘a’ [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                       ^
/tmp/go-build182607415/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:30: warning: unused parameter ‘c’ [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
...
```

These happen whenever I use the library. Nothing in my code changed (checking out a previous version still gives this), and I tried reinstalling the binding altogether, with no success. The code still ends up running (without deploying), but it takes significantly longer to compile.

System info:

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by therecipe** [comment]
Hey

Yes, these are just warnings, some of them are expected to show up when you compile cgo code and some of them (`unused parameter ‘ptr’`) are my fault. But they are not problematic.
And they also only show up if the packages weren't previously installed.

If you use `go build` then you might want to use the `-i` flag, to also install the compiled packages.
Or you may want to run `qtsetup install` to install all packages if necessary.

If you use `qtminimal` with `go build -tags=minimal`, then there is nothing that can be done about this. Because `qtminimal` changes the code with each invocation and therefore installing the packages would be useless.

**Comment by asakaplan** [comment]
I forgot to say, thanks for the quick advice, using the -i flag got rid of the warnings and made it build with the same speed as it did before!
