### ISSUE TITLE
Windows build don't include all required DLLs

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#221]
Source: https://github.com/therecipe/qt/tree/master/internal/examples/qml/application

```
~/src/github.com/therecipe/qt/internal/examples/qml/application qtdeploy build windows . docker
```

As I don't see windows do have a `ldd` equivalent, I use `wine` to do initial tests:

```
~/src/github.com/therecipe/qt/internal/examples/qml/application wine deploy/windows_minimal/application.exe 
err:module:import_dll Library Qt5Quick.dll (which is needed by L"Z:\\home\\bruno\\src\\github.com\\therecipe\\qt\\internal\\examples\\qml\\application\\deploy\\windows_minimal\\QtQuick.2\\qtquick2plugin.dll") not found
```

I copy that file from docker image and run again:

```
~/src/github.com/therecipe/qt/internal/examples/qml/application wine deploy/windows_minimal/application.exe 
err:module:import_dll Library Qt5QuickControls2.dll (which is needed by L"Z:\\home\\bruno\\src\\github.com\\therecipe\\qt\\internal\\examples\\qml\\application\\deploy\\windows_minimal\\QtQuick\\Controls.2\\qtquickcontrols2plugin.dll") not found
err:module:import_dll Library Qt5QuickTemplates2.dll (which is needed by L"Z:\\home\\bruno\\src\\github.com\\therecipe\\qt\\internal\\examples\\qml\\application\\deploy\\windows_minimal\\QtQuick\\Controls.2\\qtquickcontrols2plugin.dll") not found
```

Manually copy those again: 

```
~/src/github.com/therecipe/qt/internal/examples/qml/application wine deploy/windows_minimal/application.exe 
```

and it works:

![screenshot from 2017-02-07 14-25-02](https://cloud.githubusercontent.com/assets/474302/22680394/a3f838fe-ed42-11e6-88ef-2d55cfa82fe3.png)

**Comment by therecipe** [comment]
Hey

Should be fixed with https://github.com/therecipe/qt/commit/6f2791edd054b9a7cd8370db64761105f47783fb

The problem was that the `Qt5Quick*.dll` dependencies get pulled in through [these](https://github.com/therecipe/qt/blob/master/internal/examples/qml/application/qml/application.qml#L43-L45) imports in qml rather then being directly linked as usual.
(direct linked dependencies are easily detectable with
`/usr/lib/mxe/usr/bin/i686-w64-mingw32.shared-objdump -x path/to/project.exe` on linux with mxe)

The perfect solution would be to let qtdeploy scan the project qml files for imports and then resolve the dependencies, but then I'm probably better of porting `windeployqt` directly, so I'm pushing that back for now)

So instead of letting qtdeploy scan the qml files for the imports, the `Qt5Quick*.dll` libs will be deployed now, whether or not they are needed. (The same was already happening for the plugins in general)

**Comment by bclermont** [comment]
> Should be fixed with 6f2791e

thanks, I will test that today

Are `.dll` loaded at runtime when a QML refers import something new?

because if that is the case, I have a problem. because I have this dynamically loaded QML from a backend service. from build process, we can't know what will be the required list of dependencies.

should I do something like:

```
import (
 _ "github.com/therecipe/qt/$something"
)
```

to force `.dll` to be included along with `.exe`?

**Comment by therecipe** [comment]
>Are .dll loaded at runtime when a QML refers import something new?

Yes, I think that happens for some dlls.

>because if that is the case, I have a problem. because I have this dynamically loaded QML

You can probably create a dummy *.qml file like this one https://github.com/therecipe/qt/blob/master/internal/examples/quick/dynamic/qml/dynamic.qml
for compiling, which then imports all the modules that may be used later.

Also you can import
```go
import (
  _ "github.com/therecipe/qt/qml"
  _ "github.com/therecipe/qt/quick"
  _ "github.com/therecipe/qt/quickcontrols2"
)
```
in Go, to work around the initial issue and to include all c++/go qml/quick modules.

I think as long as you don't dynamically load something completely different later, you should be good.

**Comment by bclermont** [comment]
that seem to be fixed now, thanks
