### ISSUE TITLE
Undefined a New* function

### ISSUE THREAD

**Issue by AnyCPU** [therecipe/qt#225]
Hello,

I have following lines in my code
```
type GoQTextCharFormat struct {
	gui.QTextCharFormat
}
func InitGoQTextCharFormat() *GoQTextCharFormat {
	ret := NewGoQTextCharFormat()
	return ret
}
type GoQSyntaxHighlighter struct {
	gui.QSyntaxHighlighter
}
func InitGoQSyntaxHighlighter(doc *gui.QTextDocument) *GoQSyntaxHighlighter {
	ret := NewGoQSyntaxHighlighter(doc)
        return ret
}
```
So the function NewGoQSyntaxHighlighter is auto-generated and available, but
the function NewGoQTextCharFormat doesn't exist.
The question is why?

**Comment by therecipe** [comment]
Hey

Yes, subclassing with `qtmoc` currently only works for classes that inherit `QObject`.

So, it works for`gui.QSyntaxHighlighter`, because it's derived from `QObject`
http://doc.qt.io/qt-5/QSyntaxHighlighter.html
and not for `gui.QTextCharFormat`, because it's not http://doc.qt.io/qt-5/qtextcharformat.html.

Also, even when you would subclass `gui.QTextCharFormat`, it won't be possible to add your own signals/slots/properties.

But you could also write it like this:
```go
type GoQTextCharFormat struct {
	*gui.QTextCharFormat
}
func InitGoQTextCharFormat() *GoQTextCharFormat {
	ret := &GoQTextCharFormat{QTextCharFormat: gui.NewQTextCharFormat()}
	return ret
}
```

Or like this:

```go
package main

/* is not derived from QObject */
type GoQTextCharFormat struct {
	*gui.QTextCharFormat
}

func (f *GoQTextCharFormat) init() {
	/* do something here */
}

func NewGoQTextCharFormat() *GoQTextCharFormat {
	ret := &GoQTextCharFormat{QTextCharFormat: gui.NewQTextCharFormat()}
	ret.init()
	return ret
}

/* is derived from QObject */
type GoQSyntaxHighlighter struct {
	gui.QSyntaxHighlighter

	_ func() `constructor:"init"`
}

func (h *GoQSyntaxHighlighter) init() {
	/*
		will be called after the object is created with New*
		to connect signals/slots or to set default properties ...
	*/
}
```

and then just use the New* (constructor) functions (instead of Init* functions)

I might make it possible to subclass non QObject derived classes in the future.
But I will have to think about it first.

**Comment by AnyCPU** [comment]
@therecipe  thank you very much.
