### ISSUE TITLE
How to static build applications?

### ISSUE THREAD

**Issue by stillwarter** [therecipe/qt#230]
I don't want these qt*.dll files.

**Comment by bclermont** [comment]
AFAIK, Statically link qt open source version isn't allowed

**Comment by therecipe** [comment]
Hey

Static linking should work, but it's not supported out of the box yet.
So you would currently need to add the missing parts yourself (mostly CFLAGS and LDFLAGS)
and also rebuild Qt (not the binding) from source with the -static option. (or use the mxe versions, to cross compile to windows from linux, if you don't want build it from source)

You can also find two static build scripts here: https://github.com/therecipe/qt/issues/55 (a linux and an mxe one to cross compile to windows)

And also depending on your use, you need to keep in mind what @bclermont said.
>AFAIK, Statically link qt open source version isn't allowed

If you static link against the Qt libs and intend to deploy your application, you will need to either open source it under GPL or buy a commercial Qt license, IIRC. https://www.qt.io/faq/#_Toc_3_7

**Comment by joeblew99** [comment]
So as things are now, when I build for desktop and distribute it to my coworker, they have to have Qt installed ?

And for mobile, I assume that Qt is compile in with the all ?

Sorry about my lack of knowledge in this area.

**Comment by stillwarter** [comment]
Thanks a lot! @therecipe @bclermont

**Comment by therecipe** [comment]
@joeblew99
>So as things are now, when I build for desktop and distribute it to my coworker, they have to have Qt installed ?

Not when you use `qtdeploy`, then the deploy folder should contain everything to run you application on a "clean" pc.

>And for mobile, I assume that Qt is compile in with the all ?

Yes, for mobile targets, all the libs an such are bundled inside the *.apk or *.app, so that's all you need distribute.

@stillwarter
No, problem.
I started working on some changes that will make static linking way easier.

**Comment by joeblew99** [comment]
@therecipe got it - just had to check.
I tried it today with a friend onto a clean PC. run like a charm with no QT in sight.

**Comment by lxn** [comment]
> If you static link against the Qt libs and intend to deploy your application, you will need to either open source it under GPL or buy a commercial Qt license, IIRC. https://www.qt.io/faq/#_Toc_3_7

Isn't your LGPL licensed Go library forcing everyone using it to license their code under [L]GPL as well?

**Comment by therecipe** [comment]
@lxn

No, afaik LGPL isn't viral as long as it is "works that use the library" (what most people do).
And not "works based on the library", that one would require you to license your work under [L]GPL as well.
These are two different scenarios / use cases.

Taken from here: https://copyleft.org/guide/comprehensive-gpl-guidech11.html#x14-10000010.4


So this is how I understand the requirements for "works that use the library":

If you dynamically link against LGPL libs, then your are good, because the user has the possibility to just swap the *.dll / *.so against a modified version.
This is how "qtdeploy" currently links against the Qt libs.

But if you statically link against LGPL, then your are required to provide some way for the user to re-link against a modified version of the LGPL library.
This is how "qtdeploy" (and Go in general) links against Go libs and so also against the glue code from this binding.

Taken from here: https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic

So it seems like you already need to provide the user with the necessary info to re-link your app against this binding, whether or not you link against Qt dynamically or statically.

@stillwarter This also means that I was wrong with:
>If you static link against the Qt libs and intend to deploy your application, you will need to either open source it under GPL or buy a commercial Qt license, IIRC. https://www.qt.io/faq/#_Toc_3_7

And that statically linking against Qt doesn't force you to use GPL or their commerical version automatically, but if you can't comply the LGPL license (providing a way to re-link), then your can fallback to either their GPL or commercial license.


So this brings up two things that I wasn't really aware yet:
1. That you need to provide the user with the intermediate object format of your application, when you use this binding and intend to deploy your application.
2. That if you statically linking against Qt, then there are no further requirements then to comply with the first point.


I tested the re-linking of an application in object format (it was an *.a) against a modified version of this binding, and it was pretty straightford.
This means, I can possibly provide an additional automated way to help users of this binding to comply with Qt's (and this binding's) LGPL license (**also when they static linking against the Qt libs**).
Which then let's everybody easily use the advantages of static linking.

If I did understand it right, then it would be a huge thing :)
With the minor drawback, that the distribution of the object format it also necessary, if you link against Qt dynamically. (Because Go only supports static linking against Go libs at the moment)
But that will fall away once Go supports dynamic linking against Go libs, and that should happen with Go 1.9 IIRC.


Also if you don't intent to distribute your application at all, then you probably can ignore the legal stuff, but IANAL.


Some more infos:
https://www.qt.io/qt-licensing-terms/
https://choosealicense.com/licenses/lgpl-3.0/
