### ISSUE TITLE
5.8 QT Designer build: missing header

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#232]
```
INFO[0356] installing full qt/designer
DEBU[0356] Execute                                       cmd="go install -p 4 -v github.com/therecipe/qt/designer" func=RunCmdOptional name=install.designer
ERRO[0359] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/designer" error="exit status 2" func=RunCmdOptional name=install.designer
github.com/therecipe/qt/designer
# github.com/therecipe/qt/designer
In file included from ../designer/designer.cpp:21:
/Users/eva/Qt5.8.0/5.8/clang_64/lib/QtDesigner.framework/Headers/QDesignerCustomWidgetCollectionInterface:4:4: warning: Header <QtDesigner/QDesignerCustomWidgetCollectionInterface> is deprecated. Please include <QtUiPlugin/QDesignerCustomWidgetCollectionInterface> instead. [-W#warnings]
/Users/eva/Qt5.8.0/5.8/clang_64/lib/QtDesigner.framework/Headers/QDesignerCustomWidgetCollectionInterface:8:10: fatal error: 'QtUiPlugin/QDesignerCustomWidgetCollectionInterface' file not found
```

**Comment by therecipe** [comment]
I'm currently making some changes to the cgo* files in general, it will probably also solve this.
If not, then this "QDesignerCustomWidgetCollectionInterface" class will be simply blacklisted.

**Comment by joeblew99** [comment]
i can reproduce that.
i just did a clean install of qt5,8 and the repo.
got same error 

````
ERRO[0523] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/designer" error="exit status 2" func=RunCmdOptional name=install.designer
github.com/therecipe/qt/designer
# github.com/therecipe/qt/designer
In file included from qt/designer/designer.cpp:21:
/Users/apple/Qt5.8.0/5.8/clang_64/lib/QtDesigner.framework/Headers/QDesignerCustomWidgetCollectionInterface:4:4: warning: Header <QtDesigner/QDesignerCustomWidgetCollectionInterface> is deprecated. Please include <QtUiPlugin/QDesignerCustomWidgetCollectionInterface> instead. [-W#warnings]
/Users/apple/Qt5.8.0/5.8/clang_64/lib/QtDesigner.framework/Headers/QDesignerCustomWidgetCollectionInterface:8:10: fatal error: 'QtUiPlugin/QDesignerCustomWidgetCollectionInterface' file not found

````

**Comment by joeblew99** [comment]
wondering if at some stage we should think about to using a "Dev" branch for unstable dev stuff.
"Master" being stable and what everyone go gets.

**Comment by therecipe** [comment]
@joeblew99 

Yeah, I thought about that as well, but don't feel like the time is right for that yet.
I will introduce dev/feature branches at some point (probably when I feel like 1.0 is reached), but I currently "misuse" the master to get quicker feedback.
But I also try my very best to keep the master stable.
At the moment, you probably should pin the repo to a commit that is known to work, so that you can easily update or rollback.
(And I'm also somewhat waiting for the official Go package manager, to make things simpler)

**Comment by joeblew99** [comment]
@therecipe Thanks for the feedback.

Regarding the new golang package manager. I peeked at the code and it looks like glide is going to wrap it. So maybe if you go with glide you will get a nice upgrade path. Something to think about maybe

Regarding branching, i will do pinning for now. Good idea :)

**Comment by therecipe** [comment]
No problem ;)

I already looked into glide, but there don't seem to be enough benefits to use it for now.
The problem is that this lib has only a few minor go deps and the rest are non-go deps.
And glide don't seems to be intended to handle these as well.

I however intend support the official go dep tool, as it's probably expected to work with it.
And there also seem to be efforts to make the use of cgo libs more straight fort.

**Comment by joeblew99** [comment]
ok sounds like you have your eye on the prize..

**Comment by skiz** [comment]
So what would you suggest people do to handle this at this point?  Can you suggest a specific SHA?

**Comment by therecipe** [comment]
@skiz 

>So what would you suggest people do to handle this at this point?
>Can you suggest a specific SHA?

Just use the current master and stick with it until you need to update.
The thing is, you can probably take any commit from the last few month and they all should be stable, as I intent to never break the master on purpose and only push stuff that was tested first.
