### ISSUE TITLE
Style Sheet file import paths

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#265]
Hi,

Where would the application lookup these files? I attempted to trace it in procmon (Win7) but it didn't appear to look for these files at all.

```go
tree.SetStyleSheet(`
QTreeWidget::branch:has-siblings:!adjoins-item {
    border-image: url(:/tree/vline.png) 0;
}

QTreeWidget::branch:has-siblings:adjoins-item {
    border-image: url(:/tree/branch-more.png) 0;
}

QTreeWidget::branch:!has-children:!has-siblings:adjoins-item {
    border-image: url(:/tree/branch-end.png) 0;
}`)
```

Even ```tree.SetStyleSheet(`background-image: url(:/tree/vline.png);`)```
shows nothing.

**Comment by therecipe** [comment]
Hey :)

The files will be looked up in the [resource system](http://doc.qt.io/qt-5/resources.html), because you used the `:/` prefix (the same happens if you use the `qrc:/` prefix)

So for this to work you need to let `qtrcc` bundle these files first.
You can do this by creating a custom *.qrc file in the root folder of your project. (if you don't want to use the qml folder and then use `:/qml/vline.png` ...)

```
.
├── custom.qrc
├── main.go
└── tree
    ├── branch-end.png
    ├── branch-more.png
    └── vline.png
```

`custom.qrc` (can be created by hand or with the help of the Qt Creator)

```xml
<RCC>
    <qresource prefix="/">
        <file>tree/vline.png</file>
        <file>tree/branch-end.png</file>
        <file>tree/branch-more.png</file>
    </qresource>
</RCC>
```


`main.go`
```go
package main

import (
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	tree := widgets.NewQTreeWidget(nil)
	tree.SetStyleSheet(`
  QTreeWidget::branch:has-siblings:!adjoins-item {
      border-image: url(:/tree/vline.png) 0;
  }

  QTreeWidget::branch:has-siblings:adjoins-item {
      border-image: url(:/tree/branch-more.png) 0;
  }

  QTreeWidget::branch:!has-children:!has-siblings:adjoins-item {
      border-image: url(:/tree/branch-end.png) 0;
  }`)
	tree.Show()

	widgets.QApplication_Exec()
}
```

**Comment by 5k3105** [comment]
worked perfectly. Thank you!
