### ISSUE TITLE
Kirigami

### ISSUE THREAD

**Issue by rkakrik** [therecipe/qt#267]
It is possible to use github.com/KDE/kirigami?

**Comment by therecipe** [comment]
Hey

Yes, it should be possible in theory, as you are just accessing the QML API and therefore don't need to port the C++ part.

However, I tried to get it working real quick but failed because I couldn't get cmake working and the qmake version seems to be broken? But I only tried it for macOS and android. I will try it again once I got more time.

**Comment by therecipe** [comment]
@rkakrik 
Got kirigami working (on macOS + android)
You can find it here: https://github.com/therecipe/qt/tree/master/internal/examples/qml/kirigami
Just run the `init.go` or manually install kirigami and then use the QML api like usual.

(If you are on windows or linux, then you might need to edit the `init.go` to point to your qmake)
