### ISSUE TITLE
slides with QML

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#274]
https://github.com/qt-labs/qml-presentation-system

Very useful. 

Its uses some shades too: https://github.com/qt-labs/qml-presentation-system/blob/master/examples/animatedbackground/Swirl.qml

It has a single c++ file. I think i can try to get it working myself based on how you did the cgo with flux. Will see :)

**Comment by therecipe** [comment]
Hey

I ported the "printslide" tool: https://github.com/therecipe/qt/commit/32211648707b02017511c77b932ee61dd1d39aff

It seems like the repo actually contained two things, one was the qml module to create presentations in general. And the other was just the "printslide" tool to convert these presentations into pdfs.

To get it working you need to modify the "src/src.go" again, to point to your qmake binary.
And then call "go generate" once. But because the "presentation" module was 100% QML, there is no need to create cgo stuff this time.

**Comment by gedw99** [comment]
ah sweet. thanks for putting this in. You beat me to it again :)
