### ISSUE TITLE
Compiled too slowly

### ISSUE THREAD

**Issue by gonboy** [therecipe/qt#275]
Question:
1. Compiled too slowly
2. Compiled spend too much RAM. (Qt5.8.0 Mingw only for 386, not X64)
    I test go\pkg\tool\windows_386\compile need max too 2G (if use widget)

Compiler slow, how to speed up compilation?

**Comment by bclermont** [comment]
Your bug report is just opinions.

Too slowly is objective. If your expectations are 2 seconds, then sure it's slow. 

This is cgo. Calling gcc from golang is always slower.

Plus large generated `.go` files. The  binding are huge, because qt is huge. 

`go install` that pre compile dependencies speed up compilation a lot. 

README file already specify that build binding need 8 Gb RAM. Then no surprise here. 

You should use docker image that cross compile for Windows for faster build.

**Comment by m8m5** [comment]
@bclermont FYI it now takes less than 2.5gb  free ram (last I checked compile.exe takes 2197mb for widgets).

**Comment by gonboy** [comment]
1. if import **Widget.** waste a lot of  memory . 
2. go\pkg\tool\windows_XXX\compiler waste a lot of  memory . 

later, I test qml, if use qml can reduce memory size, maybe I can use qml for GUI.
.

**Comment by therecipe** [comment]
@gonboy 

Hey, yes the initial setup and the compilation of applications that make use of this binding can be slow.

But you can speed-up the setup by exporting `QT_STUB=true` prior running the setup.
This will also reduce the needed amount of ram down to 200mb or something.
But this will also bring the limitation that you always have to use `qtminimal` and `go build -tags=minimal ...` or `qtdeploy`.

If you instead only want speed-up your compilation (and you don't use QT_STUB), then you can use the `-fast` flag like this: `qtdeploy -fast build desktop ...`

It might be possible to reduce the needed amount of ram during the setup even further in the future (it was at 8gb at some point), but it will probably always require at least 1.5gb.

@m8m5 

Thanks, a FAQ section in the readme is a great idea :)

**Comment by gonboy** [comment]
OK. thanks
