### ISSUE TITLE
Qt 5.6 support ?

### ISSUE THREAD

**Issue by LER0ever** [therecipe/qt#28]
Hi, great project ! But it seems only working under Qt 5.5.1. And this morning i tried for replacing all "5.5.1" with "5.6.0", I know it's a foolish move, i got a lot of path not found error.

**So any chance to support Qt5.6? or add an option to choose the qt version?**

**Comment by therecipe** [comment]
Hey, thank you :)

Replacing all "5.5.1" with "5.6.0" and also replacing all remaining "5.5" with "5.6" should have been enough.
But the `*.index` files provided by Qt are not perfect/correct and therefore need some minor fixes (missing overload-numbers, missing parent classes, ...)

I have already written most of that and will push the changes asap.
And I will probably add forward compatibility to the Qt 5.7.0-Beta, but not backward compatibility to Qt 5.5.1, because that would probably be to much work to maintain.

**Comment by LER0ever** [comment]
Thank you! I think the "file not found" does not affect the final result and it's working fine by now.

**Comment by therecipe** [comment]
Hey

The binding now uses Qt 5.6.0 (https://github.com/therecipe/qt/commit/7e98e7f8776df32e711832c38addb8eb5bfb3289)

Don't forget to update your **PATH** to `C:\Qt\Qt5.6.0\Tools\mingw492_32\bin`, if you use windows.
