### ISSUE TITLE
qtdeploy 5x slower (win7 go1.7.5), qtdeploy -fast not finding imports

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#281]
Hi tr!

For a small example program qtdeploy is now taking ~2min 20s. I didn't time it but I'm pretty sure the previous version I used it was ~1min.

I have another program that's split into 8 files (all package main) and qtdeploy is taking 5min (it used to be 1min). It seems to hang in qtdeploy.exe for a long time where it didn't before. Around minute 4 it sits in qtdeploy.exe for a solid minute (I thought it hung).

Also, ```-fast``` fails to detect imports. It will stop ~30s in and says something like:

```
# local/Submit
.\dblist.go:12: undefined: widgets.QTreeWidget
.\dblist.go:32: undefined: widgets.QTreeWidgetItem
.\dblist.go:72: undefined: widgets.QTreeWidget
.\dblist.go:72: undefined: gui.QFont
.\dbtree.go:44: undefined: widgets.QTreeWidget
.\dbtree.go:70: undefined: widgets.QTreeWidgetItem
.\dbtree.go:77: undefined: widgets.QTreeWidgetItem
.\dbtree.go:214: undefined: widgets.QTreeWidget
.\dbtree.go:274: undefined: widgets.QTreeWidgetItem
.\dbtree.go:274: undefined: widgets.QTreeWidget
.\dbtree.go:274: too many errors
```

I've tried this with 3 programs so far, and failed to detect imports. It failed once with the webkit example, worked once, then failed twice again. So it was strangely inconsistent :)

```
INFO[0000] running: 'qtsetup prep'
INFO[0000] running: 'qtsetup check windows' [docker=false]
INFO[0000] GOOS:                        'windows'
INFO[0000] GOARCH:                      'amd64'
INFO[0000] GOVERSION:                   'go1.7.5'
INFO[0000] GOROOT:                   *  'C:\Go\'
INFO[0000] GOPATH:                   *  'C:\goworksp'
INFO[0000] GOBIN:                    *  'C:\Go\bin'
INFO[0000] QT_HASH:                     '6d11509f782efa2ee6dc56a0a6f2153198c5ac43'
INFO[0000] QT_VERSION:                  '5.8.0'
INFO[0000] QT_VERSION_MAJOR:            '5.8'
INFO[0000] QT_DIR:                      'C:\Qt\Qt5.8.0'
INFO[0000] QT_STUB:                  *  'true'
INFO[0000] QT_DEBUG:                    'false'
INFO[0000] QT_QMAKE_DIR:                ''
INFO[0000] QT_WEBKIT:                *  'true'
INFO[0000] QT_MSYS2:                    'false'
```

**Comment by therecipe** [comment]
Hey :)

qtdeploy (also qtmoc and qtminimal) should be faster now with: https://github.com/therecipe/qt/commit/bc5bdbc293ee913353da7b043d88c21176d43f54

I forgot to filter out the std packages, as I initially planned when I started to make use of `go list`.

And for the missing imports, that could have been a bug in combination with the stub mode.

I hope it's fixed with: https://github.com/therecipe/qt/commit/91ffc25c1b390da86ccc3bc1c6fa28d72f49d874

**Comment by 5k3105** [comment]
Works now. Thank you!

- fast is ~10s faster than regular qtdeploy. I got ~1m 14s vs 1m 27s.

Thanks for all your hard work tr!

**Comment by therecipe** [comment]
You are welcome :)

And you might also be able to get qtdeploy even fast by not using the stub mode.
Currently the stub mode foces qtdeploy to always run "qtminimal" and that probably costs around 20sec in the end.

**Comment by 5k3105** [comment]
Ok, I'm not understanding.

I have set QT_STUB = true so that qtsetup runs fast. Maybe the new directions are not to use that env var at all since the note says "is set to true during the minimal setup".

First note: I am no longer getting a windows_minimal folder. When I run qtdeploy it just gives a deploy/windows folder with dll s and exe.

So I removed the env var and run qtdeploy -fast and all I get is a exe in deploy/windows which doesn't work. Also, the compile is like.. 6 seconds. (I wish!)

Now I try qtdeploy first, get the dlls and exe in the folder, remove the working exe and run qtdeploy -fast. I get an exe 6 seconds later but it doesn't run either.

**Comment by therecipe** [comment]
ah, sorry 

You need to set QT_STUB=false and then re-run the setup first, so  that the real packages can be installed. After this is done, you also need to run the normal `qtdeploy` at least once for you application (and also everytime you change your moc structs). Only then you can use `qtdeploy -fast`.

>I have set QT_STUB = true so that qtsetup runs fast. Maybe the new directions are not to use that env var at all since the note says "is set to true during the minimal setup".

Yeah, the stub mode is not really needed anymore because the normal setup should work with 2.5gb ram now. (but the stub mode is still used in some other form by the minimal setup.)

>First note: I am no longer getting a windows_minimal folder. When I run qtdeploy it just gives a deploy/windows folder with dll s and exe.

Yes, I dropped the "_minimal" suffix, because the "minimal" build in combination with `qtminimal` is now the default.

>So I removed the env var and run qtdeploy -fast and all I get is a exe in deploy/windows which doesn't work. Also, the compile is like.. 6 seconds. (I wish!)

I don't want to make false promises, but the normal use of `qtdeploy` (without moc structs in the code) takes like 30sec for me. With the `-fast` flag it actually only takes 6 sec :)

**Comment by 5k3105** [comment]
You have a fast computer ;)

~1min qtdeploy. 

30sec -fast!

Much better - thank you!

What happened to the good old days when it was 5min?? :)

**Comment by therecipe** [comment]
great :)

>What happened to the good old days when it was 5min?? :)

I hope those are gone for good :D
