### ISSUE TITLE
running in AndroidWear

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#289]
I got this going.

you can test using the standard android emulator.

https://bugreports.qt.io/browse/QTCREATORBUG-16765

Need to add an example to this repo :)

also the widget control for QML need to be based on https://asteroidos.org/

https://github.com/AsteroidOS/AsteroidOSSync

I dont use this for sync.
On the phone i run a Qt Service with a QUIC / HTTP/2 address and allow the watch and phone communicate this way. The reason i do this is so that the watch can also sync via a secure server.
It also less hassle than dealing with bluetooth and provides a single way to do sync for everything.
I need to submit a sample for running a Qt based android server and IOS service if i get time.
The server is written on golang using QUIC, as its much better than http and http2 for this type of two way sync.

i just wanted to write this so its known and follow up later with samples and also get opinions from others about this and help support this usage. 

Best sample i guess would be a simple sort of hello world, ping and something to sync a json document between devices.

**Comment by therecipe** [comment]
Hey

That's awesome :)
I honestly didn't even though about trying to get it working on a stock android smartwatch.
Did you needed to make changes beside the ones in the manifest?
I sadly have no time to test it myself today, but I definitely will do that tomorrow with the emulator.

And I just ordered a smartwatch so that I can also test it on a real device (and also with AsteroidOS) :)

>i just wanted to write this so its known and follow up later with samples and also get opinions from others about this and help support this usage.

ah, great :)

>Best sample i guess would be a simple sort of hello world, ping and something to sync a json document between devices.

Yes, that sounds good.
You probably could even let it sync between your pc and phone first, and then sync between your phone and watch later. Or even directly sync between your pc and watch.

I already thought about the possibilities of those applications that can run on your pc + phone + watch, when the support for AsteroidOS came in. And even though I was not able to come up with a really exiting idea so far, I still think there is probably some great potential in this.

On a side note, is there a term for applications that can run on your pc + phone + watch and then may also work together?

**Comment by joeblew99** [comment]
will get back to you when i have something.

I think the use cases are very much undiscovered yet, but then when they
are alot of people will be like how did i even live without it.
Or maybe it will be like - ah who cares.
I think the killer wil be when you talk to your watch for chat and
responding to messages quickly without having to get your mobiel out.
Maybe also for highly workflow driven environments like a factory floor,
warehouse packing etc, where you just need to co-ordinate people.
Sounds a bit like the old Robot Nation story - scary :)

https://www.marshallbrain.com/robotic-nation.htm

**Comment by therecipe** [comment]
>will get back to you when i have something.

Great, I tried to get it working today real quick but it didn't directly worked out :(
But that brought me to the other idea, that I probably should add the support for android x86 now, because the emulator is so damn slow.

>I think the killer wil be when you talk to your watch for chat and
responding to messages quickly without having to get your mobiel out.
Maybe also for highly workflow driven environments like a factory floor,

Yeah I think so as well, the app on the watch will probably always be just some kind of support/extension to the base app on your phone or pc (mainly due the small screen).
You probably have to accept that and then work more with the other kinds of input that are available, such as voice commands, NFC and gestures. There is probably a niche in business environments, like you said. But for the general population it's probably not that useful.

>https://www.marshallbrain.com/robotic-nation.htm

nice, I will read that tomorrow :)

**Comment by therecipe** [comment]
Okay, got it working :)
Seems like I took the wrong emulator when I tried it the first time.

I recycled an example and simply added the custom manifest to make it work: https://github.com/therecipe/qt/tree/master/internal/examples/canvas3d/quickitemtexture_wear

Now I also understand why you said:
>also the widget control for QML need to be based on https://asteroidos.org/

Yeah, it seems like there are no proper "official" qml controls for smartwatches so far.

I also added support for the android-emulator (x86 builds) to leverage HAXM.

**Comment by joeblew99** [comment]
Nice one :)

I will try the haxm VM for android x86. That will really help also with top down testing where the test system simulates user clicks or command actions.
Will be able to run it without waiting for ever.

About the lack of watch qml. I reckon the asteroid is a pretty good place to start. Maybe it's worth putting in a very basic eample using it in the internal examples so others can see it's there and doable.
Then i plan to copy the Google android material design spec to make it look like proper android wear. Google did a complete redesign with android wear 2.0.
Then i want to use the command actions / flux stuff to make it easy to write for desktop / mobile / watch with the same qml drawer-x base. You tend to have different compositions on a s reden for different devices but use the same components. So the command action / flux approach will make that decoupling work well i feel. 
The way a component lays out it's sub controls needs to vary between devices. I am not sure how to do that at only the qml level right now. Maybe you do.
The grid that constrains the components is the driver of it all and you want to have different grids per device type and then inject your components into it.
For example an email app on desktop versus mobile and watch.
On desktop you can show an email item in the right pane . On mobile you want to open the email item on a new page using stack push. On watch i am not sure but probably something different too :)

Wondering if you interested in me and others making a simple example to illustrate this ? It would really round out how to deal with this properly and show an approach everyone can us.

Thanks again for all of this btw. Qt golang has really shifted how i make apps

**Comment by therecipe** [comment]
:D great timing, I just got the watch today and tested some examples :)
But it seems like the watch ("LG G Watch") has no Wifi and only bluetooth. And it will also never get Android Wear 2.0, because it has no mechanical button :( 

But I will try to get the asteroid controls working in a basic example, like you suggested. And maybe also create another bluetooth example if I have time.

>The way a component lays out it's sub controls needs to vary between devices. I am not sure how to do that at only the qml level right now. Maybe you do.

You could make use of file selectors: http://doc.qt.io/qt-5/scalability.html#loading-files-depending-on-platform (the whole site is about the layout topic in general)

And the qml/webview example makes use of them on android with the `+android` folder: https://github.com/therecipe/qt/tree/master/internal/examples/qml/webview

And there is also something similar for images: http://doc.qt.io/qt-5/qquickimageprovider.html

>Wondering if you interested in me and others making a simple example to illustrate this ? It would really round out how to deal with this properly and show an approach everyone can us.

Sure, sounds great :)
The current examples are all really basic, so having something like that would be awesome.

>Thanks again for all of this btw. Qt golang has really shifted how i make apps

Thank you, I really appreciate it :)

**Comment by joeblew99** [comment]
thanks for the tips. big help..

i have not brought an android wear watch yet. But will check it has a mechanical button.

will close this since i highjacked the issue..
