### ISSUE TITLE
suggest：build each module to dll/so

### ISSUE THREAD

**Issue by sunwangme** [therecipe/qt#29]
dll/so will save time when build. now, too long...

**Comment by therecipe** [comment]
Hey

Did you run the setup.bat / setup.sh ?
It will install the packages (15 min - one time), so that you can build you application in less than 1 min.

I have a few concerns, regarding dynamic libs.

1) Currently the c/c++ part is around 30% and therefore you would still have to compile/install the 70% go code.
2) They will probably result in an even bigger total application size.
3) I would have to upload them every time I make a commit. (dll's / so's for windows/mac/linux/android)
4) I personally don't like to link agains an unknown pre build binary and assume other people feel the same way.

So, I currently don't see any benefits.

But there is a [proposal](https://github.com/golang/proposal/blob/master/design/2775-binary-only-packages.md) for go 1.7, which allows you to distribute binary go packages.
Then it should be possible to skip the 15 min one time install phase.

I will reconsider this issue, once go 1.7 is out.

**Comment by sunwangme** [comment]
ok
