### ISSUE TITLE
cross compiler windows xp support

### ISSUE THREAD

**Issue by kitech** [therecipe/qt#295]
I am using windows_32_dynamic docker image for cross compile on linux.

the .exe can not run my windows xp sp3.

the error message is missing  dwmapi.dll

and i found the deploy/windows/Qt5Widgets.dll linked dwmapi.dll

is the suppled Qt5Widgets.dll must linked dwmapi.dll?

**Comment by therecipe** [comment]
Hey

It seems like the last version to support XP was Qt 5.6 and `dwmapi.dll` is only present on Vista and newer. Taken from: https://forum.qt.io/topic/77135/dwmapi-dll-not-found/6

You probably need to build Qt 5.6 with mxe yourself, because the pre-built versions are probably gone by now. Or use the official pre-built Qt 5.6 version and compile on a windows machine yourself.

**Comment by kitech** [comment]
I see. thanks.
