### ISSUE TITLE
Can not location program entrance point __gxx_personality_v0

### ISSUE THREAD

**Issue by xland** [therecipe/qt#3]
I run this example:
therecipe\qt\internal\examples\widgets

And then run the exe file
therecipe\qt\internal\examples\widgets\deploy\windows\widgets.exe

Error Msg:
"Can not location program entrance point __gxx_personality_v0 ........... Qt5Core.dll"

Environment:
Windows 10 x64

**Comment by therecipe** [comment]
Okay, I looked into this.
This seems to happend, if you got a missing or wrong `libstdc++-6.dll`, maybe due a visual studio installation?

Does your folder contain the following dlls?

The important ones:
```
MD5(D3Dcompiler_47.dll)= 7ac9a645004744c4e3fb3953ac4ab34d
MD5(Qt5Core.dll)= 3b6d42bf7b71874037b7d6bc129971fd
MD5(Qt5Gui.dll)= e189ac2cc8fd526b458634ac5d601070
MD5(Qt5Svg.dll)= 715c730d4e180a14a64aad9d4e46006a
MD5(Qt5Widgets.dll)= 251e93666d4eb9d5e3efc6fd199980e1
MD5(libEGL.dll)= 94bdc5b44f54b2cce5a54cac181e6f3d
MD5(libGLESV2.dll)= f7aad84ba3923b09681b8337dfb308f7
MD5(libgcc_s_dw2-1.dll)= fadde43c97607e4445a6f924d851f04e
MD5(libstdc++-6.dll)= c283d446b34e75019b81d0981cb11f0d
MD5(libwinpthread-1.dll)= d128ae39a79e5d196fc001907b5ec3d1
MD5(opengl32sw.dll)= 33b541dd1131e0c784aba0a799ec91b5

MD5(platforms/qwindows.dll)= 3a170c78e442fca639ecdc7f9802c5b4
```

The other dlls that should be inside the sub folders, but that are not necessary to run the exe.
```
MD5(iconengines/qsvgicon.dll)= ab820a157d21da93618c27d68306ac7d

MD5(imageformats/qdds.dll)= c425fb146339526d1a462f45fdcd11fa
MD5(imageformats/qgif.dll)= 20d7a6cfb946b22a816d92ed57b51ce5
MD5(imageformats/qicns.dll)= fb197ac1d0f2f50f7b0e026bef2d8267
MD5(imageformats/qico.dll)= 26a7460345584d1a26866739577afd5a
MD5(imageformats/qjp2.dll)= 930cf0185e4c01c8a26f2b0b3db1ce29
MD5(imageformats/qjpeg.dll)= 24583405f8bcfc26884f221a2a9eb0c9
MD5(imageformats/qmng.dll)= 942e3d18ea0976778908add6d509bbb5
MD5(imageformats/qsvg.dll)= 59c816b1cbee57b2b75911a8c4857279
MD5(imageformats/qtga.dll)= 38719595d9268099680e96a4b8e1eefa
MD5(imageformats/qtiff.dll)= 30aafcd598ca04ef81af491e71a0bf8a
MD5(imageformats/qwbmp.dll)= 00064efbcc13bc363005764fec2836ad
MD5(imageformats/qwebp.dll)= 604f8f905d32955f285b15b17ac31abd
```

Alternatively you could install http://www.dependencywalker.com and check where the widgets.exe tries to get the dlls.

Also did you build the widgets example with the `setup.bat or setup/test.go` or with `qtdeploy.exe` or with `go build` (the last one shouldn't run, because it can't find the dlls) ?

(Additionaly, if you use the go x64 version, you need to clone the repo again, because I made some changes recently)

**Comment by xland** [comment]
It is fixed

**Comment by Inkeliz** [comment]
I have the same issue.
