### ISSUE TITLE
Databinding golang model with qml

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#301]
There seems to be many approaches.
Simple stuff like tree views, list views, forms

Many involve moc.

I was wondering if there are examples considered best practice clean ?
Am avoiding widgets.

Sorry about lame question but i see so many ways done for this using MOC and it gets complicated and unreliable in terms of workflows

**Comment by joeblew99** [comment]
Not getting any answers here :)

What I am trying to do is essentially use grpc with message queue running on client and server. The model that grpc and Nats message queue uses need to bind to Qt and bind back to the message queue.

This is really a kappa / cqrs style architecture that makes it very easy to handle apps with real time ( sort of) data flying between the server Uster and the Qt apps.

Maybe I can put up a github repo to show what I am trying to do and get some tips ??

**Comment by therecipe** [comment]
Hey

Sorry, was a bit busy. 

>I was wondering if there are examples considered best practice clean ?

Yeah, there are some examples, but probably non of them can considered best practice. Even through the two sailfish examples are somewhat clean.

https://github.com/therecipe/qt/tree/master/internal/examples/sailfish
https://github.com/therecipe/qt/tree/master/internal/examples/quick/listview
https://github.com/therecipe/qt/tree/master/internal/examples/quick/tableview

I probably should create some basic examples that show the usage of list, table and treeviews in qml, while the real model is kept in go.

>Maybe I can put up a github repo to show what I am trying to do and get some tips ??

Sure :)

**Comment by shalaby** [comment]
Can you please make these tutorials :)

**Comment by therecipe** [comment]
Hey

I actually wrote the examples already, they are just a bit buried: https://github.com/therecipe/qt/blob/master/internal/examples/common/qml_demo/itemViews.go

You will need to create a model in Go:
https://github.com/therecipe/qt/blob/master/internal/examples/common/qml_demo/itemViews.go#L10-L33

(In the example I used a wrapper to create a QML view + inject the model as `goListModel` in one go. 
You will probably need to explicitly set the `goListModel` through the `(*QmlEngine).RootContext().SetContextProperty()` function in your code and also load the Qml view through a QQuickView or QQmlApplicationEngine.)

here is the model used it in a QML listview:
https://github.com/therecipe/qt/blob/master/internal/examples/common/qml_demo/itemViews.go#L109-L118

or here in a QML tableview:
https://github.com/therecipe/qt/blob/master/internal/examples/common/qml_demo/itemViews.go#L205-L219

The model could also be any other class that is derived from QAbstractItemModel or even QAbstractItemModel itself. I just used the AbstractListModel because there you only need to implement `RowCount`, `Data` and `RoleNames`.

I will probably write a tutorial if I find the time. But it's really "just" the same stuff you would need to do if you use Qt through C++ or Python.

**Comment by shalaby** [comment]
@therecipe Thanks for taking the time to post this, I will dive into all this :)
