### ISSUE TITLE
Proper way to use go routines in Qt

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#305]
```QBasicTimer::start: QBasicTimer can only be used with threads started with QThread```

When I spin off go routines I get this error. I don't see a race condition but my program sometimes crashes anyway...

I do update to a text edit box within the go routine. Maybe it doesn't like that?

**Comment by 5k3105** [comment]
It allows me to write from one go routine to a textbox but I spin off a second routine from that which updates a treeview and that's when it breaks.

I will try to provide an example when I get time.

**Comment by therecipe** [comment]
Hey

>I do update to a text edit box within the go routine. Maybe it doesn't like that?

Yeah, you need to use either a slot or a signal function if you want to make visual changes from another thread or go routine. Otherwise it may crash.

>It allows me to write from one go routine to a textbox but I spin off a second routine from that which updates a treeview and that's when it breaks.

Yes, the function to set the text in the textbox is probably a slot ([this one maybe?](http://doc.qt.io/qt-5/qtextedit.html#setText)), therefore it works. The treeview function you use is probably neither a signal or slot and crashes therefore.

You probably just need to simply wrap the function you want to call from the go routine in a custom slot or signal will the help of qtmoc, [like it's done here](https://github.com/therecipe/qt/blob/master/internal/examples/widgets/systray/systray.go#L52-L60).

**Comment by 5k3105** [comment]
Thank you!
