### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by thesyncim** [therecipe/qt#31]

**Comment by therecipe** [comment]
Hey

I will look into this.

**Comment by therecipe** [comment]
Okay, I added iOS and iOS-Simulator support https://github.com/therecipe/qt/commit/54bd9aaf7690c92bb244ff86a82c278279169637

Just install [this](https://download.qt.io/official_releases/qt/5.6/5.6.0/qt-opensource-mac-x64-android-ios-5.6.0.dmg) qt version with iOS support and run `github.com/therecipe/qt/setup.sh ios` and `github.com/therecipe/qt/setup.sh ios-simulator`


But there are some limitations:

Currently only arm64 devices are supported (iPhone 5s and newer), because the created binaries are to big for armv7. (Maybe this will change with go 1.7)
Here is a great [comparison](http://dorianroy.com/blog/wp-content/uploads/2016/03/iOS_Support_Matrix_v4.1.pdf) about which device supports which arm version.

Another limitation is, that the qt library can only be statically linked by now.
Which means you probably have to provide the created `libgo.a` to your end user or buy the commercial version of qt. (Maybe this will change with qt 5.8  - [link](http://stackoverflow.com/questions/35068054/does-app-store-accept-qt-app-linked-with-qt-library-lgplv3))

And there could be the need to raise the minimum supported iOS version from 6.1 to 8.0, after the first two limitations are solved.

**Comment by therecipe** [comment]
If you use the current go tip or go 1.7 you will get fat binaries with armv7 and arm64 support.
https://github.com/therecipe/qt/commit/63cdd637683ede3337cb1495c974d696ff37bf2e
