### ISSUE TITLE
Extending examples

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#312]
These examples are awesome.
Big thank you !!

Nice clean tutorials to help people get the concepts.

Can we have the classic master / detail example ?
But don't use SQL, using boltdb. It's the golang dB default ( don't kill me ).

Master:
List view that is sortable on fields.
Choose a row and it opens the item view.

Item:
Lays out the form controls.

I know this is simple stuff but the other examples around are using widgets and old stuff. A pure qml based approach will mail it .

The pie chart examples are good too for sure.  If we use boltdb then the really useful thing will be to show a CLI updating the boktdb over port 80 and the Qt app updating based on the changes. That's huge because you eliminated lots of boiler plate code etc. It could be as simple as using a scope that polls the boltdb every second.

Great project !!!

**Comment by therecipe** [comment]
Hey :)

Do you mean [this](http://doc.qt.io/qt-5/qtsql-masterdetail-example.html) one?
I will try to port it to the widgets and then port it from there to qml.

I also haven't forgotten about the list/table/tree qml examples ;)
It will just take some time.

**Comment by joeblew99** [comment]
yes thats exactly it.  You got it.
I hope you also feel this is worth it. Its a very common need and i guess its a good way to see what needs to be refactored - an acid test as it were

**Comment by therecipe** [comment]
>I hope you also feel this is worth it. Its a very common need and i guess its a good way to see what needs to be refactored - an acid test as it were

Yeah, it always good to have some examples that are more "real world" ones :)

I ported the examples as it was for now with: https://github.com/therecipe/qt/commit/d0995a0002fadf7a6dc29ea85bffe3b0224757b6 and it can be found [here]( https://github.com/therecipe/qt/tree/master/internal/examples/sql/masterdetail).

I also started to work on a boltdb version, but it will take a while since I haven't worked with the Qt models in a while and boltdb is also completely new to me :D

After that version is done, I hope that I can simply reuse the model to use it in the qml version also.

**Comment by joeblew99** [comment]
Boltdb is allot more work than sqlite, but has the advantage of running on anything.

There are a few wrappers:
https://github.com/timshannon/bolthold

there is also another one called storm. its a fair bit older and has lots of users
https://godoc.org/github.com/asdine/storm?importers

--

Also you can get lucern like indexing and searching by using bleve, which can use boltdb
https://github.com/blevesearch/bleve
i have used this and it works well. It can also scale horizontally using alias's

You can also scale out with boltdb because there are raft and serf based implementations.

**Comment by therecipe** [comment]
Yeah, getting boltdb running wasn't so much work after all, but thanks anyway :)
I first tried to create buckets for everything (to mimic the db map structure I used as well) but then I figured I should just serialize everything to json and just use boldtb as a KV database.

But you will see what I mean ...

I rebuilt the masterdetail example here: https://github.com/therecipe/qt/tree/master/internal/examples/sql/masterdetail_qml

And you can swap out the "database" and "view" parts by using the `boltdb` and/or `qml` build tags.

The usual database (if you don't use the `boltdb` tag) is just a map [here](https://github.com/therecipe/qt/blob/master/internal/examples/sql/masterdetail_qml/database.go#L20-L54) and I used these functions [here](https://github.com/therecipe/qt/blob/master/internal/examples/sql/masterdetail_qml/database_nodb.go) to access it.

If you use the `boltdb` tag however, [these](https://github.com/therecipe/qt/blob/master/internal/examples/sql/masterdetail_qml/database_boltdb.go) functions will be used to access the boltdb database.

After that was working, I ported the "view" part to qml, which can be used by using the `qml` build tag.
The qml version has a separate "main" function and starts [here](https://github.com/therecipe/qt/blob/master/internal/examples/sql/masterdetail_qml/main_qml.go).

I tried to use the new Quick controls first, but these are lacking a TableView and I didn't want to build my own TableView out of a ListView or something. And so I used the old ones instead, which mimic the  widgets style on the desktop, but they might look bad on the mobile platforms.

However, the qml version still requires plenty of Go code, which can be found [here](https://github.com/therecipe/qt/blob/master/internal/examples/sql/masterdetail_qml/controller_qml.go) and most of this is just duplicate code taken from the widget version [here](https://github.com/therecipe/qt/blob/master/internal/examples/sql/masterdetail_qml/mainWindow.go).
I later figured that I might should have separated the widget view and controller code as well, so that I could have used the controller code for qml and the widget version. (I might do that someday, but for now it's okay.)

Another thing is that the qml "AlbumDetails" part on the right (in the `qml` version), might look a bit off sometimes due the GridLayout, but that's just a design issue. So I'm leaving that for now as it is as well ...

Beside that, I'm hoping you can make some sense out of this example, as it shows the use of List and TableViews with the help of the List and TableModel for both the old widgets and also in qml.

**Comment by joeblew99** [comment]
thanks !

Am looking into it now...

**Comment by joeblew99** [comment]
@therecipe 

There are some issues with the build tags.
As you can see from the Venn mix, it seems the QML tag does not work.
it builds on OSX, the app opens in the dock, but there is no window.

# normal build - WORKS
#qtdeploy 
#qtdeploy -fast

# GUI: qml, Database: nil - DOES NOT WORK 
qtdeploy -tags="qml"

# GUI: widget, Database: boltdb - WORKS
#qtdeploy -tags="boltdb" 

# GUI: qml, Database: boltdb - DOES NOT WORK
#qtdeploy -tags="qml boltdb"

**Comment by joeblew99** [comment]
the qml bolt tag works now for me too  - thanks.

I will try out altering the qml and db code to build up some Material Design style components.

I was thinking of making each component use different folders. Each folder would have:
- qml
- go code
- qrc

Anyone building an app can then use the Drawerx, and then these components.

BUT i am not sure QT will support this style of laying out the file system. If you can comment with your thoughts it would help. I can setup a public repo for this to help collab

**Comment by joeblew99** [comment]
I went over an checked out how lirios is going.
they are using QBS (Qt build system) to help break up their system into reusable components.
https://github.com/lirios/fluid/blob/develop/fluid.qbs

Can we use this ?
Should we ? :)

**Comment by therecipe** [comment]
>BUT i am not sure QT will support this style of laying out the file system. If you can comment with your thoughts it would help. I can setup a public repo for this to help collab

Yeah setup one if you like, I also threw some examples together here:
https://github.com/therecipe/qt/tree/f5eecc27111cea17e0e9ed2a645ad0ac3c96a9fb/internal/examples/qml/extending/components

As I was curious to see if this would work :)

And it does, even through there are some changed needed to qtrcc to nicely integrate this.

The first example `test_go` works without any changes needed, as the component is just Go code.
But there is the need for the helper class `PieChartFactory` (like in the `qml/extending` examples in general), but that's an in-depended issue.

The second example `test_qml` needs some changes, but the `make.sh` should build it on macOS, if you got `QT_DIR` set.
This example shows that you can create qml only components, that you can import through a Go import.

The last example `test_qml_go` is probably what you meant, as it combines qml and go to an independent component. The most common way is probably to have a core Go component and then build upon those with Qml code, like I did in that example. But there are probably other ways as well. And I will look into them after I'm done with the qtrcc changes.

>Anyone building an app can then use the Drawerx, and then these components.

Yeah, beeing able to re-use small and independent components would be really awesome.

>Can we use this ?
Should we ? :)

Do you mean QBS or fluid?
About QBS, I would rather not couple it with qtdeploy or something. I think if people want to use it, then they can already do so. But bringing in a build system will make things only more complicated for the average user.

About fluid, yeah it looks interesting. And it seems like there has been a lot work been done since I looked into it. The question is just how to get it to work with Go. One way would be to port the c++ part to Go, but this will probably be tedious and one would not be able to make use of the changes made upstream. The other would be to create glue code, to get it working. But then you would only have access to the Qml types (and I don't know if this is sufficient).

**Comment by joeblew99** [comment]
sorry yes i meant QBS, and after looking at it i tend to agree. QtDeploy gives control to do anything and the extending components example looks like a great test of it.

Fluid seems to be rolling forward :) 
I favour golang, rather than glue code. I had a look into the code a few months ago and realised that most of the c++ code is there because they are making an OS itself and so need a fair bit more c++ code. In other words YAGNI (you aint gonna need it).  Have another another look and see if i am off the mark or not.
Also its going to be way easier to maintain our own golang code since we are all gophers. 

For example: 

https://github.com/lirios/fluid/tree/develop/src/fluid
- dateutils.cpp. golang has awesome libs to do this anyway as wall as current i18N etc etc. 


https://github.com/lirios/fluid/tree/develop/src/demo
- no c++here :)
i quite like the folder layout best practice.  
I dont think they have a command action, reflux best practice architecture yet in their, but thats really something else outside this for now.


https://github.com/lirios/fluid/tree/develop/src/imports/core

- qqmlsortfilterproxymodel.cpp. We can do this in golang and should because with boltdb etc you want a different type of activation model anyway.

- clipboard.cpp. They need this because they are making an OS. We use QT that taps into the desktop and mobile clipboard code (i assume :) )



https://github.com/lirios/fluid/tree/develop/src/imports/effects

- effectsplugin.cpp. just has a few lines of code anyway


https://github.com/lirios/fluid/tree/develop/src/imports/layouts

- layoutsplugin.cpp. Again just a single line of code

**Comment by therecipe** [comment]
>I favour golang, rather than glue code approach. The reason is because I had a look into the code a few months ago and realised that most of the c++ code is there because they are making an OS itself and so need a fair bit more c++ code.

Yeah, I looked into it and tried to port some parts, but then realized that they make use of a few features that are probably not that easy to port at all. Such as this one: http://doc.qt.io/qt-5/qtqml-modules-cppplugins.html And that there would be the need to re-structure some parts to get it working with Go.

But then I figured that it would be way easier to just "make install" fluid and then work with the QML api. This way you can simply make use of the changes made upstream without the need to catch-up later on.

I also changed qtrcc to support the`qml/extending` examples, so that they work with qtdeploy: https://github.com/therecipe/qt/commit/4db4e9c202f63223417541131178758075303089

And I got https://github.com/KDE/kirigami working in the same way fluid works now as well.

Just run the init.go files and fluid or kirigami will be installed for darwin and android:

https://github.com/therecipe/qt/tree/master/internal/examples/qml/fluid
https://github.com/therecipe/qt/tree/master/internal/examples/qml/kirigami

**Comment by joeblew99** [comment]
sorry about delay. work stuff.

All good stuff thanks.
Will play with Fluid and try my luck :)

I think i should close this..
