### ISSUE TITLE
Swift and qt

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#314]
Can I use swift code with Qt ?

This for example:
https://github.com/maximbilan/iOS-Shared-CoreData-Storage-for-App-Groups/blob/master/README.md

**Comment by joeblew99** [comment]
It solves a big problem for Qt apps on mobile imho

**Comment by joeblew99** [comment]
This is using gomobile, but it shows its doable.

https://forum.golangbridge.org/t/experimental-swift-bindings-for-go-mobile/1053

I Gitta admit that as a golang programmer doing tricky stuff using swift instead of objective c is easier to read

**Comment by therecipe** [comment]
>This is using gomobile, but it shows its doable.
>https://forum.golangbridge.org/t/experimental-swift-bindings-for-go-mobile/1053

Yeah, I haven't looked into that, but I suspect that this is working because gomobile generates C glue code and therefore you can easily use the Go functions in Swift, because you are accessing them through C.

If you however want to access Swift/Obj-C from Go, then you need to wrap that code in C first.
Here is a small example how it works for Obj-C++: https://github.com/therecipe/qt/issues/22#issuecomment-212434537

Calling plain Obj-C is probably simpler and it might work with "go build", but I have no example for that. But I recall that I already did that at least once.

So calling Go from Swift, is probably "easy" because you can call it like this:
`Swift/Obj-C -> C -> Go`

However, calling Swift from Go is more complicated, because you need to call:
`Go -> C -> Obj-C -> Swift`, and you probably need a lot of glue code too.

But it should be possible ...

**Comment by joeblew99** [comment]
ok thanks. Your knowldge in this area is totally amazing !
i now knwo what i am up against and will work through it and see how far i get.

I will close this, because this answers it and i will go and try to do this inside QT and let you know.

**Comment by smasher164** [comment]
Sorry to revive this, but if you would like an example of calling swift code from Go, I create one here:
https://github.com/smasher164/swift-cgo-example

Basically you have to use a bridging header to communicate to Obj-C, and a header to connect Obj-c to Go. It can be even be automated through the xcode command line tools!

**Comment by therecipe** [comment]
@smasher164 no problem, thanks for the example :)
