### ISSUE TITLE
webview fails to show window on OSX

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#317]
This was working about  two weeks ago.
Now has not worked for the last week i think.

What i am seeing:
The dock opens, but no window shows up. 

Maybe i am doing something wrong ?

````

x-MacBook-Pro:webview apple$ qtdeploy build desktop
# builds without complaining

x-MacBook-Pro:webview apple$ qtdeploy run desktop
# opens immediately the dock, but no window shows up.


````

**Comment by therecipe** [comment]
You problem just forgot that you need to start/build it outside of the `*.app`, because of the bug in `macdeployqt`: https://github.com/therecipe/qt/issues/227#issuecomment-284768974

**Comment by joeblew99** [comment]
works thanks !!

**Comment by joeblew99** [comment]
@therecipe 
I copied the webview example out of internal, as i wanted to add some catching and logging of errors back using Stackdriver.
For some reason the images referenced in the qrc are no longer showing in the app.
Mhh.. any ideas ?

Also can i call it main.qrc ? I dont see in the main.go or the main.qml any reference to the .qrc file, so it seems its some sort of convention logic for the system to know what .qrc file to use ?

**Comment by therecipe** [comment]
Yeah, you can rename it to whatever you want, as long as it's not `rcc.qrc`.
Because `rcc.qrc` will be overridden by qtrcc to bundle the content of the `qml` subfolder.

The reason why the *.qrc files are not references in the code is, that they are only needed to create the two imported `rcc_cgo_*.go` and `rcc.cpp` files by `qtrcc`. And simply compiling those is enough to bundle the resources and to make them available to `qrc:///`.

If you look here: https://github.com/therecipe/qt/tree/master/internal/examples/qml/webview
You will see that the original example makes use of a custom `qml.qrc` to bundle the resources.
And if you run `qtrcc` in that folder you will end up with `rcc.qrc` and `qml.qrc` and both will be used later and be combined into `rcc.cpp`. (Even through rcc.qrc will be empty, because the qml folder itself is empty)

>For some reason the images referenced in the qrc are no longer showing in the app.

You probably removed the reference to these images in one of the `*.qrc` files, or forgot to compile the `rcc.cpp` file.
Or just run `qtrcc` in your project folder an then open the `rcc.cpp` and seach for your image names.
If you don't find them there, then you need to edit your `*.qrc` files.

**Comment by joeblew99** [comment]
fixed it. thanks !!
