### ISSUE TITLE
Event filters are not working

### ISSUE THREAD

**Issue by testhmaa** [therecipe/qt#34]
Event filters are not working (i am testing on linux x64), when i try it on a QPlainTextEdit control.  I have tried different ways, but still not able to figure out how to get this done. I am new to GO, QT and ofcourse the bindings, so can't figure it out myself ( Too many new things i know at this time ). 

when i use InstallEventFilter method, i get this as compile error.
**widgets.QPlainTextEdit does not implement core.QObject_ITF (missing QObject_PTR method)**

Also, i tried using various Connect methods for events such as **ConnectEventFilter, ConnectKeyPressEvent, ConnectEvent** but in all the case i was not able to catch any events. Also, no compile time/runtime error occurs.

btw, extremely good work, this seems to be a holy grail, because using the binding is easy rather than clumsy C.This might easily take the place of https://github.com/google/gxui, if more documentation, examples are provided.

**Comment by therecipe** [comment]
Hey

Here is some code that should work.
It intercepts the events that are send to the `textEdit`, so you can inspect them with the `filterObject`.
And here are some general infos about [event filters](http://doc.qt.io/qt-5/eventsandfilters.html#event-filters).

Also you need to you run the `[YOUR_PROJECT]/deploy/linux/[YOUR_PROJECT].sh` file after you ran `qtdeploy build/test desktop YOUR_PROJECT`, otherwise you won't see anything in the terminal/shell.

Maybe you should also take a look at these [examples](https://github.com/therecipe/qt/tree/master/internal/examples) and the [qt docs](http://doc.qt.io).

Feel free to ask, if you run into any problems :)

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var filterObject = core.NewQObject(nil)
	filterObject.ConnectEventFilter(func(watched *core.QObject, event *core.QEvent) bool {

		if event.Type() == core.QEvent__KeyPress {
			var keyEvent = gui.NewQKeyEventFromPointer(event.Pointer()) //like static_cast
			//var textEdit = widgets.NewQPlainTextEditFromPointer(watched.Pointer())

			if keyEvent.Key() == int(core.Qt__Key_Tab) {
				println("filterObject:", "special tab handling")
				return true
			}

			println("filterObject:", keyEvent.Text())
			return false
		}

		return false
	})

	var textEdit = widgets.NewQPlainTextEdit(nil)
	textEdit.InstallEventFilter(filterObject)
	textEdit.ConnectKeyPressEvent(func(event *gui.QKeyEvent) {
		println("textEdit:", event.Text())

		//do something here

		textEdit.KeyPressEventDefault(event) //call default implementation (always suffixed with *Default)
	})

	textEdit.Show()

	widgets.QApplication_Exec()
}
```

**Comment by testhmaa** [comment]
Yes, the eventfilter code above has been tested to work fine. thanks for the help and documentation
