### ISSUE TITLE
Error during the execution of setup.bat

### ISSUE THREAD

**Issue by dtrehas** [therecipe/qt#35]
During the execution of setup.bat with administrator account I come across to this message

![setup](https://cloud.githubusercontent.com/assets/10588073/15485128/d04ac9fc-213d-11e6-8fe4-86d70f035a0c.png)

During the generate-phase says that "can't load package: .../therecipe/qt/core
nobuildable Go Source files in c:\prog\gopath\src\github.com\the recipe\qt\core.

2. Before TheRecipe you changed the source code to use the GOROOT env variable (thanks for that) i was managed to build the code but, it couldnt see to be able to link the core.a library.

I do not know if there is any implication by using the administrator account during the creation of .a files, a file takes elevated privileges.

Thank you in advance.

P.S. A GO/QT executable, using 2 only widgets weighs a lot in MB?

**Comment by therecipe** [comment]
Hey

I tried to rebuild your environment, because I suspected some problems with `PROG` and `Prog`, but it did work.
```
C:\>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\PROG\GOPATH
set GORACE=
set GOROOT=C:\Prog\Go
set GOTOOLDIR=C:\Prog\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

So, this is what I would do:

1. Remove the `qt` folder
2. `go get github.com/therecipe/qt`
3. Open the cmd (right-click as admin, **but don't login to the admin account**)
4. `cd %GOPATH%\src\github.com\therecipe\qt && setup.bat`

I'm not sure but maybe some files/folders got the wrong privilege, due the use of the admin account?

And yes, unfortunately a simple application (with the core, gui and widgets modules) is around 100 mb (40 mb for qt dlls and 60 mb for the go application), hopefully the size will be heavily reduced with go 1.7
