### ISSUE TITLE
qtdeploy -docker build windows

### ISSUE THREAD

**Issue by dzhou121** [therecipe/qt#365]
Hi,

I'm trying to docker build for windows but it failed with a very long error message, but the error message doesn't give me which exactly make it fail. I'm building on macOS and it works for both macOS and docker linux.

**Comment by therecipe** [comment]
Hey

I will do some tests, but could you maybe look for `fatal` or `error` in the output and upload those parts?

**Comment by dzhou121** [comment]
This is the only thing about ```fatal``` or ```error```
```time="2017-06-19T04:05:36Z" level=error msg="failed to run command" cmd="go build -p 2 -v -ldflags="-s" "-w" "-H=windowsgui" -o /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/cmd/gonvim/deploy/windows/gonvim.exe -tags="windows" "minimal" -pkgdir /home/user/work/pkg/windows_windows_386" env="GOARCH=386 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin CC=/usr/lib/mxe/usr/bin/i686-w64-mingw32.shared-gcc CXX=/usr/lib/mxe/usr/bin/i686-w64-mingw32.shared-g++ GOOS=windows CGO_ENABLED=1 GOPATH=/home/user/work:/media/sf_GOPATH0 GOROOT=/usr/local/go" error="exit status 2" func=RunCmd name="build for windows on linux" ```

I'm using QSvgQwidget

**Comment by therecipe** [comment]
Okay, I looked into it and it seems like the current master is a bit broken.
So I worked around it by commenting out the line containing `fzf.UpdateMax`.

Then to build it for windows there was also the need to go get `github.com/mattn/go-shellwords`

But then the docker build broke because of:
```
# github.com/neovim/go-client/msgpack
../../../../neovim/go-client/msgpack/pack.go:177: constant 4294967295 overflows int
../../../../neovim/go-client/msgpack/pack.go:243: constant 4294967295 overflows int
../../../../neovim/go-client/msgpack/pack.go:272: constant 4294967295 overflows int
```

It works however if you pull the 64bit windows image and run it like this:
```
docker pull therecipe/qt:windows_64_shared
export QT_MXE_ARCH=amd64
qtdeploy -docker build windows
```

I will look into the `constant 4294967295 overflows int` issue, it could be that I just need to use the 32bit version of Go for the windows images.

**Comment by dzhou121** [comment]
Thanks. I'll raise an issue in github.com/neovim/go-client
