### ISSUE TITLE
Generated ListModel havent `get` method

### ISSUE THREAD

**Issue by averrin** [therecipe/qt#385]
If i use https://github.com/therecipe/qt/blob/master/internal/examples/quick/listview/personmodel.go as reference ListModel havent `get` method and if i use it in ComboBox i cant get current selevted item in other components.
How i can add this method?

**Comment by therecipe** [comment]
Hey

Yeah, if you use a C++/Go model instead of a real QML model like this one: http://doc.qt.io/qt-5/qml-qtqml-models-listmodel.html

Then you also need to use the C++/Go api to access the model: http://doc.qt.io/qt-5/qabstractlistmodel-members.html

So you probably need to rebuild your own "get" function with: http://doc.qt.io/qt-5/qabstractitemmodel.html#data and http://doc.qt.io/qt-5/qabstractitemmodel.html#index

Like shown this:

```qml
import QtQuick 2.0

import QtQuick.Controls 1.4 as Old
import QtQuick.Controls 2.1 as New

Rectangle {
  Old.ComboBox {
    id: oldComboBox

    anchors {
      top: parent.top
      left: parent.left
      right: parent.right
    }

    model: PersonModel

    textRole: "firstName" //or "display", if you didn't overwrote the roleNames in Go
    onActivated: console.log("Combo Box Index Changed To:", index, model.data(model.index(index, 0), Qt.UserRole + 1))
  }

  New.ComboBox {
    id: newComboBox

    anchors {
      top: oldComboBox.bottom
      left: parent.left
      right: parent.right
    }

    model: PersonModel

    textRole: "firstName" //or "display", if you didn't override the roleNames in Go
    onActivated: console.log("Combo Box Index Changed To:", index, model.data(model.index(index, 0), Qt.UserRole + 1)) //"Qt.UserRole + 1" can be omitted if you didn't override the roleNames in Go
  }

  New.Button {
    anchors {
      left: parent.left
      right: parent.right
      bottom: parent.bottom
    }

    text: "click me"

    onClicked: {
      console.log("OldComboBox current: ", oldComboBox.model.data(oldComboBox.model.index(oldComboBox.currentIndex, 0), Qt.UserRole + 1)) //"Qt.UserRole + 1" can be omitted if you didn't override the roleNames in Go
      console.log("NewComboBox current: ", newComboBox.model.data(newComboBox.model.index(newComboBox.currentIndex, 0), Qt.UserRole + 1)) //"Qt.UserRole + 1" can be omitted if you didn't override the roleNames in Go
    }
  }
}
```

If don't use custom role names, then you can simply remove all "Qt.UserRole + 1" and replace "firstName" with "display".

**Comment by averrin** [comment]
You are awesome. You know it? =) All your answers are correct. I used Qt some years ago and i surprised with this changes=)

**Comment by therecipe** [comment]
Thank you :)
And yeah, I had exactly the same issues with QML in the beginning.
