### ISSUE TITLE
Common examples

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#393]
Can I enquire about the common examples.

It looks like a different approach with the qml markup embedded in the golang. This seems really smart for many reasons with the main one being golang vendoring / sharing between projects which is huge I feel.

What's the real difference between the qml and widgets ? There is presumably a reason they exist.

I guess also this all makes it easier to build GUI where a single s teen needs to change dynamically, rather then toggling elements in a traditional qml file ?

Very curious. Please tell more...

**Comment by therecipe** [comment]
Hey

Yeah, actually I just wanted to have it easily comparable to the "widgets" example.

And this particular approach to embed QML inside Go is a bit hacky, take a look here for example: https://github.com/therecipe/qt/blob/master/internal/examples/common/qml_demo/main.go#L74-L76
(Also creating many QQuickWidgets is probably not really effective at all.)

But yeah, if you have a small QML component that you want to embed into your regular widget application, then you can use the QQuickWidgets approach.

If you are however only interested in creating QML components dynamically, then you probably should take a look here: http://doc.qt.io/qt-5/qqmlengine.html#setNetworkAccessManagerFactory
(You will need to create your own NetworkAccessManager and NetworkReply(s), so that you can create/load QML components dynamically over the network or from memory)

And another approach would be this: https://github.com/therecipe/qt/tree/master/internal/examples/quick/dynamic
