### ISSUE TITLE
ConnectCurrentItemChanged

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#40]
Hi,

Using QListWidget:

```go
func (ptr *QListWidget) ConnectCurrentItemChanged(f func(current *QListWidgetItem, previous *QListWidgetItem))
```
```go
func (ptr *QListWidget) CurrentItemChanged(current QListWidgetItem_ITF, previous QListWidgetItem_ITF)
```

I get error:

	λ qtdeploy

	build_1
	output:# local/AM/controlbox/graphpanel
	controlbox\graphpanel\graphpanel.go:102: cannot use gp.NodeList.CurrentItemChanged (type func(widgets.QListWidgetItem_ITF, widgets.QListWidgetItem_ITF)) as type func(*widgets.QListWidgetItem, *widgets.QListWidgetItem) in argument to gp.NodeList.ConnectCurrentItemChanged

	error:exit status 2

I've used both:

    type Nodelist struct{ *widgets.QListWidget }

	func (n *Nodelist) CurrentItemChanged(current widgets.QListWidgetItem_ITF, previous widgets.QListWidgetItem_ITF) {

	}

	func (n *Nodelist) CurrentItemChanged(current *widgets.QListWidgetItem, previous *widgets.QListWidgetItem) {

	}

**Comment by therecipe** [comment]
Hey

You overshadow / override the `CurrentItemChanged` function and therefore change the input parameters.

It is confusing, because the normal functions take *_ITF (interfaces) parameters and the Connect* functions want *pointers.
I made this so you don't always have to deduce the *_ITF to *pointers with *_PTR(), if you write a Connect-function.

This should work:
```go

package main

import "github.com/therecipe/qt/widgets"

func main() {

	var nodeList = NewNodelist(nil)

	nodeList.ConnectCurrentItemChanged(nodeList.CurrentItemChanged)

	nodeList.CurrentItemChanged(nil, nil)             //overshadows and wants *widgets.QListWidgetItem and *widgets.QListWidgetItem
	nodeList.QListWidget.CurrentItemChanged(nil, nil) //overshadowed and wants widgets.QListWidgetItem_ITF and widgets.QListWidgetItem_ITF
}

type Nodelist struct{ *widgets.QListWidget }

//overshadows QListWidget.CurrentItemChanged function which wants (widgets.QListWidgetItem_ITF and widgets.QListWidgetItem_ITF)
func (n *Nodelist) CurrentItemChanged(current *widgets.QListWidgetItem, previous *widgets.QListWidgetItem) {

}
```

**Comment by 5k3105** [comment]
My fault. I declared the Nodelist wrong. What you said kind of went over my head but got me curios. 

How/why would you directly call an event function:

    nodeList.CurrentItemChanged(nil, nil) 

How/why would you change input parameters?

**Comment by 5k3105** [comment]
So my problem is, if I have a form with multiple widgets and each widget has a method I need to get to a sibling widget (a widget on the same form). So I need access to the parent struct to get to the children. Can I pass in the parent using this?

**Comment by 5k3105** [comment]
Sorry. Solved it like this:

```go
    package form

    var form *Form

    type Form struct {
        *widgets.QWidget
        Listbox ListBox
        Textbox TextBox
    }

    type ListBox struct {
        list []string
    }

    type TextBox struct {
        text string
    }

    func (l *ListBox) CurrentItemChanged(current *widgets.QListWidgetItem, previous *widgets.QListWidgetItem) {
        form.JobID.SetText(current.Text())
    }

    func NewForm() *Form {

        form = Form{QWidget: NewQWidget(nil), Listbox: ListBox{}, Textbox: TextBox{}}

        // event loop
    }
```

**Comment by therecipe** [comment]
Hey

Referring to https://github.com/therecipe/qt/issues/40#issuecomment-225689128

You probably don't need to call an event function directly. (Only for testing purposes)

But since you can do this in go:

```go
package main

type A struct{}
type B struct{ A }

func (a *A) someFunction(s string) {
	println("hello from A")
}

func (b *B) someFunction(i int) {
	println("hello from B")
}

func main() {
	var a = A{}
	var b = B{A{}}

	a.someFunction("")
	b.A.someFunction("")

	b.someFunction(0)
}
```

You could redeclare the functions and also the input parameters:
```go
//overshadows QListWidget.CurrentItemChanged function which wants (widgets.QListWidgetItem_ITF and widgets.QListWidgetItem_ITF)
func (n *Nodelist) CurrentItemChanged(current *widgets.QListWidgetItem, previous *widgets.QListWidgetItem) {

}
```

But only because `CurrentItemChanged` is a [signal](http://doc.qt.io/qt-5/qlistwidget.html#currentItemChanged) and therefore not created in the `moc.go`.

But it won't work with all other functions such as slots or plain normal functions and you will get the `redeclared` issue.

That's why it's probably better to suffix you own implementations for the `Connect` functions with something like `_Implementation` (just so you can identify them easily and also won't run into the redeclared issue)

**Comment by 5k3105** [comment]
Got it. Thanks for your help.
