### ISSUE TITLE
Miss file or cannot open file

### ISSUE THREAD

**Issue by wzwmzm** [therecipe/qt#402]
When I run the example **github.com/therecipe/qt/internal/examples/qt3d/audio-visualizer-qml/** . 

First ,i do **qtdeploy test desktop ...**, OK! 

Then run **wzw@home:~/audio-visualizer-qml/deploy/linux$ ./audio-visualizer-qml.sh**

**qrc:/main.qml:38:1: plugin cannot be loaded for module "QtQuick.Scene3D": Cannot load library /home/wzw/share/github.com/therecipe/qt3d/audio-visualizer-qml/deploy/linux/qml/QtQuick/Scene3D/libqtquickscene3dplugin.so: (libQt53DRender.so.5: 无法打开共享对象文件: 没有那个文件或目录)(CHINESE: cannot open the file : no the file or direction )**

I run qtdeploy command in docker.
Sorry, my English is very poor!

**Comment by therecipe** [comment]
Hey

No problem, it's not that bad :)

The issue should be fixed with: https://github.com/therecipe/qt/commit/794d660e4775975de7d6f9472589a3b8d05f5712
There were just some dependencies missing in `deploy/linux/lib`.

But it takes a while until the new docker image is ready: https://hub.docker.com/r/therecipe/qt/builds/bwjwqfxe9vybzld6wpnqvnd/

**Comment by wzwmzm** [comment]
THANK  U  VERY  MUCH !
