### ISSUE TITLE
Error during qtdeploy on MacOS

### ISSUE THREAD

**Issue by Aelphy** [therecipe/qt#405]
Hi. I have just received the following problem during running qtdeploy -debug build:
QT. version is 5.9.

ERRO[0122] failed to run command                         cmd="strip mybinary" env= error="exit status 1" func=RunCmd name="strip binary for darwin on darwin"
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: symbols referenced by relocation entries that can't be stripped in: mybinary(_all.o)

**Comment by therecipe** [comment]
Hey

Sorry, I'm a bit busy atm.
Also thanks for the PR :)

I looked into this, and the problem can be probably also solved by using `strip -u -r`.
This is the solution I would prefer, because it's one of the two default modes.
(And it also seems to get rid of even more symbols then `-x`)

So could you try to run `strip -u -r` on a unstriped binary as well, and the maybe compare the resulting binary size to `strip -x` ?

**Comment by Aelphy** [comment]
strip -ur produces the binary of size 2.7M
strip -x gives me 2.6M

**Comment by therecipe** [comment]
Mh, okay.
I will merge your PR.
