### ISSUE TITLE
run qtsetup in win7 32bit,  gui widgets failed

### ISSUE THREAD

**Issue by zhuwei** [therecipe/qt#423]
run qtsetup:
installing full qt/gui  failed to run command
installing full qt/widgets  failed to run command
please help me.

**Comment by zhuwei** [comment]
and qt/quick

**Comment by zhuwei** [comment]
and gui widgets sql svg multimedia quick failed

**Comment by 5k3105** [comment]
I'd delete the entire therecipe/qt library and re-install. Just guessing.

**Comment by zhuwei** [comment]
Thank you very much.
I will try.

**Comment by therecipe** [comment]
@zhuwei 
Ah, yeah the gui and widgets module will need more then 2GB ram an therefore it's not possible to install them on 32 bit systems atm. (I will try to get it working again in the future, but it's a bit of a hassle because it will always scratch at the 2GB limit)

What you can do is set QT_STUB=true and then re-run the setup, that way you will be able to install the gui and widgets module as well, and then be also able to use code completion.

**Comment by zhuwei** [comment]
@therecipe I understand . Thank you very much!!!
