### ISSUE TITLE
respond to onCreate or onNewIntent in android app?

### ISSUE THREAD

**Issue by dncohen** [therecipe/qt#425]
Hey,

I'm new to both Qt and Android, as well as these go bindings.  So far so good.  I have some example apps running in both linux and on android.  This is great!

I've figured how to modify android/AndroidManifest.xml to have my app handle intents, with a clause like

          <intent-filter>
            
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            
            <data android:scheme="http"
                  android:host="example.com"
                  android:pathPrefix="/gizmos" />
            
            </intent-filter>

With that, a link to that URL does pull up my application, which is just the webview example.  However, I haven't figured out how to respond to the Android events which tell the application which url the intent has requested.
If I understand correctly, an android app is expected to implement onCreate() and onNewIntent() hooks to learn the specifics of the intent.  I'm not sure where to start to do that, so any pointers would be appreciated.  Thanks in advance.  And thanks for the entire project!

**Comment by therecipe** [comment]
Hey

You will need to create your own activity: https://github.com/therecipe/qt/blob/master/internal/examples/androidextras/notification/android/src/org/qtproject/example/notification/NotificationClient.java
+ the overriden onCreate + onNewIntent functions

And then let the Java activity callback into Go code: https://github.com/therecipe/qt/blob/master/internal/examples/androidextras/jni/android/src/qt/java/lang/Runnable.java#L9-L14 and https://github.com/therecipe/qt/blob/master/internal/examples/androidextras/jni/runnable.go#L41-L47
If you pass back a string from java to go you will probably need to use a unsafe pointer and then convert it to a go string with "androidextras.NewQAndroidJniObject6(unsafe.Pointer).ToString()"

(Or  maybe you could store the intent values in java and then request them later from Go, which is probably a bit easier since you don't have to directly deal with javas JNI stuff.)

Then you will only need to edit the android manifest to start/use your custom activity: https://github.com/therecipe/qt/blob/master/internal/examples/androidextras/notification/android/AndroidManifest.xml#L5


If you piece this together it should work, but I just wrote down what I was able to recal from something similar I tried a while ago. 
I will try to create a small example, if I'm able to dig out the code I wrote back then.

But be warned the android apis are a pain in the ass to work with :D
