### ISSUE TITLE
slow build time

### ISSUE THREAD

**Issue by mathieujobin** [therecipe/qt#431]
I started to play around and build myself a small app based on the gallery example

but I was slowdown my compile time..

I am using `QT_PKG_CONFIG=true ~/go/bin/qtdeploy test desktop .`
to recompile and launch my project, which takes 2 minutes on my small laptop...

decided to move my changes to the C++ example, takes 2 second to compile... 

this is a big different, it slow me down quite a bit when developing

**Comment by RadhiFadlillah** [comment]
Hey @mathieujobin

The deployment process is slow because (AFAIK) this binding uses `cgo` to call Qt's API from Go. 

`cgo` is an amazing tool which allows Go programs to interoperate with C libraries. However, there are some [trade-offs](https://dave.cheney.net/2016/01/18/cgo-is-not-go) that happened from using `cgo`, and one of them is slower build times.

When there are `cgo` in your project, `go build` has to do a lot more work to build your code. Building your package is no longer simply passing a list of all the `*.go` files in scope to a single invocation of `go tool compile`, instead:

- The `cgo` tool needs to be invoked to generate the C to Go and Go to C thunks and stubs.
- Your system C compiler has to be invoked for every C file in the package.
- The individual compilation units are combined together into a single .o file.
- The resulting .o file take a trip through the system linker for fix-ups against shared objects they reference.

To make your deployment faster, you can use `-fast` flag like this :

```
qtdeploy -fast test desktop
```

It should be faster than normal `qtdeploy but I doubt it can be as fast as your C++ build time.

Do note before using `-fast` flag, you have to run normal `qtdeploy` at least once before.

_Sent from my Lenovo P70-A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by therecipe** [comment]
@mathieujobin You should generally use "qtdeploy -fast build ..." or "go build ..." (+ qtmoc, qtrcc) during development like @RadhiFadlillah said, and only use "qtdeploy build ..." for the actual deployment.

**Comment by mathieujobin** [comment]
Oh nice ! thank you I will try that.

Every single unix command line should provide a `-fast` switch, I should have thought about that

now if `cgminer -fast` could generate me more bitcoins, that would fantastic

thank you

**Comment by mathieujobin** [comment]
oh, before I open a new issue... I wonder if it is related with `cgo` having to do all that work and making everything a lot slower ?

Would it be possible to add support for Android with `QT_PKG_CONFIG=true` ? 

I have no idea how much work is involve....

```
mathieu@octariki:~/android-ndk-linux$ ~/go/bin/qtsetup full android
FATA[0000] android is not supported as a deploy target on linux with PkgConfig -> install the official Qt version instead and try again 
mathieu@octariki:~/android-ndk-linux$ 
```

thanks

**Comment by therecipe** [comment]
>oh, before I open a new issue... I wonder if it is related with cgo having to do all that work and making everything a lot slower ?

Yeah, some of the slow down comes from using cgo but the most is due the use of qtmoc, qtrcc and qtminimal by qtdeploy.

>Would it be possible to add support for Android with QT_PKG_CONFIG=true ?
I have no idea how much work is involve....

I will look into it.
Which distro do you use? Arch?

**Comment by mathieujobin** [comment]
Yes Arch mainly

Thanks

**Comment by kitech** [comment]
After the first time `QT_PKG_CONFIG=true ~/go/bin/qtdeploy test desktop .`, you even can build with `go build .`. 
If you resource changed, need rerun the slower full build command.

**Comment by mathieujobin** [comment]
thanks all ! much appreciated

**Comment by therecipe** [comment]
@kitech @mathieujobin 
Just for the reference, you can also use qtmoc and qtminimal directly if some resources or moc structs change. That's most of the time faster than re-running the full qtdeploy process.
