### ISSUE TITLE
Frameworks & PlugIns missing from mac .app/Contents

### ISSUE THREAD

**Issue by nursarowar** [therecipe/qt#444]
I have upgraded QT to Qt5.9.1 with homebrew and therecipe/qt to the latest head and ran qtsetup.

Example app and my app is working fine with "qtdeploy test darwin" and "qtdeploy build darwin".

However, the generated .app does not include Frameworks & PlugIns inside Contents (like the old version I was using). I have copied the app to a different computer that does not have qt installed and the app does not work there.

Is something changes in the new version or am I missing anything?

qtsetup check
INFO[0000] running: 'qtsetup check darwin' [docker=false] [vagrant=false]
INFO[0000] GOOS:                        'darwin'
INFO[0000] GOARCH:                      'amd64'
INFO[0000] GOVERSION:                   'go1.8.1'
INFO[0000] GOROOT:                      '/usr/local/go'
INFO[0000] GOPATH:                   *  '/Users/nur/Work/go'
INFO[0000] GOBIN:                       '/Users/nur/Work/go/bin'
INFO[0000] QT_HASH:                     'a7d7d6588cc6988a4f93bda1c34a8f4f55cfd864'
INFO[0000] QT_VERSION:                  '5.9.1'
INFO[0000] QT_VERSION_MAJOR:            '5.9.1'
INFO[0000] QT_DIR:                      '/Users/nur/Qt5.9.1'
INFO[0000] QT_STUB:                     'false'
INFO[0000] QT_DEBUG:                    'false'
INFO[0000] QT_QMAKE_DIR:                ''
INFO[0000] QT_WEBKIT:                   'false'
INFO[0000] QT_HOMEBREW:              *  'true'
INFO[0000] XCODE_DIR:                   '/Applications/Xcode.app'

**Comment by therecipe** [comment]
@nursarowar 

Hey, yeah the Homebrew version is not really intended to be used to deploy "stand alone" applications.
You would need to install the homebrew version of Qt on your target machine as well for this to work.

If you want to really have applications that don't depened on a pre installed Qt version, then you will need to deploy your application after you ran the "regular" setup with the pre-built official Qt version.

(The problem with the homebrew version of Qt is, that the "macdeployqt" tool was broken the last time I check, but it could be that this is fixed by now. I will take a look and report back)

**Comment by nursarowar** [comment]
Qt5.9.1 "macdeployqt" works! Thanks

**Comment by therecipe** [comment]
Nice, then the stand alone homebrew deployments should work again with: https://github.com/therecipe/qt/commit/3725b223d2193530429fb34500ccaa8017746a1d
