### ISSUE TITLE
Issue while compiling with third library

### ISSUE THREAD

**Issue by abhishekgarg120** [therecipe/qt#445]
Hi, 
I am developing on a mac and following the instructions to install docker for building windows and linux packages, but I'm having an issue. I use the following command to build the windows library

`qtdeploy -docker build windows_64_static /opt/repos/my_app`

and it doesn't compile. I found that its crashing because I'm using another go library in my app, gopkg.in/yaml.v2, when I don't use that lib, it compiles. 

How can I install that library on the docker image before running the build command?

Can someones please help me with this. Thanks.

**Comment by therecipe** [comment]
Hey

Can you maybe provide the output of qtdeploy?
It should work out of the box usually, as the docker container will use your host's go packages as well.

You only need to share your GOPATH with docker first. (You can use the docker GUI tool to do this on macOS)

**Comment by abhishekgarg120** [comment]
Hi, Yes I reinstalled everything and then it worked, my linux and windows distribution are working but I'm having issue with mac, when I build a package and then copy it to another mac, it doesn't work, I read that its a dynamic build, but is there any way that we can package everything in one app?
I tried the otool and install_name_tool to copy all the required lib and then relinking them one by one, but I end up with some "missing Qt library for cocoa" warning. You have any idea on that, do I need to install Qt on the client's machine as well?

**Comment by therecipe** [comment]
Do you use the homebrew version of Qt?
If yes, then you will need to install the regular version of Qt instead as well, as only the regular version is able to produce "stand alone" applications atm.
Also maybe take a look here for more info: https://github.com/therecipe/qt/issues/444#issuecomment-327030139

(You can also switch anytime between the homebrew and regular Qt version by exporting/unsetting "QT_HOMEBREW" before invoking "qtdeploy" without the need to re-run the full setup each time. So that you can still keep developing with homebrew's Qt version and only use the regular version during deployments.)
