### ISSUE TITLE
This is the app I am doing in GO/QT

### ISSUE THREAD

**Issue by ReK2Fernandez** [therecipe/qt#479]
https://github.com/ChrisFernandez/goNikto
Feel free to add it to the list.
I am not a software engineer, I work on hacking and security so do not expect the best code haha

**Comment by rashwell** [comment]
@ChrisFernandez I took a look.  I like it so far.  I do have a bit of caution though, probably because I am afraid to take your approach in some of my stuff.  If you spend more time on this app, I would look into [Qt Threading](http://doc.qt.io/qt-5/thread-basics.html).  The reason this raises a read flag for me, is you are appending to the QTextEdit box which is in the gui thread, from inside a go subroutine which itself runs in another thread.  I am thinking your approach might run into issues.  From everything I have read perhaps more specifically with OS X then anything, all GUI stuff should be executed only from the main thread.  I am thinking that if you stick to driving QT's api from Go and that Qt's threading stuff might be more robust cross platform.  In my own app I plan on a lot of Go subroutine stuff as well, I just have in my notes, not to mess with the GUI from a sub thread. Of course if you have it working :) I should just shut up.

**Comment by ChrisFernandez** [comment]
@rashwell hey thanks for poiting this out... I am an GNU/Linux user.. I do not have nor OSX nor windows.. yes android on my phone so it never ocurred to me this issue... but also yes I wanted to do this all in QT as much as possible but I asked a question here: https://github.com/therecipe/qt/issues/474 never really got a reply.. so had to do it the GO way.. and like I mention I am not a software engineer I code for fun, not for work so my code can be very non academic, but I am a hacker so I get it done :) if I can learn to do this in QT like my question above (the issue) yeah I will of course love to do this only in QT.

**Comment by cornfeedhobo** [comment]
This repo is no longer up. this issue can probably be closed.

**Comment by therecipe** [comment]
@cornfeedhobo Thanks, you are right, I will close this issue and also #474.

**Comment by ReK2Fernandez** [comment]
We moved all our repost to gitlab after microsoft bought this, and stop
using github all together along all our colective.
I suggest you guys do the same
