### ISSUE TITLE
Can't install it on ubuntu 16.04

### ISSUE THREAD

**Issue by lugorian** [therecipe/qt#52]
Installation stops(freeze) on installing sql package and eat all memory..

**Comment by therecipe** [comment]
Hey

It can take up to 10-15 min to install the sql package, because
the sql package depends on the heavy widgets package (which gets to be installed first).
And the installation uses around 8gb of ram for those 10-15 minutes.

**Comment by lugorian** [comment]
Thank you for quick answer!
That's the problem.. I have just 4gb on this mashine..
According to your answer i can't install this binding on this machine?
Maybe you should put system requirements in readme?
Anyway what bothers me is the fact that there is a few Go bindings to QT and all of them are incomplete, experimental and unmantained, so i have few questions..

How stable is?
Do you have long term plans to mantain and improve it?
Do you using it for your projects or is still in experimental phase?
Is it posible to support Ubuntu touch(phone) platform?

**Comment by therecipe** [comment]
Unfortunately you can't install a big part of the binding (the widgets package and all the packages that depend on it https://godoc.org/github.com/therecipe/qt/widgets?importers)

However you can still use the binding, but you won't get gocode auto-complete for the packages I mentioned above (because gocode requires them to be installed -.-)

You need to build qtdeploy and qtmoc and put them somewhere in your path.
If you are on linux or mac you could use those:

`cd $GOPATH/src/github.com/therecipe/qt/internal/deploy && go build -o /usr/local/go/bin/qtdeploy`

and

`cd $GOPATH/src/github.com/therecipe/qt/internal/moc && go build -o /usr/local/go/bin/qtmoc`

Then you need to modify `qt/indernal/setup/install.go` and comment `os.Exit(1)` out. (line 274)
After that your need to run the install.go
`cd $GOPATH/src/github.com/therecipe/qt/internal/setup && go run install.go`

(It with throw a few errors and probably take a little bit longer, but you should get most of the packages installed)

Now you can build the examples like this:
`cd $GOPATH/src/github.com/therecipe/qt/internal/examples/widgets && qtdeploy build desktop line_edits minimal`
You will find the binary in line_edits/deploy/[GOOS]_minimal

This works because qtdeploy will dynamically generate a small version of the binding on the fly.
Buy as I said earlier you won't get gocode auto-complete ...

And I will add system requirements to the readme.

---

`How stable this project is?`
The project is pretty stable (probably the most stable of all the available gui packages/projects)

`Do you have long term plans to maintain and improve it?`
I will try to keep it up to date to the latest Qt version and integrate the new modules, but I won't provide backward compatibility to older versions of Qt. I will also add more platforms, cleanup the code and add missing features.

`Do you using it for your projects or is still in experimental phase?`
I'm using it for my projects since 2013, so I probably got the big bugs sorted out.

`Is it possible to support Ubuntu touch(phone) platform?`
Yes, this is already on my todo list.

**Comment by therecipe** [comment]
Added system requirements with https://github.com/therecipe/qt/commit/4c104f8cca5cad6ec4f5fd62524856b7ef0ce737

**Comment by therecipe** [comment]
@lugorian 
Made some changes, your can now define `QT_STUB=true` before running the setup file, this should work on machines with at least 1gb ram.
https://github.com/therecipe/qt#installation

**Comment by lugorian** [comment]
Thank you,
Great work @therecipe!
