### ISSUE TITLE
Web Engine

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#53]
Hi tr,

I was interested in getting this running on windows. You mentioned I needed to install visual studio. I am interested in testing this out when you have time. No rush please.

**Comment by therecipe** [comment]
Hey

I will take a look at it once I got some time, but it probably requires some changes in qtdeploy and
that you install one of these msvc packages from https://download.qt.io/official_releases/qt/5.7/5.7.0/ and either visual studio 2013 or 2015.

Also there might be a chance that they will bring back the WebKit module in 5.8 (which hopefully works with the gcc/g++ version of mingw)

**Comment by therecipe** [comment]
I looked into this, but unfortunately Qt requires a visual studio compiler (2013 or 2015) which seems to be incompatible with cgo.
It may be possible to use clang http://llvm.org/releases/download.html on windows (I'm not entirely sure) instead of msvc, but clang is currently incompatible as well.
But there seem to be related issues to get clang working on windows: https://github.com/golang/go/issues/16932 and https://github.com/golang/go/issues/17014

Also there might be a comeback of the webkit module, which should work with mingw https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Windows-(MSYS)

**Comment by 5k3105** [comment]
tr,

Thanks for taking a look. Happy for any excuse not to install Visual Studio :)

**Comment by therecipe** [comment]
@5k3105 
I haven't forgotten the WebKit on windows and will implement it in the future, I promise ;)
