### ISSUE TITLE
When will version 5.10.1 is come ?

### ISSUE THREAD

**Issue by ubuntulove74** [therecipe/qt#572]
Qt version 5.10.0 have DPI problem in Android , But it and several bugs fixed in Version 5.10.1 ,so when will be it come?

**Comment by therecipe** [comment]
Hey

You should already be able to use Qt 5.10.1, by exporting `QT_VERSION=5.10.1` before running the setup.

**Comment by woodyjon** [comment]
For info, I just installed Qt 5.10.1 on Win 10. I don't know when it changed, but the Qt directory structure is different form your doc (see printscreens). So QT_DIR should be set to "C:\Qt" and not "C:\Qt\Qt5.10.1", otherwise qtsetup does not find the files.
![qt](https://user-images.githubusercontent.com/30724004/37778660-c9dc1812-2dea-11e8-9a46-bd50670e0ab6.png)
![5 10 1](https://user-images.githubusercontent.com/30724004/37778663-cc48136c-2dea-11e8-8825-6385bcffc698.png)

**Comment by therecipe** [comment]
@woodyjon Thanks, yeah this changed in 5.9 or 5.10. Will update the wiki.

**Comment by therecipe** [comment]
Updated the wiki, will close this now.
But for the record, Qt 5.10.1 should work already.
