### ISSUE TITLE
Scaling UI for mobile/android

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#584]
Hey,
So I have compiled the app for windows and OSX and it works perfectly, and in fact technically it compiles perfectly for android too, however the UI scaling is ridiculously zoomed out on android, I need needle fingers to press buttons 😂

I think there must be a setting I can tweak so that it understands the resolution/screen size to scale properly, I was wondering what it is?

I currently am setting:

```
os.Setenv("QT_QUICK_CONTROLS_STYLE", "material") //set style to material
```

```
app.SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
```

and I am using a 

```
app := widgets.NewQApplication(len(os.Args), os.Args)
var view = quick.NewQQuickView(nil)
```

to render the view.
I'm hoping I don't need to manually design a totally different UI for android (with different dimensions) in QML, its so close to being perfect cross platform UI design!

Incidentally, while I'm here, how can I set the window title for a `NewQApplication`?

**Comment by therecipe** [comment]
Hey

No worry, most of the time there is no need to manually scale the design to fit smaller views.

You can set a window title with `view.SetTitle()` and let the content of you view resize to the current view by using `view.SetResizeMode(quick.QQuickView__SizeRootObjectToView)`

So something like this should work:
```go
view := quick.NewQQuickView(nil)
view.SetTitle("Some Title")
view.SetSource(core.NewQUrl3("qrc:/qml/view.qml", 0))
view.SetResizeMode(quick.QQuickView__SizeRootObjectToView)
view.Show() //view.ShowFullScreen()
```

Also `view.ShowFullScreen()` is useful on android to get rid of the status bar iirc.

**Comment by amlwwalker** [comment]
Hmm, interesting, I forgot to put it above, but I already was resizing. The end of my main function contains: 

```
	view.SetResizeMode(quick.QQuickView__SizeRootObjectToView)
	view.Show()

	widgets.QApplication_Exec()
```

I'll try with showFullScreen() , but is there anything else that could be making the app think it needs to be so zoomed out. Ive attached a screen shot.
![image](https://user-images.githubusercontent.com/2920180/38456274-ef8bd7ea-3a7a-11e8-8967-997db0b5e385.png)

In case its of use, inside view.qml, I have:

```
Item {
    id: window
    width: 480
    height: 620
    visible: true
```

could forcing the size here be anything to do with it, and if so, what would a better way to set the size be?

Thanks, Alex

**Comment by therecipe** [comment]
Ah, okay yeah that looks like some different issue (otherwise the toolbar would have had the same width as the item in the middle).

This seems to be an issue in your [got-qt](https://github.com/amlwwalker/got-qt) repo or? Thanks btw, for the promotion :)

I looked into this and it seems like you made some minor mistake when working with the ColumnLayout.

Usually you can't directly anchor (and/or use width/height, not sure about that) on the items inside. (I don't recall it exactly, but the qml engine was very verbose about that in the past. Seems like they did hide those warnings or maybe changed the way things work, but I doubt it.)

However, when you add some item to an Layout, you are usually expected to use the "attached" properties: http://doc.qt.io/qt-5/qml-qtquick-layouts-columnlayout.html such as `Layout.fillWidth` or `Layout.preferredWidth`, `Layout.minimumWidth`, ...

So something like this should work:
```diff
diff --git a/qt/qml/loader.qml b/qt/qml/loader.qml
index 0e670ae..1084ca8 100644
--- a/qt/qml/loader.qml
+++ b/qt/qml/loader.qml
@@ -159,10 +159,8 @@ Item {
         //content holder
 	    StackView {
 	        id: stackView
-	        anchors.top: toolbar.bottom
-	        anchors.left: parent.left
-	        anchors.right: parent.right
-	        anchors.bottom: footer.top
+	        Layout.fillWidth: true
+	        Layout.fillHeight: true
             anchors.margins: 10
               Connections {
                 target: QmlBridge
```

Some other ways to make it work would be to use something like this (for the TextAreaPage only):
```diff
diff --git a/qt/qml/pages/TextAreaPage.qml b/qt/qml/pages/TextAreaPage.qml
index 74d5f40..d267fca 100644
--- a/qt/qml/pages/TextAreaPage.qml
+++ b/qt/qml/pages/TextAreaPage.qml
@@ -43,6 +43,7 @@ import QtQuick.Controls 2.0
 
 ScrollablePage {
     id: page
+    anchors.fill: parent
 
     Column {
         spacing: 40
```
or this for all possible stack items:
```diff
diff --git a/.DS_Store b/.DS_Store
index 40d650a..5e1a6c1 100644
Binary files a/.DS_Store and b/.DS_Store differ
diff --git a/qt/qml/.DS_Store b/qt/qml/.DS_Store
index 5008ddf..7c2c3ae 100644
Binary files a/qt/qml/.DS_Store and b/qt/qml/.DS_Store differ
diff --git a/qt/qml/loader.qml b/qt/qml/loader.qml
index 0e670ae..594409d 100644
--- a/qt/qml/loader.qml
+++ b/qt/qml/loader.qml
@@ -209,6 +209,8 @@ Item {
 	            }
 
 	        }
+
+            onCurrentItemChanged: currentItem.anchors.fill = this
 	    }
 	}
     //menu
```

But even though those last two solutions work, you will run into issues sooner or later. Because similar to how the ColumnLayout works, you aren't supposed to use anchors on the root item of the current stack view item, instead the stack view usually resizes the current item to it's size automatically iirc.

>Note: Using anchors on the items added to a StackView is not supported. Typically push, pop, and replace transitions animate the position, which is not possible when anchors are applied. Notice that this only applies to the root of the item. Using anchors for its children works as expected.

From: https://doc.qt.io/qt-5.10/qml-qtquick-controls2-stackview.html#transitions

Also maybe you should use something like this: https://github.com/therecipe/qt/blob/master/internal/examples/showcases/sia/main.go#L41-L43

To prevent the qml engine from creating `*.qmlc` files which are (when present) will be used instead of the plain `*.qml` files.

Also when you apply the first solution, you may want to reorder the "items" inside your main ColumnLayout to: "ToolBar", "StackView", "Footer" to get rid of the white space above the stack view.

**Comment by amlwwalker** [comment]
Absolutely, no problem its a great project, I put links on youtube and reddit aswell so might get some traffic. Got-qt is just meant to be a (sort of) template app to get going very quickly. I took a bit of time to get something working so thought I would put it all in one place.

Right so this is some nuances of Qt I wasn't aware of, thanks. I made this change:
![image](https://user-images.githubusercontent.com/2920180/38469992-e350c5a0-3b54-11e8-9352-9186b0361c97.png)
and added
![image](https://user-images.githubusercontent.com/2920180/38469996-e9f55b1e-3b54-11e8-9546-321c488755d2.png)

and that has indeed stretched the stackView across the whole of the android screen, which is great. I also added that disable caching line. Cool.

So now the elements are very small still (including the header/footers) (see pic of asynchronous loading page but its the same for all)
![image](https://user-images.githubusercontent.com/2920180/38470026-42ab83c8-3b55-11e8-898b-f64a4a138844.png)

I suppose, is this to do with using `parent`, on the elements (for instance the button/progressbar) rather than fill or something within the stack pages? 
Just so you can see in comparison to the same app being run on OSX
![image](https://user-images.githubusercontent.com/2920180/38470056-96d00690-3b55-11e8-97eb-a7a72236057c.png)

The scaling is different/better.

Incidently, what path can I use for a config.json file inside the compiled app for each OS? I have a config.json in my project that I want to read on run, it works in dev mode, but when its a compiled app, what would the path be (I assume I put the config.json in the darwin/android dirs so they get bundled into the app, just not sure of the path. (Sorry two questions!)

**Comment by therecipe** [comment]
Mh, seems like you need to set the high dpi scaling before creating an application with `widgets.NewQApplication`

Like this:
```diff
diff --git a/qt/main.go b/qt/main.go
index 4080c36..1d9c12f 100644
--- a/qt/main.go
+++ b/qt/main.go
@@ -48,11 +48,12 @@ func main() {
 	var qmlBridge = NewQmlBridge(nil)
 	qmlBridge.ConfigureBridge(config)
 
+	// turn on high definition scaling
+	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
+
 	//4. Configure the qml binding and create an application
-	app := widgets.NewQApplication(len(os.Args), os.Args)
+	widgets.NewQApplication(len(os.Args), os.Args)
 
-	// turn on high definition scaling
-	app.SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
 	//create a view
 	var view = quick.NewQQuickView(nil)
 	//configure the view to know about the bridge
```

For the config file, you can put them in the "windows/linux" folders and then they should be in the same folders as your binary. (You can get the path to your binary with os.Args[0])

For macOS you will need to create two new folders inside the darwin folder like this:
```
.
└── Contents
    └── MacOS
        └── config.json
```
And then get the path to your binary with this function: http://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath

(It was difficult to get the location otherwise, once the application is started inside an "*.app" folder iirc)

For android, you can probably create an "assets" folder inside the android folder and place your files there. And then access them with `file:///android_asset/config.json`, but I'm not quite sure if this worked out of the box. And you could also create an "res" folder to embed resources, but these things are android specific, so you are probably better of reading the docs there.

Another option would be to embed the data with `qtrcc` or maybe use one of the http://doc.qt.io/qt-5/qstandardpaths.html#standardLocations to read/write your data there.

**Comment by amlwwalker** [comment]
This is so great. Yes that worked, setting the Hi Res before creating the window. Good knowledge! :)

Gonna try the config.json thing now and get that working.

(I think) Final question on this issue..... Is there a way to know what permissions are required within the manifest file at compilation, or is the best way to compile the app, hook it up to adb, and watch the logger to see what permissions are not there, then edit the manifest.json and recompile?
Do you every build Go apps for Android, and if so, what libraries do you use to interact with the filesystem/OS? I see there are a couple of options: https://github.com/xlab/android-go being one of them. I am planning on using their libraries but compiling with therecipe/qt, I assume that would work....

**Comment by amlwwalker** [comment]
Hmm, so been playing with accessing the config.json from android. My main now has:

```
	fileDst := filepath.Join(core.QStandardPaths_StandardLocations(core.QStandardPaths__AppDataLocation)[0], "//assets/config.json")
	if core.QFile_Exists(fileDst) {
		core.QFile_Remove2(fileDst)
	}

	file := core.NewQFile2("//assets/config.json")
	if file.Exists2() {
		file.Copy(fileDst)
	}
	fmt.Println("file ", file)
	var config Config
	switch runtime.GOOS {
		case "android":
			_, config = LoadConfiguration(fileDst)
			fmt.Println("android config: ", config)
		default:
			_, config = LoadConfiguration("config.json")
	}
	_, tmpConfig := LoadConfiguration("//assets/config.json")
	fmt.Println("just for testing: ", tmpConfig)
```

based on a few stackoverflow links suggesting how to get a relative path to the assets directory. My output based on the above is:

```
open /data/user/0/org.qtproject.example.go/files/assets/config.json: no such file or directory
android config:  {       false false}
open //assets/config.json: no such file or directory
just for testing:  {       false false}
{Author: Path: Date: Mode: Host: Version: Port: Hotload:false Verbose:false}
```
I got the suggestions from: [SO link](https://stackoverflow.com/questions/22906068/how-to-get-file-path-of-asset-folder-in-android?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)
(and a couple of other links which I've lost now). Anyhow, I tried both `//assets/config.json` and `file:///android_asset/asset` but to no avail.  

[this link](https://stackoverflow.com/questions/18302603/where-do-i-place-the-assets-folder-in-android-studio) suggests that perhaps the assets directory is in the wrong place within our apk? I cant see in the apk, but I can see that in deploy/android/build/ there is assets, and that suggests it should be in src? (which i don't think we have because we aren't building an app using Android Studio...)

(P.S Think cant use Google OAuth in android app, gonna need to approach that a different way)

**Comment by therecipe** [comment]
>(I think) Final question on this issue..... Is there a way to know what permissions are required within the manifest file at compilation, or is the best way to compile the app, hook it up to adb, and watch the logger to see what permissions are not there, then edit the manifest.json and recompile?

Yes, you will need to check which java call requires which permission and then add it manually to the Manifest.

>Do you every build Go apps for Android, and if so, what libraries do you use to interact with the eatures of the OS?

Yes a while ago, and you can use the "androidextras" package, maybe take a look here: https://github.com/therecipe/qt/tree/master/internal/examples/androidextras

>I see there are a couple of options: https://github.com/xlab/android-go being one of them. I am planning on using their libraries but compiling with therecipe/qt, I assume that would work....

That should probably work, however I'm not sure if the android NDK gives you access to most of the stuff you need. (It's mostly slow level stuff that was made available through it afaik).
For most stuff you will still need to use Java and the JNI (which is wrapped by the "androidextras" package).

>My reason for wanting to do so, is my app currently using google oAuth to authenticate my users. Instead of me building a whole login process, i wanted to use oAuth in a webview, however Google is clever enough to realise its an in-app browser and doesn't allow it. I looked into changing the user-agent, but doesnt seem too straight forward. So wanting to now open an intent, to open the browser to log the user in.... bit messy but just to get things going....

Yeah calling intents is possible, however it was messy to get it working irrc (if) need to wait for the response, because you will need to use some kind of message object for this. (at least using the android sdk from the jni was a pain in the ass for the stuff I needed)

It's probably way simpler to use some other implementation of oAuth if possible.


For the assets:

You will need to use `file := core.NewQFile2("assets:/config.json")` and place the config file in the subfolder called "assets" within the "android" folder:

```
android
└── assets
    └── config.json
```

Then to copy the file from the "read-only" asset location to another location, you will need to use something like this:
```
fileDst := filepath.Join(core.QStandardPaths_StandardLocations(core.QStandardPaths__AppDataLocation)[0], "config.json")
```
If you want to put the config file in a sub folder ("assets" or so) at the destination, then you will need to create a folder there first. (Because you used "//assets/config.json" in your last post)

**Comment by amlwwalker** [comment]
Right thats cool, the androidextras demo is great I'm going to incorporate some of that stuff now. I see how the permissions are working in the manifest file there. Couple of questions:

* I see in android/src/org/qtproject/example/notification/ there is NotificationClient.java

Do I need to include that file in a similar directory structure (changing the path of qtproject/example/notification to whatever my project is called? I'm imagining in the manifest I set this somewhere.

* I am using [boltdb](https://github.com/boltdb/bolt) which needs write access to somewhere on the device. Apart from the permission to write in the manifest file, how do I discover where it will be allowed to write?

This is great.

**Comment by therecipe** [comment]
>Do I need to include that file in a similar directory structure (changing the path of qtproject/example/notification to whatever my project is called?

You don't really need to change the path, but if you do it then you will need to change it here as well: https://github.com/therecipe/qt/blob/master/internal/examples/androidextras/notification/notificationclient.go#L25

>How can I make it so notification appears across top of device, rather than just in notification bar as an icon? I presume this is an adjustment to the java code.

Yepp, you will need to make some changes. Maybe take a look here: https://developer.android.com/training/notify-user/expanded.html

>I also presume I can follow this template to create an intent that opens the android device's file browser?

I'm not that experienced with the android sdk, so I'm not sure if this is simple or not.
But it's probably possible to get this working somehow.

>Our earlier fix to deal with the scaling was great however I have a qml FileDialog that opens when a button is clicked, and that seems to suffer on phone:

This seems to be a bug, take a look here: https://forum.qt.io/topic/69965/filedialog-rendering-broken-on-android/6 and here: https://bugreports.qt.io/browse/QTBUG-51999

> Does this tell me something to do with where I should put the config.json inside the assets directory? For instance should I have it in

For this structure to work you will probably need to use something like this:

```go
file := core.NewQFile2("assets:/org.qtproject.example.notification/files/config.json")
```

>androidextras seems like something you have made as opposed to a standard library, what is it capable of? Is there documentation anywhere, interacting the chunks of java to do "androidy" things?

Yeah, I needed to deduce some of the functions semi-manually since Go doesn't support generics.
But it's basically just this class that's important: http://doc.qt.io/qt-5/qandroidjniobject.html
It lets you call into Java code easily, and if you look here: https://github.com/therecipe/qt/tree/master/internal/examples/androidextras/jni
You can even callback from Java into Go code with some cgo usage.

You can probably do most of the the stuff you need to do, however some things like passing Java arrays around are not supported yet.
