### ISSUE TITLE
Removing all elements in a list (to stop duplication)

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#589]
Looking at this file here:
https://github.com/therecipe/qt/blob/master/internal/examples/quick/listview/personmodel.go
There is a removePerson function, however how would you clear the whole list? I attempted:

```
func (m *PersonModel) clearPeople() {
	lengthOfResults := len(m.People())
	for i := 0; i < lengthOfResults; i++ {
		m.removePerson(i)
	}
}
func (m *PersonModel) removePerson(row int) {
	m.BeginRemoveRows(core.NewQModelIndex(), row, row)
	m.SetPeople(append(m.People()[:row], m.People()[row+1:]...))
	m.EndRemoveRows()
}
```

and this almost works, however in some cases (when the list goes from 2 to 1 elements) it crashes out with an index out of bounds error on `m.SetPeople(append(m.People()[:row], m.People()[row+1:]...))`

**Comment by therecipe** [comment]
Ah, yes this is caused by using append to remove an item from an array.
The solution is to remove the items in reversed order instead:

```go
	for i := len(m.People()) - 1; i >= 0; i-- {
		m.removePerson(i)
	}
```

but you should better use something like this instead:

```go
	m.BeginResetModel()
	m.SetPeople(make([]*Person, 0))
	m.EndResetModel()
```

this won't create unnecessary copies while "removing" the items and also will let Qt update the listview in one go, instead of updating it for each item separately.

**Comment by amlwwalker** [comment]
Yep, this (second solution) works nicely. Was looking for an example that contained that, but couldn't find one. Realised my solution would cause a problem as was iterating over something I was removing from....
Thanks!
