### ISSUE TITLE
Copying to clipboard

### ISSUE THREAD

**Issue by chuckwagoncomputing** [therecipe/qt#596]
How can I copy to the system clipboard?

QT has a QClipboard class, but how do I use it with this binding? I can't find any references to it in the docs.

I came up with a little hack using an invisible TextArea, but I need to set the clipboard MIME types, which I unfortunately can't do that way.

**Comment by therecipe** [comment]
Hey

Something like this should work:

```go
package main

import (
	"os"

	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	app := widgets.NewQApplication(len(os.Args), os.Args)

	println("old clipboard:", app.Clipboard().Text(gui.QClipboard__Clipboard))
	app.Clipboard().SetText("some text", gui.QClipboard__Clipboard)
	println("new clipboard:", app.Clipboard().Text(gui.QClipboard__Clipboard))

	widgets.QApplication_Exec()
}
```

Maybe also take a look here: http://doc.qt.io/qt-5/qclipboard.html#details

**Comment by therecipe** [comment]
Mh, you can probably create a general Qt related question on SO most of the time.
Because people having used one of the python bindings or are using Qt from C++ should also be able to answer most of the questions. (The API is mapped one-to-one from C++ to Go, so it should be easily comparable)

But there are also already tons of answered questions on SO (for Qt in C++ and python) + the official C++ documentation of Qt is really great.

And most of the time you will just need to get to know the class name of the class you want to use and then you can directly look into the official docs: http://doc.qt.io/qt-5/classes.html
All classes should have some "Detailed Description" section that explains the general usage.
