### ISSUE TITLE
qml example can not work(win10x64)

### ISSUE THREAD

**Issue by fcying** [therecipe/qt#60]
the other example run ok.

two samples in qml folder build ok, but doesn't work, when I run it, nothing happened

**Comment by therecipe** [comment]
Hey

Yes, unfortunately the `qml/application` example doesn't work somehow. https://github.com/therecipe/qt/issues/49#issuecomment-239646637
But I will look into this.

The `qml/prop` example is probably working, but doesn't have visual elements.

prop.go
```go
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/qml"
)

func main() {

	core.NewQCoreApplication(len(os.Args), os.Args)

	var (
		component = qml.NewQQmlComponent5(qml.NewQQmlEngine(nil), core.NewQUrl3("qrc:///qml/prop.qml", 0), nil)
		object    = component.Create(nil)
	)

	fmt.Println("Property value:", object.Property("someNumber").ToInt(false))
	object.SetProperty("someNumber", core.NewQVariant7(5000))
	fmt.Println("Property value:", object.Property("someNumber").ToInt(false))
	object.SetProperty("someNumber", core.NewQVariant7(200))
	fmt.Println("Property value:", object.Property("someNumber").ToInt(false))
}
```

prop.qml
```qml
import QtQuick 2.0

Item {
    property int someNumber: 100
}
```

The QQmlComponent is used to interpret the the `prop.qml` without displaying visual / gui elements.
And because the cmd is hidden under windows you won't see anything, not even the output from print.

**Comment by fcying** [comment]
Okay, I know, thanks~~
