### ISSUE TITLE
failed to find qt_dir

### ISSUE THREAD

**Issue by W1sh** [therecipe/qt#606]
I followed the installations steps, but when I try to run qtsetup this is what I get:

```
INFO[0000] running: 'qtsetup prep'                      
INFO[0000] successfully created qtrcc symlink in your PATH (/usr/local/bin/qtrcc) 
INFO[0000] successfully created qtmoc symlink in your PATH (/usr/local/bin/qtmoc) 
INFO[0000] successfully created qtminimal symlink in your PATH (/usr/local/bin/qtminimal) 
INFO[0000] successfully created qtdeploy symlink in your PATH (/usr/local/bin/qtdeploy) 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.10.1'      
INFO[0000] GOROOT:                      '/usr/local/go' 
INFO[0000] GOPATH:                      '/home/bruno/go' 
INFO[0000] GOBIN:                       '/home/bruno/go/bin' 
INFO[0000] QT_HASH:                     '49a0021f932c3446cda48796e4871093d8189a66' 
INFO[0000] QT_VERSION:                  '5.10.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.10.0'        
INFO[0000] QT_DIR:                      '/home/bruno/Qt5.10.0' 
PANI[0000] failed to find QT_DIR (/home/bruno/Qt5.10.0)  error="open /home/bruno/Qt5.10.0: no such file or directory"
panic: (*logrus.Entry) (0x7f7560,0xc42008b360)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc42008a190, 0xc420083cb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/bruno/go/src/github.com/sirupsen/logrus/entry.go:112 +0x254
github.com/sirupsen/logrus.(*Entry).Panic(0xc42008b310, 0xc4200517d0, 0x1, 0x1)
        /home/bruno/go/src/github.com/sirupsen/logrus/entry.go:182 +0xaa
github.com/sirupsen/logrus.(*Entry).Panicf(0xc42008b310, 0x827201, 0x16, 0xc420051b48, 0x2, 0x2)
        /home/bruno/go/src/github.com/sirupsen/logrus/entry.go:230 +0xed
github.com/therecipe/qt/internal/cmd/setup.Check(0x80244b, 0x5, 0x800000)
        /home/bruno/go/src/github.com/therecipe/qt/internal/cmd/setup/check.go:147 +0x13e5
main.main()
```

It seems that QT_DIR path is incorrect as my installation is in /opt/Qt . How can I change the path to the correct one?

**Comment by arsham** [comment]
Can you try this please? 
```bash
$ export QT_PKG_CONFIG=true
$ qtsetup
```

**Comment by W1sh** [comment]
This doesn't seem to fix the issue. Still get the same error

**Comment by arsham** [comment]
Well, here is how I've installed everything:
```bash
$ curl -L -o qt-opensource-linux-x64-5.10.1.run -C - https://download.qt.io/official_releases/qt/5.10/5.10.1/qt-opensource-linux-x64-5.10.1.run
# Run qt-opensource-linux-x64-5.10.1.run and select all options.

$ yaourt -S $(pacman -Ssq ^qt5-.\*) mesa libpulse
$ export QT_WEBKIT=true
$ export QT_PKG_CONFIG=true
# Just in case, do the following again:
$ go get -u -v github.com/therecipe/qt/cmd/...
$ qtsetup
```

Hope that helps.

**Comment by W1sh** [comment]
I tried redownloading everything but still same issue :/

**Comment by arsham** [comment]
What is this folder's contents: `/home/bruno/Qt5.10.0`?

**Comment by therecipe** [comment]
@W1sh try to export `QT_DIR=/opt/Qt` and then run the setup again.
also maybe take a look here: https://github.com/therecipe/qt/wiki/Installation

**Comment by arsham** [comment]
If you look [closely](https://github.com/therecipe/qt/issues/606#issue-317254789) it says:
```
INFO[0000] QT_DIR:                      '/home/bruno/Qt5.10.0'
```
It's the last `INFO` message.

**Comment by arpitjindal97** [comment]
mkdir /home/bruno/Qt5.10.0

**Comment by therecipe** [comment]
Will close this now, please reopen if this is still relevant

**Comment by BH90210** [comment]
Hello,

I'm reopening because I have the same issue and I can not resolve it.

I'm under ubuntu, and got everything working, then updated QT (from 5.12.0 to 5.12.2 cause of a bug with textField..) and removed 5.12.0 since I wouldn't use it anymore.
Qt works fine. Compiles and runs everything on desktop & mobile.
Then I followed the install instructions (one the initial setup I didn't follow this step) and added 
`
export QT_DIR=$HOME/Qt/5.12.2
export QT_VERSION=5.12.2
export QT_API=5.12.2
`
to my `~/.profile`. I tried both `source ~/.profile` and reboot.
I downloaded everything again with `sudo go get -u -v -tags=no_env github.com/therecipe/qt/cmd/...`
When I try to run setup `sudo /home/****/go/bin/qtsetup` I get this log and then a bunch of error (files not found)
`INFO[0000] running: 'qtsetup prep'                      
INFO[0000] successfully created qtrcc symlink in your PATH (/usr/local/bin/qtrcc) 
INFO[0000] successfully created qtmoc symlink in your PATH (/usr/local/bin/qtmoc) 
INFO[0000] successfully created qtminimal symlink in your PATH (/usr/local/bin/qtminimal) 
INFO[0000] successfully created qtdeploy symlink in your PATH (/usr/local/bin/qtdeploy) 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.12'        
INFO[0000] GOROOT:                      '/usr/local/go' 
INFO[0000] GOPATH:                      '/home/****/go' 
INFO[0000] GOBIN:                       '/home/****/go/bin' 
INFO[0000] QT_HASH:                     'da9f0689a846bd6233b12e4a65a8d443fb35f4b3' 
INFO[0000] QT_API:                      ''              
INFO[0000] QT_VERSION:                  '5.12.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.12.0'        
INFO[0000] QT_DIR:                      '/home/****/Qt' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'ubuntu'        
INFO[0000] QT_PKG_CONFIG:               'false'         
`
tried adding to my /root/.profile as well, nothing.
I'm stuck.
