### ISSUE TITLE
App GUI do not displayed on Windows

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#607]
Hi,

I'm trying to use cross-platform compilation using latest docker `windows_32_shared` and `windows_64_shared` and run the result on Windows 10. If I run the executable, the GUI is not displayed and the application just stucked (I know this because it prevents Windows from restarting, but it doesn't listed on task manager) ... this is happening on both results. 
Please use [this sample](https://github.com/therecipe/qt/files/1947507/therecipe-issue.zip) to reproduce the issue, I compiled the binaries on osx with latest version of binding.

Thanks.

**Comment by therecipe** [comment]
Hey

I looked into this, and there were a few small issues.
The first is that the windows docker images still use Qt 5.8 and you will therefore need to use `import QtQuick 2.8`.
The others are that since you only import the charts module through qml, the dependency detection won't work and you will therefore need to import the charts module in Go as well and then use something like `var _ charts.QChart` to make it work.

Please leave this open, since this issue probably affects the windows msys2 deployments and probably also the plain normal linux deployments.
