### ISSUE TITLE
QLineEdit loaded from ui resource doesn't receive KeyPressEvent

### ISSUE THREAD

**Issue by arsham** [therecipe/qt#611]
Hi,

With a simple QWidget loaded from a file and the following snippet:
```go
userInput := widgets.NewQLineEditFromPointer(
	dialog.FindChild("lineEdit", core.Qt__FindChildrenRecursively).Pointer(),
)
userInput.ConnectKeyPressEvent(func(event *gui.QKeyEvent) {
	fmt.Println("Key pressed")
        userInput.KeyPressEventDefault(event)
})
userInput.ConnectTextChanged(func(text string) {
	fmt.Println("Text changed")
})
```
The userInput receives `TextChangedEvent` event but not the `KeyPressedEvent`.

However, if it's set it up directly from the go code, will work.

Thanks.

**Comment by therecipe** [comment]
Same issue as in https://github.com/therecipe/qt/issues/610, `keyPressEvent` won't work because it's a virtual function http://doc.qt.io/qt-5/qlineedit.html#keyPressEvent, but textChanged will work because it's a signal: http://doc.qt.io/qt-5/qlineedit.html#textChanged.

I also looked into the wiki page, it looks good.
Did you benchmark the difference before and after?
I think it should speedup the initial setup, but I'm not sure if it will speedup compilation of your programs later (since the go tool already does all sorts of caching, and the slowest part is usually Go's own linker)

**Comment by therecipe** [comment]
Nice, okay that's awesome.
You can also speedup the go link process by using `go build -ldflags="-s -w"` as well. (If you don't already use `qtdeploy -fast`)
