### ISSUE TITLE
problem with advanced examples (in your examples repo)

### ISSUE THREAD

**Issue by creedr** [therecipe/qt#623]
Hi,

I was trying to run some of the examples in your [therecipe/examples](https://github.com/therecipe/examples) repo, and it wasn't working right, but it seems you don't have issues enabled on that repo. 

I tried running some of the advanced examples, but kept getting an issue with moc.cpp. For instance running qtdeploy qtmoc on the [tableview](https://github.com/therecipe/examples/tree/master/advanced/widgets/tableview) I get an error on `moc.cpp:124: Error: Not a signal or slot declaration`

I'm trying to figure out where the problem is here. The code in that moc.cpp (lines 123-125) looks like

```
if signal := qt.GetSignal(ptr, "add,auto"); signal != nil {
signal.(func (TableItem) )(itemD)
}
```
which has something to do with this code from main.go line 21
```
_ func(item TableItem) `signal:"add,auto"`
```
The other [advanced/widgets](https://github.com/therecipe/examples/tree/master/advanced/widgets) examples are producing this same error for me as well. I am running this on Windows 10 with mingw-64bit.

**Comment by therecipe** [comment]
Hey

Hm, did you try to update your version of the binding?
Like you said, this is probably caused by the new syntax from line 21.

I will have to document that feature, but it's basically just a shortcut to connect the "add" signal to: https://github.com/therecipe/examples/blob/master/advanced/widgets/tableview/main.go#L82 automatically without writing `xyz.ConnectAdd(xyz.add)` by hand.
