### ISSUE TITLE
the docker image has no specific method

### ISSUE THREAD

**Issue by akiyosi** [therecipe/qt#658]
Hi,
I updated to Qt 5.11.1 of my repository, and also updated Qt Binding to use.
With this correspondence, I fixed some changes and the build succeeded on macos.
However, using windows docker image, some methods do not exist and get the following error.

```
../../editor/font.go:28:18: fontMetrics.HorizontalAdvance undefined (type *gui.QFontMetricsF has no field or method HorizontalAdvance)
../../editor/palette.go:199:46: p.ws.font.defaultFontMetrics.HorizontalAdvance undefined (type *gui.QFontMetricsF has no field or method HorizontalAdvance)
../../editor/screen.go:903:30: s.ws.font.fontMetrics.HorizontalAdvance undefined (type *gui.QFontMetricsF has no field or method HorizontalAdvance)
../../editor/signature.go:109:36: s.ws.font.defaultFontMetrics.HorizontalAdvance undefined (type *gui.QFontMetricsF has no field or method HorizontalAdvance)
```

I thought that something I was wrong because I looked like an image corresponding to the latest Qt Binding, each image was updated 6 days ago at therecipe/qt's Docker Hub.
I did `docker rmi`, `docker pull` again, but I could not resolve the error.

Would you please teach if there is any advice?

**Comment by therecipe** [comment]
Hey

Yeah, the problem is that the windows docker images still only contain Qt 5.8 atm.
This is the root cause of many issue lately and I will create a separate issue for this to refer to in the future.

However, I will look into this and maybe there is an simple way to easily fix this.
I think for example some compatibly mode would be easy to create, where you only would need to run something like this: "qtdeploy -docker -api=5.11.1 build windows" to make it work for you.

**Comment by akiyosi** [comment]
Thanks for the reply!
I understood that the windows docker image is Qt 5.8.
