### ISSUE TITLE
error /usr/bin/go is not a directory

### ISSUE THREAD

**Issue by richtourist** [therecipe/qt#685]
Hi
I'm on Arch linux and installed your qt repo. It seemed successful and the test apps opened fine during installation. 
But when I run qtdeploy on my own go code I get the below error.

error="fork/exec /usr/bin/go: not a directory" func=RunCmd name="go list deps"

It is true /usr/bin/go is NOT a directory, it is a link to /usr/lib/go/bin/go which is the path to the Go executable itself. The link permissions are lrwxrwxrwx.
Other go code builds fine with 'go build myCode.go'

my go env is:

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dev/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dev/docs/share/libs/go:/home/dev/docs/projects/testPro/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build987173157=/tmp/go-build -gno-record-gcc-switches"

and qtsetup check desktop is:

INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.10.3'      
INFO[0000] GOROOT:                      '/usr/lib/go'   
INFO[0000] GOPATH:                   *  '/home/dev/docs/share/libs/go' 
INFO[0000] GOBIN:                    *  '.'             
INFO[0000] QT_HASH:                     'ad4b26dcd5d05cbd3e39c874b80b79213244f845' 
INFO[0000] QT_VERSION:                  '5.11.1'        
INFO[0000] QT_VERSION_MAJOR:            '5.11.1'        
INFO[0000] QT_DIR:                   *  '/usr/include/qt/QtCore' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'arch'          
INFO[0000] QT_PKG_CONFIG:               'false'

NOTE there are asterisks against GOPATH, GOBIN, and QT_DIR

Any help would be much appreciated.
Should my GOROOT have a /bin on the end?

Thanks for your work. I'm hoping to escape from cpp to go!

**Comment by richtourist** [comment]
I'm fairly newb to linux and Qt, but... Looking at the command that raises this error, it looks like it is trying to gather info about what items are in the directory. Like it is trying to list things in the directory in order to install them or link them or something. It makes me wonder if I have an env variable set wrong which is causing the command to be run on the wrong /path/dir.
I tried setting GOPATH, GOROOT, GOEXE, GOBIN to all kinds of educated guesses, and it just broke stuff.
I also tried placing a directory called go there and moving the symlinks into it, but then the error just changed to can't find go executable.
Also, I reinstalled this repo, and the examples ran fine during that, but afterwards I just get the above error again.

Don't know what else to try.

**Comment by therecipe** [comment]
Hey

Mh, if the setup did run successful then maybe the issue is caused by the way you run qtdeploy.
Try to run it like this, if you aren't already: `qtdeploy test desktop path/to/your/project/dir` or `qtdeploy test desktop .` if you are already inside the right folder.

>Should my GOROOT have a /bin on the end?

No, and you usually won't need to set GOROOT or GOBIN manually at all.
GOROOT is detected by the go tool automatically, and GOBIN is `$GOPATH/bin` by default.
So unless you explicitly want to override them, it's better to keep them unset.

The only env variables you probably need to set are GOPATH and QT_DIR.
But you can also keep them unset and then use the default locations:
For GOPATH it's `$HOME/go` and for QT_DIR it's `$HOME/Qt`.

>Looking at the command that raises this error, it looks like it is trying to gather info about what items are in the directory. Like it is trying to list things in the directory in order to install them or link them or something. It makes me wonder if I have an env variable set wrong which is causing the command to be run on the wrong /path/dir.

I'm not really sure, maybe try to test one of the examples after unsetting all the unnecessary GO env variables, just cd into `$GOPATH/src/github.com/therecipe/qt/internal/examples/widgets/line_edits` and then run `qtdeploy` or `qtdeploy test desktop .`

Also, you should be able to get a list of the env variables that are recognized by qtdeploy by running:
`env | grep -E 'QT|GO'` then simply run `unset GOBIN` and so on for all the env variables you don't need.

And maybe try to use the `-debug` flag when running qtdeploy, and then post the last part of the log here, so I can look into it.

**Comment by richtourist** [comment]
HI, thanks very much for your help.
I ran 'qtdeploy test desktop .' in the src directory of the project. First I realise I don't have the .index files installed.
Sorry, that's a bit stupid of me, I got distracted and forgot about them. Where do they come from? In the repo? Got loads of the below errors followed by the 'panic' line and the 'goroutine 1' line.

ERRO[0000] failed to load /usr/include/qt/QtCore/Docs/Qt-5.11.1/qtxmlpatterns/qtxmlpatterns.index  error="open /usr/include/qt/QtCore/Docs/Qt-5.11.1/qtxmlpatterns/qtxmlpatterns.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=XmlPatterns

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x75c871]

goroutine 1 [running]:
github.com/therecipe/qt/internal/cmd/minimal.Minimal(0xc42008c750, 0x26, 0x81bbf8, 0x5, 0x0, 0x0)
        /home/dev/go/src/github.com/therecipe/qt/internal/cmd/minimal/minimal.go:191 +0xaf1
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x7ffc2e407b34, 0x4, 0x81bbf8, 0x5, 0xc42008c750, 0x26, 0x0, 0x0, 0x0, 0x0, ...)
        /home/dev/go/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:61 +0xe22
main.main()
        /home/dev/go/src/github.com/therecipe/qt/cmd/qtdeploy/main.go:114 +0x581

Here are the env vars:
env | grep -E 'QT|GO'
GOPATH=/home/dev/docs/projects/testPro/go
QT_DIR=/home/dev/docs/projects/QT_DIR
GOBIN=/home/dev/docs/projects/testPro/go/bin

**Comment by richtourist** [comment]
Oh, actually I do have the .index doc files installed.
But I have probably got the wrong QT_DIR. I've tried setting it to both /usr/lib/qt, /usr/include/qt, /usr/share/doc/qt/activeqt, and /usr/share/doc/qt
but I get the same errors in each case.

**Comment by richtourist** [comment]
I think that is it!
The file paths in the errors that say 'no such file or directory' are slightly different to the ones that do actually exist.... eg capital Docs and extra wrapper directory.

QT_DIR/Docs/Qt-5.11.1/qtdbus/qtdbus.index
QT_DIR/docs/Qt-5.11.1/qtdbus.index

I guess this is because I used the ARCH Pacman install?
Do you think I should uninstall and try the official Qt source?

**Comment by therecipe** [comment]
Since you are using the pacman version, you could try to unset QT_DIR, and then instead export `QT_PKG_CONFIG=true`, this should let qtdeploy use the Qt version installed by pacman.

I haven't tested it on arch in a while, but if the index files are not present under `/usr/share/doc/qt` like they used to, then you will also need to export `QT_DOC_DIR` to point to the directory containing the index files.

**Comment by richtourist** [comment]
OK, I went with...
env | grep -E 'QT|GO'
QT_PKG_CONFIG=true
QTDIR=
QT_DOC_DIR=/usr/share/doc/qt
GOPATH=/home/dev/docs/projects/testPro/go
GOBIN=/home/dev/docs/projects/testPro/go/bin

...and I got lots of the below. But maybe they are classes my qml file doesn't use. It is only a simple example file.
But at the end it says it can't find github.com/therecipe/qt
Is this because I've got my stuff in two places...a library with your repo in it:
/home/dev/docs/share/libs/go/src/github.com

and a serperate projects folder:
/home/dev/docs/projects/testPro
   /go
   /qml


Here is the end of the error output:

DEBU[0004] failed to parse header                        class=QSurface3DSeries module=DataVisualization
DEBU[0004] failed to parse header                        class=QSurfaceDataItem module=DataVisualization
DEBU[0004] failed to parse header                        class=QSurfaceDataProxy module=DataVisualization
DEBU[0004] failed to parse header                        class=QTouch3DInputHandler module=DataVisualization
DEBU[0004] failed to parse header                        class=QValue3DAxis module=DataVisualization
DEBU[0004] failed to parse header                        class=QValue3DAxisFormatter module=DataVisualization
DEBU[0004] prepare                                       module=Charts
DEBU[0004] prepare                                       module=Speech
DEBU[0004] prepare                                       module=QuickControls2
DEBU[0004] prepare                                       module=Sailfish
DEBU[0004] prepare                                       module=WebView
DEBU[0004] failed to find header file                    class=QWebViewFactory module=WebView
DEBU[0004] prepare                                       module=RemoteObjects
DEBU[0004] failed to find header file                    class=QRemoteObjectPackets module=RemoteObjects
DEBU[0004] failed to find header file                    class=QRemoteObjectStringLiterals module=RemoteObjects
DEBU[0004] failed to find header file                    class=QtROClientFactory module=RemoteObjects
DEBU[0004] failed to find header file                    class=QtROServerFactory module=RemoteObjects
DEBU[0004] Execute                                       cmd="/usr/lib/go/bin/go list -f {{.Root}} github.com/therecipe/qt" dir= env= func=RunCmd name="get list gopath"
ERRO[0004] failed to run command                         cmd="/usr/lib/go/bin/go list -f {{.Root}} github.com/therecipe/qt" dir= env= error="exit status 1" func=RunCmd name="get list gopath"
can't load package: package github.com/therecipe/qt: cannot find package "github.com/therecipe/qt" in any of:
        /usr/lib/go/src/github.com/therecipe/qt (from $GOROOT)
        /home/dev/docs/projects/testPro/go/src/github.com/therecipe/qt (from $GOPATH)

**Comment by richtourist** [comment]
FANTASTIC... all working now.
I hacked it a bit by copying the github.com/therecipe/qt so that it was in both the 'lib' dir I first put it in, and also in the 'src' dir where my file.go is.
I guess I need to tidy up my file structure and my env vars.

Hey, thanks very much for all your help. I really appreciate it.
I can't code well, but if I can contribute by working on the documentation for you or something like that, let me know what I can do.

Rich.

**Comment by therecipe** [comment]
>OK, I went with...
env | grep -E 'QT|GO'
QT_PKG_CONFIG=true
QTDIR=
QT_DOC_DIR=/usr/share/doc/qt
GOPATH=/home/dev/docs/projects/testPro/go
GOBIN=/home/dev/docs/projects/testPro/go/bin

looks good, but maybe unset QTDIR with `unset QTDIR`

>DEBU[0004] failed to parse header class=QSurface3DSeries module=DataVisualization
DEBU[0004] failed to parse header class=QSurfaceDataItem module=DataVisualization
DEBU[0004] failed to parse header class=QSurfaceDataProxy module=DataVisualization
DEBU[0004] failed to parse header class=QTouch3DInputHandler module=DataVisualization
DEBU[0004] failed to parse header class=QValue3DAxis module=DataVisualization
DEBU[0004] failed to parse header class=QValue3DAxisFormatter module=DataVisualization
DEBU[0004] prepare module=Charts
DEBU[0004] prepare module=Speech
DEBU[0004] prepare module=QuickControls2
DEBU[0004] prepare module=Sailfish
DEBU[0004] prepare module=WebView
DEBU[0004] failed to find header file class=QWebViewFactory module=WebView
DEBU[0004] prepare module=RemoteObjects
DEBU[0004] failed to find header file class=QRemoteObjectPackets module=RemoteObjects
DEBU[0004] failed to find header file class=QRemoteObjectStringLiterals module=RemoteObjects
DEBU[0004] failed to find header file class=QtROClientFactory module=RemoteObjects
DEBU[0004] failed to find header file class=QtROServerFactory module=RemoteObjects

these are just warnings so you can probably ignore them


>...and I got lots of the below. But maybe they are classes my qml file doesn't use. It is only a simple example file.
But at the end it says it can't find github.com/therecipe/qt
Is this because I've got my stuff in two places...a library with your repo in it:
/home/dev/docs/share/libs/go/src/github.com
>and a serperate projects folder:
/home/dev/docs/projects/testPro
¬/go
¬/qml

ah, I think the problem is that you use GOPATH wrong.
the GOPATH should hold all your go related files (the binding and your project for example), it's also the place where packages are downloaded if you run `go get`.

that's also the reason why you got this:
>ERRO[0004] failed to run command cmd="/usr/lib/go/bin/go list -f {{.Root}} github.com/therecipe/qt" dir= env= error="exit status 1" func=RunCmd name="get list gopath"
can't load package: package github.com/therecipe/qt: cannot find package "github.com/therecipe/qt" in any of:
/usr/lib/go/src/github.com/therecipe/qt (from $GOROOT)
/home/dev/docs/projects/testPro/go/src/github.com/therecipe/qt (from $GOPATH)

because currently your GOPATH is set to `/home/dev/docs/projects/testPro/go/`


so maybe try to structure your gopath like this:
```
/home/dev/docs/share/libs/go/
├── bin
│   ├── qtdeploy
│   ├── qtminimal
│   ├── qtmoc
│   ├── qtrcc
│   └── qtsetup
└── src
    ├── github.com
    │   └── therecipe
    │       └── qt
    └── testPro
        ├── main.go
        └── qml
            └── main.qml
```

and then set your GOPATH to: `/home/dev/docs/share/libs/go/`


Alternatively if you don't have anything important in `/home/dev/docs/share/libs/go/` or `/home/dev/docs/projects/testPro/go/` then maybe start from a clean state and remove both folders, unset GOBIN and export the GOPATH to the place where you want it to live and then run `go get -v github.com/therecipe/qt/cmd/...` again.
This will create the basic folder structure for your so you don't need to do it by hand.
Then cd into $GOPATH/src and create an project folder with the following file structure:
```
testPro
├── main.go
└── qml
    └── main.qml
```
or better yet, run 
```
cp -r $GOPATH/src/github.com/therecipe/qt/internal/examples/quick/view testPro
```
 to copy one of the examples.

then run `$GOPATH/bin/qtsetup` and after that `cd $GOPATH/src/testPro && qtdeploy test desktop`

**Comment by richtourist** [comment]
Yes the GOPATH thing is a bit of an issue. I was hoping to have it colon separated:
/path/to/libs/go/src:/path/to/projects/go/src
That way I could have each project in its own git repo. But if the go code is in a different repo then it is more hassle making a commit. But it seems to cause so many problems to go against the flow.

I will definitely try to help with the docs or something. I was so glad when I found this project and thought it might save me from C++ in favor of Go... pure bliss.

**Comment by therecipe** [comment]
> I was hoping to have it colon separated:
/path/to/libs/go/src:/path/to/projects/go/src

you actually can do that, e.g. something like this should work:

```
gopath1
├── bin
├── pkg
└── src
    └── github.com
        └── therecipe
            └── qt
```

```
gopath2
├── bin
├── pkg
└── src
    └── testPro
```

just export `GOPATH=/path/to/gopath1:/path/to/gopath2`

also maybe take a look here: https://golang.org/cmd/go/#hdr-GOPATH_environment_variable

**Comment by richtourist** [comment]
I'm back to square one! All sorts of errors. So I've deleted the two directories I had the bindings and my project in, as you suggested. And I tried reinstalling the bindings as you outlined above... but I got all sorts of errors.
I'm going to give it another go, but do it really methodically. So can I ask some questions as I go, please...

Do I have to do any of the install as root, or will a normal user do?
I'm using Go 2:1.10.3-1, and Qt 5.11.1-2, is that ok?
How do I identify the root directory of my Qt installation, what kind of files would it have in it, my machine has got Qt stuff in several locations.
