### ISSUE TITLE
windows_64 docker SetMarkerShape undefined [bug]

### ISSUE THREAD

**Issue by nntaoli** [therecipe/qt#692]
```
chart.Legend().SetMarkerShape undefined (type *charts.QLegend has no field or method SetMarkerShape)
undefined: charts.QLegend__MarkerShapeCircle

```

**Comment by therecipe** [comment]
Hey

Yeah, this is because 3 of the 4 windows images are still on Qt 5.8 and this function was added in [5.9](https://doc.qt.io/qt-5/qlegend.html#markerShape-prop)
But I'm currently in the process of upgrading all of them to Qt 5.11.1.

Also the `windows_32_static` image should already contain the`SetMarkerShape` function.
And the `windows_32_shared` should be done in a few hours as well.
But the windows 64 images will take at least another day though.

**Comment by therecipe** [comment]
The `windows_32_*` images should work now, as well as the `windows_64_static` image.

**Comment by therecipe** [comment]
Will close this now, since all the recent images should contain Qt 5.12
