### ISSUE TITLE
HELP: How to serialize structs into *core.QVariant

### ISSUE THREAD

**Issue by skaldesh** [therecipe/qt#702]
Hey there, I need some help.
I want to return a struct from one of my slots, so that in QML I have access to multiple return values. Right now, I am using *core.QVariant. But I would prefer, if I could do something like that:
```
type ReturnData struct {
    Str string
    Index int
}
```
and now serialize this automatically to a *core.QVariant, so that I can write in my QML code:
```
var returnData = ctx.someSlotFunc()
// access data like returnData.Str and returnData.Index
```

I tried to get it to work by embedding core.QObject in my struct and register the type, but in QML I then only receive null. How should I go about this?

**Comment by skaldesh** [comment]
@therecipe thanks for the example! What I was missing: I thought I had to either register the type OR the metatype, not both. That may very well be my problem! I will try this as soon as possible, thanks so far!

**Comment by skaldesh** [comment]
@therecipe Hey, I have a follow up question to this! How would you construct the `CustomObject` from QML, to send it back to go?

**Comment by therecipe** [comment]
You just need to register the type with the `QmlRegisterType2` function of your `CustomObject` class.
Maybe take a look at the [advanced/qml_quick/gotemplate](https://github.com/therecipe/examples/tree/master/advanced/qml_quick/gotemplate) example

**Comment by skaldesh** [comment]
Thanks for the link!  
I have a little bit more advanced use case, though.  
```
type Data1 struct {
    _ string `property:"s1"`
    _ []*Data2 `property:"inner"`
}

type Data2 struct {
    _ string `property:"s2"`
}
```

How would I go about sending them from Go -> QML and QML -> Go. I remember reading an old issue here where you explained that a slice of custom objects is somewhat tricky. But I just can not find this issue anymore.

**Comment by therecipe** [comment]
No problem, yeah it's been a while since I worked with qml but iirc sending slices and maps can be done by using `[]*core.QObject, []*core.QVariant or map[string]*core.QVariant`.
These are the blessed types that qml can recogniz as a [slice or map](https://github.com/therecipe/examples/blob/master/advanced/qml_quick/bridge/main.go#L27:L30).

But `[]*Data2` and other custom slices or maps won't be really recognized by qml as slices or maps and instead are handled like a *QVariant I think. So you can pass them through qml, but not really use them from within qml.

Also multidimensional (go) slices and maps are not supported by qml, but you can simulate them by encapsulating QVariants.

However, if you want to send your `[]*Data2` slice to qml, or want to access it from qml whatsoever.
Then you will just need to use `[]*core.QObject` or `[]*core.QVariant` instead.
It's a bit cumbersome, but works for now.
(I can't remember if this custom slices issue is/was a limitation of qml or if I planned to look into it again. Custom enums for example are supported by qml and I planned to add them, but I just can't remember if it was a limitation from qml that custom lists are unsupported. But from skimming through the [docs](http://doc.qt.io/qt-5/qtqml-cppintegration-data.html#conversion-between-qt-and-javascript-types) it seems so.)


The following is a patch for the `gotemplate` example and shows you how to move the`[]*core.QObject` around. (Using `[]*core.QVariant` should work as well, without any changes on the qml side) 

Also btw, it's most of the time better to keep as much of your data as possible in Go-land and just invoke slots or signals from the "dumb" declarative qml code, but that also depends on your use case ...

```diff
diff --git a/advanced/qml_quick/gotemplate/main.go b/advanced/qml_quick/gotemplate/main.go
index b6c68f1..34d5182 100644
--- a/advanced/qml_quick/gotemplate/main.go
+++ b/advanced/qml_quick/gotemplate/main.go
@@ -19,9 +19,10 @@ type ItemTemplate struct {
 
 	_ func() `constructor:"init"`
 
-	_ string `property:"someString"`
+	_ []*core.QObject `property:"someNestedQtObject"`
 
-	_ *QtObjectTemplate `property:"someNestedQtObject"`
+	_ func(objects []*core.QObject) []*core.QObject `slot:"sendToGo,auto"`
+	_ func(objects []*core.QObject)                 `signal:"sendToQml"`
 }
 
 func (t *ItemTemplate) init() {
@@ -30,11 +31,21 @@ func (t *ItemTemplate) init() {
 
 //this is the earliest possible point you can access the initial properties
 func (t *ItemTemplate) componentComplete() {
-	println("from Item:", t.SomeString())
-	println("from Item (QtObject):", t.SomeNestedQtObject().SomeString())
+	//println("from property (QtObject) 0:", NewQtObjectTemplateFromPointer(t.SomeNestedQtObject()[0].Pointer()).SomeString())
+	//println("from property (QtObject) 1:", NewQtObjectTemplateFromPointer(t.SomeNestedQtObject()[1].Pointer()).SomeString())
 	t.ComponentCompleteDefault()
 }
 
+func (t *ItemTemplate) sendToGo(in []*core.QObject) []*core.QObject {
+
+	println("from sendToGo (QtObject) 0:", NewQtObjectTemplateFromPointer(in[0].Pointer()).SomeString())
+	println("from sendToGo (QtObject) 1:", NewQtObjectTemplateFromPointer(in[1].Pointer()).SomeString())
+
+	t.SendToQml(in)
+
+	return in
+}
+
 //same as http://doc.qt.io/qt-5/qml-qtqml-qtobject.html
 type QtObjectTemplate struct {
 	core.QObject
@@ -46,7 +57,7 @@ type QtObjectTemplate struct {
 
 //this is the earliest possible point you can access the initial properties (using a workaround in qml)
 func (t *QtObjectTemplate) componentComplete() {
-	println("from QtObject:", t.SomeString())
+	//println("from QtObject:", t.SomeString())
 }
 
 func main() {
diff --git a/advanced/qml_quick/gotemplate/qml/main.qml b/advanced/qml_quick/gotemplate/qml/main.qml
index c0edbb8..ff8a5c9 100644
--- a/advanced/qml_quick/gotemplate/qml/main.qml
+++ b/advanced/qml_quick/gotemplate/qml/main.qml
@@ -5,13 +5,6 @@ import CustomQmlTypes 1.0		//ItemTemplate and QtObjectTemplate
 ItemTemplate {
 	id: root
 
-	someString: "hello world"
-
-	someNestedQtObject: QtObjectTemplate {
-		someString: root.someString
-		Component.onCompleted: componentComplete()
-	}
-
 	width: 250
 	height: 200
 
@@ -19,4 +12,18 @@ ItemTemplate {
 		anchors.fill: parent
 		text: "look into the console"
 	}
+
+
+	property var objectFactory: function(text) { return Qt.createQmlObject('import QtQuick 2.10; import CustomQmlTypes 1.0; QtObjectTemplate { someString: "'+text+'"; Component.onCompleted: { componentComplete() } }', root) }
+
+	someNestedQtObject: [objectFactory("hello"), objectFactory("world")]
+
+	onSendToQml: {
+		console.log("from sendtoQml:", objects[0].someString, objects[1].someString)
+	}
+
+	Component.onCompleted: {
+		var ret = root.sendToGo(root.someNestedQtObject)
+		console.log("from sendToGo return:", ret[0].someString, ret[1].someString)
+	}
 }
\ No newline at end of file
```
