### ISSUE TITLE
Cannot find the new AddItem2 and AddItem3 methods of QGridLayout

### ISSUE THREAD

**Issue by apocelipes** [therecipe/qt#724]
Hey

I cannot find and use the new AddItem2 and AddItem3 methods of QGridLayout.
These methods have been added to the code, they exist after ```qtsetup upgrade```, but they disappear after running ```qtsetup```, I don't know what happened, can you give me some help?

golang 1.11.1
Qt 5.11.2
GCC 8.2.1

**Comment by therecipe** [comment]
Hey

Ah sorry, yeah the qtsetup re-generates the whole code and all manual changes are lost after each qtsetup run. To preserve them you would need to run something like this:
```
$GOPATH/bin/qtsetup generate && cd $GOPATH/src/github.com/therecipe/qt && git reset --hard && $GOPATH/bin/qtsetup install
```
(or `git checkout -f YOURCOMMIT` instead of the hard reset)


However, I looked into why the addItem functions where missing in the first place and it seems like they were just blacklisted. So I removed them from the blacklist with: https://github.com/therecipe/qt/commit/16b369950c7c1351710151055ec6f57612e5c555#diff-9bbdf1b6f8e66f0a346330f3be71a4d3

and they should be available now as: `AddItem` and `AddItem2`
https://github.com/therecipe/qt/commit/16b369950c7c1351710151055ec6f57612e5c555#diff-3d4bab0cc56efaf31cb0a7106ce088c0

**Comment by apocelipes** [comment]
Thank you.
