### ISSUE TITLE
New docker image for windows?

### ISSUE THREAD

**Issue by akiyosi** [therecipe/qt#725]
I found the following tag in docker-hub with a build status of "Success".

 - windows_32_static_msys2
 - windows_32_shared_msys2
 - windows_64_static_msys2
 - windows_64_shared_msys2

Also, the status of "Windows_64_shared" is "Error" for a long time.
Are these tags a new build image for Windows?

**Comment by therecipe** [comment]
Hey

Yeah, these are some of the new images I worked on.

The `windows_32_static_msys2`, `windows_32_shared_msys2`, `windows_64_static_msys2` and `windows_64_shared_msys2` images can be used as an alternative to the normal `windows_*` images, but they don't provide anything new and compiling with them takes longer, because they need to make use of wine. The main use case of these images is to test the binding itself, and they also lack the webengine and webview module. So you can use them, but there is no real benefit over the normal `windows_*` images atm.

The `windows_32_shared_56`, `windows_32_shared_xp`, `windows_32_shared_59` and `windows_32_shared_wine` images can be used as an alternative for the `windows_32_shared` image and were created to mainly provide backward compatible images against Qt 5.6.x and 5.9.x.
The `*_xp` image can also be used to create applications for windows xp, it contains Qt 5.6.x and Go 1.10.x
The `*_wine` image will always contain the latest official Qt version and can be used to work around the issue with QML application on virtual machines: https://github.com/therecipe/qt/issues/720

The `linux_56` and `linux_59` images are not yet available, but they can be used for backward compatibility reason as well. The `*_56` image can also be used to work around the styling issue on linux: https://github.com/therecipe/qt/issues/306 

The `linux_arch`, `linux_ubuntu_vivid` and `linux_ubuntu_xenial` images are not yet available, but they will make use of the Qt version provided by the system package manager of the distro and can be used to work around the styling issues and also to create small but non portable distro specific applications.

And the `wasm` image can be used to compile your application to webassembly. But it's still experimental, and the `js` image which uses gopherjs instead seems to create more performant applications.

And yes, the `windows_64_shared` is currently broken because hub.docker times out during the builds. I will look into this, but if you depend on it then you could build it yourself as well.
Just cd into `qt/internal/docker/windows_64_shared` and build the 7 base images with something like `docker build -f Dockerfile.base_X -t therecipe/qt:windows_64_shared_base_X .`, then once done you can build the target image with `docker build  -t therecipe/qt:windows_64_shared .`

**Comment by akiyosi** [comment]
Thank you for the detailed explanation.
I also understand why windows_64_shared becomes Error.
I will try image generation by docker build :)
