### ISSUE TITLE
qtsetup end on error

### ISSUE THREAD

**Issue by OpoOpo** [therecipe/qt#741]
Hi,
I am trying to setup Qt, but ending on this type of error.
```WARN[0003] failed to install:                           
WARN[0003] core                                         
WARN[0003] androidextras                                
INFO[0003] running: 'qtsetup test linux' [docker=false] [vagrant=false] 
INFO[0003] testing quick/calc                           
ERRO[0004] failed to run command                         _func=RunCmdOptional cmd="/home/opoopo/Qt/5.11.1/gcc_64/bin/qmake -o Mfile ../calc.pro -spec linux-g++ CONFIG+=release" dir=/home/opoopo/go/src/github.com/therecipe/qt/internal/examples/quick/calc env= error="fork/exec /home/opoopo/Qt/5.11.1/gcc_64/bin/qmake: no such file or directory" name="run qmake for linux on linux"

ERRO[0004] failed to load /home/opoopo/go/src/github.com/therecipe/qt/internal/examples/quick/calc/Mfile  error="open /home/opoopo/go/src/github.com/therecipe/qt/internal/examples/quick/calc/Mfile: no such file or directory"
ERRO[0004] failed to run command                         _func=RunCmd cmd="/home/opoopo/Qt/5.11.1/gcc_64/bin/rcc -project -o /home/opoopo/go/src/github.com/therecipe/qt/internal/examples/quick/calc/rcc.qrc" dir=/home/opoopo/go/src/github.com/therecipe/qt/internal/examples/quick/calc/qml env= error="fork/exec /home/opoopo/Qt/5.11.1/gcc_64/bin/rcc: no such file or directory" name="execute rcc *.qrc on linux for linux"
```
Any suggestions ?
Thank you

**Comment by Dorukanyk** [comment]
Hi All

I have also same issue, can you please tell how did you solve this?

Thanks and Best Regards

**Comment by therecipe** [comment]
@Dorukanyk 
Can you post the log or your setup?

Also which command did you run to setup the binding?
```
go get -u -v github.com/therecipe/qt/cmd/... && for /f %v in ('go env GOPATH') do %v\bin\qtsetup test && %v\bin\qtsetup -test=false
```
Does this one work?

**Comment by Dorukanyk** [comment]
Thank you for your interest,

I used first -> go get -u -v github.com/therecipe/qt/cmd/... , 
then used -> C:\Users\DorukanYilmazkulas\go\bin>qtsetup, because I couldn't make the setup work

Here is my qtsetup log files.. , by the way after this setup I try to run some code that I saw on youtube, used "qtdeploy build desktop", it works fine but then it gives "network error", 

time="2019-08-20T18:23:50-07:00" level=info msg="successfully created qtenv.bat symlink in your PATH (c:\\go\\bin\\qtenv.bat)"
time="2019-08-20T18:23:50-07:00" level=info msg="running: 'qtsetup prep'"
time="2019-08-20T18:23:50-07:00" level=info msg="running: 'qtsetup check windows' [docker=false] [vagrant=false]"
time="2019-08-20T18:23:51-07:00" level=info msg="GOOS:                        'windows'"
time="2019-08-20T18:23:51-07:00" level=info msg="GOARCH:                      'amd64'"
time="2019-08-20T18:23:51-07:00" level=info msg="GOVERSION:                   'go1.12.7'"
time="2019-08-20T18:23:51-07:00" level=info msg="GOROOT:                      'c:\\go'"
time="2019-08-20T18:23:51-07:00" level=info msg="GOPATH:                   *  'c:\\go'"
time="2019-08-20T18:23:51-07:00" level=info msg="GOBIN:                       'c:\\go\\bin'"
time="2019-08-20T18:23:51-07:00" level=info msg="GOMOD:                       ''"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_HASH:                     '0b997e8d18a6f416bf646ee24338413c33ba4237'"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_API:                   *  '5.13.0'"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_VERSION:               *  '5.13.0'"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_DIR:                   *  'C:\\Qt'"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_STUB:                  *  'false'"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_DEBUG:                 *  'true'"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_WEBKIT:                   'false'"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_DEBUG_CONSOLE:         *  'true'"
time="2019-08-20T18:23:51-07:00" level=info msg="QT_MSYS2:                    'false'"
time="2019-08-20T18:23:51-07:00" level=info msg="running: 'qtsetup generate windows' [docker=false] [vagrant=false]"
time="2019-08-20T18:23:59-07:00" level=info msg="generating full qt/core"
time="2019-08-20T18:24:10-07:00" level=info msg="generating full qt/androidextras"
time="2019-08-20T18:24:11-07:00" level=info msg="generating full qt/gui"
time="2019-08-20T18:24:24-07:00" level=info msg="generating full qt/network"
time="2019-08-20T18:24:28-07:00" level=info msg="generating full qt/xml"
time="2019-08-20T18:24:29-07:00" level=info msg="generating full qt/dbus"
time="2019-08-20T18:24:30-07:00" level=info msg="generating full qt/nfc"
time="2019-08-20T18:24:31-07:00" level=info msg="generating full qt/script"
time="2019-08-20T18:24:32-07:00" level=info msg="generating full qt/sensors"
time="2019-08-20T18:24:35-07:00" level=info msg="generating full qt/positioning"
time="2019-08-20T18:24:36-07:00" level=info msg="generating full qt/widgets"
time="2019-08-20T18:25:06-07:00" level=info msg="generating full qt/sql"
time="2019-08-20T18:25:08-07:00" level=info msg="generating full qt/qml"
time="2019-08-20T18:25:10-07:00" level=info msg="generating full qt/websockets"
time="2019-08-20T18:25:11-07:00" level=info msg="generating full qt/xmlpatterns"
time="2019-08-20T18:25:12-07:00" level=info msg="generating full qt/bluetooth"
time="2019-08-20T18:25:14-07:00" level=info msg="generating full qt/webchannel"
time="2019-08-20T18:25:14-07:00" level=info msg="generating full qt/svg"
time="2019-08-20T18:25:15-07:00" level=info msg="generating full qt/multimedia"
time="2019-08-20T18:25:27-07:00" level=info msg="generating full qt/quick"
time="2019-08-20T18:25:30-07:00" level=info msg="generating full qt/help"
time="2019-08-20T18:25:33-07:00" level=info msg="generating full qt/location"
time="2019-08-20T18:25:35-07:00" level=info msg="generating full qt/scripttools"
time="2019-08-20T18:25:35-07:00" level=info msg="generating full qt/uitools"
time="2019-08-20T18:25:35-07:00" level=info msg="generating full qt/winextras"
time="2019-08-20T18:25:36-07:00" level=info msg="generating full qt/testlib"
time="2019-08-20T18:25:37-07:00" level=info msg="generating full qt/serialport"
time="2019-08-20T18:25:37-07:00" level=info msg="generating full qt/serialbus"
time="2019-08-20T18:25:38-07:00" level=info msg="generating full qt/printsupport"
time="2019-08-20T18:25:41-07:00" level=info msg="generating full qt/designer"
time="2019-08-20T18:25:44-07:00" level=info msg="generating full qt/scxml"
time="2019-08-20T18:25:45-07:00" level=info msg="generating full qt/gamepad"
time="2019-08-20T18:25:46-07:00" level=info msg="generating full qt/purchasing"
time="2019-08-20T18:25:46-07:00" level=info msg="generating full qt/datavisualization    [GPLv3]"
time="2019-08-20T18:25:50-07:00" level=info msg="generating full qt/charts               [GPLv3]"
time="2019-08-20T18:25:57-07:00" level=info msg="generating full qt/virtualkeyboard      [GPLv3]"
time="2019-08-20T18:25:58-07:00" level=info msg="generating full qt/speech"
time="2019-08-20T18:25:59-07:00" level=info msg="generating full qt/quickcontrols2"
time="2019-08-20T18:25:59-07:00" level=info msg="generating full qt/sailfish"
time="2019-08-20T18:25:59-07:00" level=info msg="generating full qt/remoteobjects"
time="2019-08-20T18:26:00-07:00" level=info msg="running: 'qtsetup install windows' [docker=false] [vagrant=false]"
time="2019-08-20T18:26:00-07:00" level=info msg="installing full qt/core"
time="2019-08-20T18:28:22-07:00" level=info msg="installing full qt/androidextras"
time="2019-08-20T18:28:22-07:00" level=info msg="installing full qt/gui"
time="2019-08-20T18:32:11-07:00" level=info msg="installing full qt/network"
time="2019-08-20T18:32:44-07:00" level=info msg="installing full qt/xml"
time="2019-08-20T18:32:52-07:00" level=info msg="installing full qt/dbus"
time="2019-08-20T18:33:00-07:00" level=info msg="installing full qt/nfc"
time="2019-08-20T18:33:07-07:00" level=info msg="installing full qt/script"
time="2019-08-20T18:33:13-07:00" level=info msg="installing full qt/sensors"
time="2019-08-20T18:33:26-07:00" level=info msg="installing full qt/positioning"
time="2019-08-20T18:33:34-07:00" level=info msg="installing full qt/widgets"
time="2019-08-20T18:41:13-07:00" level=info msg="installing full qt/sql"
time="2019-08-20T18:41:25-07:00" level=info msg="installing full qt/qml"
time="2019-08-20T18:41:36-07:00" level=info msg="installing full qt/websockets"
time="2019-08-20T18:41:42-07:00" level=info msg="installing full qt/xmlpatterns"
time="2019-08-20T18:41:48-07:00" level=info msg="installing full qt/bluetooth"
time="2019-08-20T18:42:02-07:00" level=info msg="installing full qt/webchannel"
time="2019-08-20T18:42:07-07:00" level=info msg="installing full qt/svg"
time="2019-08-20T18:42:13-07:00" level=info msg="installing full qt/multimedia"
time="2019-08-20T18:43:37-07:00" level=info msg="installing full qt/quick"
time="2019-08-20T18:44:00-07:00" level=info msg="installing full qt/help"
time="2019-08-20T18:44:19-07:00" level=info msg="installing full qt/location"
time="2019-08-20T18:44:28-07:00" level=info msg="installing full qt/scripttools"
time="2019-08-20T18:44:31-07:00" level=info msg="installing full qt/uitools"
time="2019-08-20T18:44:35-07:00" level=info msg="installing full qt/winextras"
time="2019-08-20T18:44:42-07:00" level=info msg="installing full qt/testlib"
time="2019-08-20T18:44:47-07:00" level=info msg="installing full qt/serialport"
time="2019-08-20T18:44:52-07:00" level=info msg="installing full qt/serialbus"
time="2019-08-20T18:45:00-07:00" level=info msg="installing full qt/printsupport"
time="2019-08-20T18:45:11-07:00" level=info msg="installing full qt/designer"
time="2019-08-20T18:45:30-07:00" level=info msg="installing full qt/scxml"
time="2019-08-20T18:45:37-07:00" level=info msg="installing full qt/gamepad"
time="2019-08-20T18:45:43-07:00" level=info msg="installing full qt/purchasing"
time="2019-08-20T18:45:48-07:00" level=info msg="installing full qt/datavisualization    [GPLv3]"
time="2019-08-20T18:46:18-07:00" level=info msg="installing full qt/charts               [GPLv3]"
time="2019-08-20T18:47:16-07:00" level=info msg="installing full qt/virtualkeyboard      [GPLv3]"
time="2019-08-20T18:47:26-07:00" level=info msg="installing full qt/speech"
time="2019-08-20T18:47:31-07:00" level=info msg="installing full qt/quickcontrols2"
time="2019-08-20T18:47:33-07:00" level=info msg="installing full qt/sailfish"
time="2019-08-20T18:47:34-07:00" level=info msg="installing full qt/remoteobjects"
time="2019-08-20T18:47:41-07:00" level=info msg="running: 'qtsetup test windows' [docker=false] [vagrant=false]"
time="2019-08-20T18:47:41-07:00" level=info msg="testing showcases\\wallet"
time="2019-08-20T18:47:41-07:00" level=error msg="failed to run command" _func=RunCmd cmd="go mod vendor" dir="showcases\\wallet" env= error="chdir showcases\\wallet: The system cannot find the path specified." name="go mod vendor"

------------------------
Here is my qtsetup test log files

time="2019-08-20T19:24:51-07:00" level=info msg="running: 'qtsetup test windows' [docker=false] [vagrant=false]"
time="2019-08-20T19:24:51-07:00" level=info msg="testing qml\\gallery"
time="2019-08-20T19:25:12-07:00" level=info msg="testing quick\\calc"
time="2019-08-20T19:25:35-07:00" level=info msg="testing widgets\\textedit"
time="2019-08-20T19:26:24-07:00" level=error msg="failed to run command" _func=RunCmd cmd="go build -p 12 -v -ldflags=all=\"-s\" \"-w\" -o c:\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\widgets\\textedit\\deploy\\windows\\textedit.exe -tags=\"minimal\"" dir="c:\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\widgets\\textedit" env="QT_MAKE_DIR=c:\\qt\\5.13.0\\mingw73_32\\bin USERNAME=DorukanYilmazkulas windir=C:\\WINDOWS GTK_BASEPATH=C:\\Program Files (x86)\\GtkSharp\\2.12\\ PROMPT=$P$G GOPATH=C:\\Users\\DorukanYilmazkulas\\go NUMBER_OF_PROCESSORS=12 CommonProgramFiles=C:\\Program Files\\Common Files ComSpec=C:\\WINDOWS\\system32\\cmd.exe QT_VERSION=5.13.0 CGO_ENABLED=1 =C:=C:\\Users\\DorukanYilmazkulas\\go\\bin CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files PROCESSOR_ARCHITECTURE=AMD64 SystemRoot=C:\\WINDOWS USERPROFILE=C:\\Users\\DorukanYilmazkulas TEMP=C:\\Users\\DORUKA~1\\AppData\\Local\\Temp ALLUSERSPROFILE=C:\\ProgramData PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules SystemDrive=C: VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\ PATH=C:\\Qt\\Tools\\mingw730_64\\bin;C:\\Qt\\5.13.0\\mingw73_64\\bin;C:/Qt/Tools/mingw730_64\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Microsoft MPI\\Bin\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\GtkSharp\\2.12\\bin;C:\\Go\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\mingw-w64\\x86_64-6.3.0-win32-seh-rt_v5-rev1\\mingw64\\x86_64-w64-mingw32\\bin;C:\\Program Files\\mingw-w64\\x86_64-6.3.0-win32-seh-rt_v5-rev1\\mingw64\\bin;C:\\MinGW\\bin;C:\\Users\\DorukanYilmazkulas\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\DorukanYilmazkulas\\go\\bin;C:\\Program Files\\JetBrains\\GoLand 2019.1\\bin;C:\\Users\\DorukanYilmazkulas\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\DorukanYilmazkulas\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\DorukanYilmazkulas\\.dotnet\\tools;C:\\Users\\DorukanYilmazkulas\\go\\bin;C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin HOMEDRIVE=C: QT_DEBUG=true QT_STUB=false GOFLAGS=-mod=vendor ChocolateyLastPathUpdate=132088938543291957 ProgramW6432=C:\\Program Files GO111MODULE=off APPDATA=C:\\Users\\DorukanYilmazkulas\\AppData\\Roaming COMPUTERNAME=LAPTOP-DORUKAN PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel ProgramData=C:\\ProgramData GOOS=windows PROCESSOR_REVISION=9e0a GoLand=C:\\Program Files\\JetBrains\\GoLand 2019.1\\bin; LOGONSERVER=\\\\LAPTOP-DORUKAN MSMPI_BIN=C:\\Program Files\\Microsoft MPI\\Bin\\ Path=C:\\Qt\\5.13.0\\mingw73_64\\bin;C:/Qt/Tools/mingw730_64\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Microsoft MPI\\Bin\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\GtkSharp\\2.12\\bin;C:\\Go\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\mingw-w64\\x86_64-6.3.0-win32-seh-rt_v5-rev1\\mingw64\\x86_64-w64-mingw32\\bin;C:\\Program Files\\mingw-w64\\x86_64-6.3.0-win32-seh-rt_v5-rev1\\mingw64\\bin;C:\\MinGW\\bin;C:\\Users\\DorukanYilmazkulas\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\DorukanYilmazkulas\\go\\bin;C:\\Program Files\\JetBrains\\GoLand 2019.1\\bin;C:\\Users\\DorukanYilmazkulas\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\DorukanYilmazkulas\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\DorukanYilmazkulas\\.dotnet\\tools;C:\\Users\\DorukanYilmazkulas\\go\\bin;C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin USERDOMAIN_ROAMINGPROFILE=AzureAD GOROOT=c:\\go configsetroot=C:\\WINDOWS\\ConfigSetRoot HOMEPATH=\\Users\\DorukanYilmazkulas USERDOMAIN=AzureAD QT_DEBUG_CONSOLE=true TMP=C:\\Users\\DORUKA~1\\AppData\\Local\\Temp QT_API=5.13.0 PUBLIC=C:\\Users\\Public OneDriveCommercial=C:\\Users\\DorukanYilmazkulas\\OneDrive - Gold Coin Studios ProgramFiles=C:\\Program Files OneDrive=C:\\Users\\DorukanYilmazkulas\\OneDrive - Gold Coin Studios PROCESSOR_LEVEL=6 QT_DIR=C:\\Qt CommonProgramW6432=C:\\Program Files\\Common Files DriverData=C:\\Windows\\System32\\Drivers\\DriverData OS=Windows_NT ProgramFiles(x86)=C:\\Program Files (x86) GOARCH=amd64 LOCALAPPDATA=C:\\Users\\DorukanYilmazkulas\\AppData\\Local" error="exit status 2" name="build for windows on windows"
github.com/therecipe/qt/internal/examples/vendor/github.com/therecipe/qt/core
github.com/therecipe/qt/internal/examples/vendor/github.com/therecipe/qt/gui
github.com/therecipe/qt/internal/examples/vendor/github.com/therecipe/qt/widgets
# github.com/therecipe/qt/internal/examples/vendor/github.com/therecipe/qt/widgets
widgets-minimal.cpp: In function 'void* QDesktopWidget_AvailableGeometry(void*, int)':
widgets-minimal.cpp:1509:88: warning: 'const QRect QDesktopWidget::availableGeometry(int) const' is deprecated: Use QGuiApplication::screens() [-Wdeprecated-declarations]
  return ({ QRect tmpValue = static_cast<QDesktopWidget*>(ptr)->availableGeometry(screen); new QRect(tmpValue.x(), tmpValue.y(), tmpValue.width(), tmpValue.height()); });
                                                                                        ^
In file included from C:/Qt/5.13.0/mingw73_64/include/QtWidgets/QDesktopWidget:1:0,
                 from widgets-minimal.cpp:21:
C:/Qt/5.13.0/mingw73_64/include/QtWidgets/qdesktopwidget.h:88:67: note: declared here
     QT_DEPRECATED_X("Use QGuiApplication::screens()") const QRect availableGeometry(int screen = -1) const;
                                                                   ^~~~~~~~~~~~~~~~~
github.com/therecipe/qt/internal/examples/vendor/github.com/therecipe/qt/printsupport
github.com/therecipe/qt/internal/examples/widgets/textedit
# github.com/therecipe/qt/internal/examples/widgets/textedit
.\textedit.go:55:13: undefined: NewTextEdit

**Comment by therecipe** [comment]
No problem, you are welcome.
I looked into this and it could be that https://github.com/therecipe/qt/commit/9e361992b5ed846ce9d71389aa59de522b39c48d#diff-70e9f4fa56e04a0853961938905c5d08 fixes this.
But I wasn't able to reproduce it yet, so I'm not fully sure.

**Comment by Dorukanyk** [comment]
Thank you so much, I will try it today and let you know.
