### ISSUE TITLE
Possible memory leak in QNetworkReply::readData() wrapper

### ISSUE THREAD

**Issue by hitchfred** [therecipe/qt#749]
Hi,

I've been experimenting using a custom QNetworkAccessManager and QNetworkReply to funnel large amounts of data from a Go backend to a QML frontend. I'm happy with the results, but there seems to be an issue with a memory leak somewhere. Valgrind points to callbackQNetworkReply_ReadData as a possible culprit:

```c
//export callbackQNetworkReply_ReadData
func callbackQNetworkReply_ReadData(ptr unsafe.Pointer, data C.struct_QtNetwork_PackedString, maxSize C.longlong) C.longlong {
        if signal := qt.GetSignal(ptr, "readData"); signal != nil {
                retS := cGoUnpackString(data)
                ret := C.longlong(signal.(func(*string, int64) int64)(&retS, int64(maxSize)))
                if ret > 0 {
                        C.memcpy(unsafe.Pointer(data.data), unsafe.Pointer(C.CString(retS)), C.size_t(ret))
                }
                return ret
        }
        retS := cGoUnpackString(data)
        ret := C.longlong(NewQNetworkReplyFromPointer(ptr).ReadDataDefault(&retS, int64(maxSize)))
        if ret > 0 {
                C.memcpy(unsafe.Pointer(data.data), unsafe.Pointer(C.CString(retS)), C.size_t(ret))
        }
        return ret
}
```

At a glance, the pointer returned from C.CString() there in the memcpy() isn't being freed. C.CString() mallocs from the C heap, so there needs to be a call to free() somewhere.

**Comment by therecipe** [comment]
Hey

Yes, you are right this should be fixed now with: https://github.com/therecipe/qt/commit/5251d3454c7c3600980c6791ebbbdee664b56156#diff-24ce41f044a5d947051b85bb10734d91
I will also try to get rid of `memcpy` by implementing `cGoUnpackString` differently in the future.

Also a small heads up, I will make some breaking changes for some functions to accept an `[]byte` instead of an `string` or `*string` in the future and I think `readData` will be affected as well.

**Comment by hitchfred** [comment]
It's working better now after your patch. Thanks
