### ISSUE TITLE
Sending objects to QML

### ISSUE THREAD

**Issue by chuckwagoncomputing** [therecipe/qt#757]
How do I send an object to QML? I have been trying JSON, without success.
Here is my code, in the data() function of a QAbstractListModel:
```
b := []byte("{\"FormattedName\":\"Foo Bar\"}")
fmt.Println("foo: ", string(b))
f := core.QJsonDocument_FromRawData(b, len(b), 0).Object()
fmt.Println("bar: ", f.Keys())
return core.NewQVariant44(f)
```
And this is what I get:
```
foo:  {"FormattedName":"Foo Bar"}
bar:  []
```
If I print the value from QML, it is also empty.

**Comment by therecipe** [comment]
Hey

The `fromRawData` function only accepts your data in a special binary format that is internally used in Qt: http://doc.qt.io/qt-5/qjsondocument.html#toBinaryData

This should work instead
```go
b := []byte("{\"FormattedName\":\"Foo Bar\"}")
fmt.Println("foo: ", string(b))
f := core.QJsonDocument_FromJson(core.NewQByteArray2(string(b), len(b)), nil).Object()
fmt.Println("bar: ", f.Keys())
return core.NewQVariant44(f)
```

However, you can probably also just directly return a QVariant created with `core.NewQVariant14(string(b))`, and then directly access the fields in QML with something like:
`myObject["FormattedName"] or myObject.FormattedName` (haven't tested that though)

Also since you asked about sending "Objects", you can also directly convert any QObject derived object to QVariant with `ToVariant()`, and then if the object has properties declared access these properties by their name (`myObject.myProperty`) from QML

**Comment by chuckwagoncomputing** [comment]
Thanks, that solution works.
`core.NewQVariant14(string(b))` makes it a QString, so accessing the fields as you said does not work. I suppose you could use JSON.parse() in the QML and use the returned object.
For my use case it is much easier to do the parsing on the Go side, and pass the object.
