### ISSUE TITLE
missing app.sh when building on Linux?

### ISSUE THREAD

**Issue by quantonganh** [therecipe/qt#770]
https://github.com/therecipe/qt/blob/39753cb4ef7c691bbc16c3ce73b2b64a8fa808ea/internal/cmd/deploy/bundle.go#L106

What if we are on Linux and `name != "lib"`?

**Comment by therecipe** [comment]
Hey

I made some changes that removed the need for the helper scripts

I just haven't had time to test it for the raspberry targets, that's why ` target != "linux"` is still there.
`name == "lib"` on the other side was just for a workaround where problems arised if you would call your project `lib`. But this is solved now by appending an `_project` suffix to the executable name https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/deploy.go#L20-L26

I will completly remove the `*.sh` related code with the next cleanup

**Comment by quantonganh** [comment]
If I use the full path:

```
/path/to/client: error while loading shared libraries: libQt5Designer.so.5: cannot open shared object file: No such file or directory
```

But if I `cd` into `dirname` first, it can be run:

```
cd /path/to/dirname
./client
```

**Comment by therecipe** [comment]
Oh, sorry
It should be fixed now with https://github.com/therecipe/qt/commit/df49a978e816acb9b47f2cf0a6cee8e5eb0d5efb#diff-1630b82908dbc9a3aae774d5e2f6afa8R645

**Comment by quantonganh** [comment]
Thanks,

I confirmed that we can use the full path to run the application now.
