### ISSUE TITLE
Video Widget

### ISSUE THREAD

**Issue by 5k3105** [therecipe/qt#8]
Can anyone give an example of using the media player / video widget? I'm having trouble translating the Qt 5.5 examples.. Thanks. 

(btw, maybe there should be a forum or google group?)

**Comment by therecipe** [comment]
Hey
Are your referring to this example?
http://doc.qt.io/qt-5/qtmultimediawidgets-videowidget-example.html

Unfortunately, the binding is currently missing 1 or 2 methods/functions to get it fully working.
One of these methods is 'QMediaPlayer::setVideoOutput'.

It's currently not supported because Go isn't supporting circle dependencies.
In this case the circle is:
QMediaPlayer in "multimedia" -> QVideoWidget in "multimediawidgets" -> something else in "multimedia"

I will add the missing methods, either by breaking the circle with some weak links or merging both packages/modules.

You could create a video player with the help of qml through. (But communicating with qml is currently also a bit tricky...) 
http://doc.qt.io/qt-5/qml-qtmultimedia-mediaplayer.html#details

I'm trying to add the missing methods asap (for "multimediawidgets" aswell as for easier communication with qml), but I'm currently working on a whole different edge, to create automated bindings for android libraries with the help of "androidextras".

Yes, there could be a group or forum or such, but I'm currently just letting the project evolve, maybe if there is a bigger demand for a group or forum.

**Comment by therecipe** [comment]
Hey

I added a new [video_player](https://github.com/therecipe/qt/blob/master/internal/examples/widgets/video_player/video_player.go) example.

And I'm closing this now.

**Comment by 5k3105** [comment]
Hi. Thank you for working on this :)

	C:\Users\5k3105\goworksp\src\github.com\therecipe\qt (master)
	λ setup.bat

	go run ./internal/setup/check.go

	if 0 NEQ 0 exit /b 0

	go run C:\Users\5k3105\goworksp/src/github.com/therecipe/qt/internal/setup/generate.go
	________________________Generate________________________
	core                     funcs:  4037 (-  981)   17s
	androidextras            funcs:    43 (-    3)   0
	gui                      funcs: 18704 (-  866)   16s
	network                  funcs:   607 (-  267)   3s
	sql                      funcs:   294 (-   71)   1s
	xml                      funcs:   323 (-  117)   1s
	dbus                     funcs:   175 (-   81)   1s
	nfc                      funcs:   111 (-   37)   0
	script                   funcs:   209 (-   37)   0
	sensors                  funcs:   254 (-   11)   1s
	positioning              funcs:   179 (-   69)   0
	widgets                  funcs:  5091 (-  431)   48s
	qml                      funcs:   281 (-   37)   1s
	websockets               funcs:    71 (-   27)   0
	xmlpatterns              funcs:   162 (-   50)   0
	bluetooth                funcs:   207 (-  100)   1s
	webchannel               funcs:    13 (-    2)   0
	svg                      funcs:    60 (-    5)   0
	multimedia               funcs:  1114 (-  201)   8s
	quick                    funcs:   454 (-   70)   2s
	help                     funcs:    91 (-   10)   0
	location                 funcs:   549 (-   41)   0
	scripttools              funcs:    14 (-    0)   0
	multimediawidgets        funcs:    59 (-    5)   0

	if 0 NEQ 0 exit /b 0

	go run C:\Users\5k3105\goworksp/src/github.com/therecipe/qt/internal/setup/install.go
	________________________Install-desktop________________________
	core                                    3m7s
	androidextras                           4s
	gui                                     2m56s
	network                                 36s
	sql                                     14s
	xml                                     25s
	dbus                                    14s
	nfc                                     10s
	script                                  11s
	sensors                                 38s
	positioning                             11s
	widgets                                 6m1s
	qml                                     40s
	websockets                              8s
	xmlpatterns                             13s
	bluetooth                               16s
	webchannel                              4s
	svg                                     11s
	multimedia                              1m31s
	quick                                   33s
	help                                    13s
	location                                19s
	scripttools                             5s
	multimediawidgets                       9s

	if 0 NEQ 0 exit /b 0

	go run C:\Users\5k3105\goworksp/src/github.com/therecipe/qt/internal/setup/test.go
	_________________________Test-desktop__________________________
	widgets/line_edits                      42s
	widgets/video_player                    45s
	quick/calc                              45s
	quick/dialog                            51s
	quick/view                              47s
	qml/application                         21s
	qml/prop                                11s


Attempting to run example from command line I get an error window:
    video_player.exe - Entry Point Not Found

	The procedure entry point _gxxpersonality_v0 could not be located in the dynamic link library libstdc++-6.dll.

Attempting to build:
    C:\Users\5k3105\goworksp\src\github.com\therecipe\qt\internal\examples\widgets\video_player (master)
	λ qtdeploy build desktop vplayer


	build
	output:# github.com/therecipe/qt/internal/examples/widgets/video_player/vplayer
	runtime.main: call to external function main.main
	runtime.main: main.main: not defined
	runtime.main: undefined: main.main

	error:exit status 2


	warning: LF will be replaced by CRLF in androidextras/androidextras_android.cpp.
	The file will have its original line endings in your working directory.
	warning: LF will be replaced by CRLF in androidextras/androidextras_android.go.
	The file will have its original line endings in your working directory.
	warning: LF will be replaced by CRLF in androidextras/androidextras_android.h.
	The file will have its original line endings in your working directory.
	C:\Users\5k3105\goworksp\src\github.com\therecipe\qt\internal\examples\widgets\video_player (master)
	λ

I feel like I'm doing multiple things wrong because I get the same "main.main" error running the qtExample.

**Comment by therecipe** [comment]
Hey

It seems like there are 2 different issues.
___
The **first** is the `missing entry point _gxxpersonality_v0`, which is probably the same as [this](https://github.com/therecipe/qt/issues/3).

So you probably got a (wrong/different) `libstdc++-6.dll` somewhere in your `PATH`, maybe due a visual studio installation?
You can install http://www.dependencywalker.com, to figure out which one is used.
(It should use the `libstdc++-6.dll` which is in the same directory as your *.exe)
___
The **second** issue is, due a wrong use of `qtdeploy`.
I assume you did run the following commands?
```
cd %GOPATH%/src/github.com/therecipe/qt/internal/examples/widgets/video_player
qtdeploy build desktop vplayer
```
Which should result in this:
```
build
output:# github.com/therecipe/qt/internal/examples/widgets/video_player/vplayer
runtime.main: call to external function main.main
runtime.main: main.main: not defined
runtime.main: undefined: main.main

error:exit status 2
```

This is because qtdeploy tries to find *.go files in the `github.com/therecipe/qt/internal/examples/widgets/video_player/vplayer/` directory (wich doesn't exists)

Here are a few commands, that should work:

```
cd %GOPATH%/src/github.com/therecipe/qt/internal/examples/widgets/video_player

qtdeploy build desktop

or

qtdeploy build desktop .

or

qtdeploy
```

or

```
cd %GOPATH%/src/github.com/therecipe/qt/internal/examples/widgets

qtdeploy build desktop video_player

or

qtdeploy build desktop ./video_player
```

The last argument should be a relative or absolute path to your project folder (If no path is provided, qtdeploy will use the current dir).

Sorry, I didn't wrote a proper documentation for `qtdeploy` yet. (I will add one later)

Hope, this works for you :)

**Comment by 5k3105** [comment]
Thank you for your help.

I moved mingw ahead in the PATH and ran setup.bat again and it now works.

However, it seems only to play WMV files. I only have experience with the old phonon media player. Since the status bar reported "Error:" but nothing in the error message, I'm attempting to find the mimetypes the player recognizes like this:

	func handleError(_ multimedia.QMediaPlayer__Error) {
		playButton.SetEnabled(false)
		var q = mediaPlayer.QMediaPlayer_PTR()
		var g = multimedia.NewQMediaServiceSupportedFormatsInterfaceFromPointer(q)
		var s = g.SupportedMimeTypes()
		
		errorLabel.SetText("Error: " + strings.Join(s, ","))

	}

and:

	output:# github.com/therecipe/qt/internal/examples/widgets/video_player
	.\video_player.go:130: cannot use q (type *multimedia.QMediaPlayer) as type unsafe.Pointer in argument to multimedia.NewQMediaServiceSupportedFormatsInterfaceFromPointer

	error:exit status 2

**Comment by therecipe** [comment]
Hey

It seems like on windows, the QMediaPlayer requires you to install additional codecs.
https://forum.qt.io/topic/57675/which-file-formats-or-codecs-does-qmediaplayer-support

These videos work for me: http://www.sample-videos.com, on an almost fresh windows 10 install after installing the [Basic K-Lite Codec Pack](http://www.codecguide.com/download_k-lite_codec_pack_basic.htm)

I edited the example to test which mime-types are currently supported (but not if the needed codecs are installed), so you need to pull/clone the repo again.

And a side note, `New*FromPointer()` and `*.Pointer()` are extremely rarely needed and allow you to work with the raw c-pointers.

**Comment by 5k3105** [comment]
That worked great  -  Thank you!
