### ISSUE TITLE
Android Target is not Generated

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#80]
I'm following documentation and here https://github.com/therecipe/qt/blob/master/README.md#android-1 step `6`.

I noticed that `generate.go` do nothing: https://github.com/therecipe/qt/blob/master/internal/setup/generate.go#L15 because at this point `os.Args` len is `2`.

which is probably the reason why this fail:

```
------------------------test----------------------------
Do not create symlink: not root
widgets/line_edits

test.widgets/line_edits
output:

build_1
output:# github.com/therecipe/qt/core
../../../../core/core-minimal.cpp:9:30: fatal error: QAbstractAnimation: No such file or directory
 #include <QAbstractAnimation>
                              ^
compilation terminated.

error:exit status 2


error:exit status 1

exit status 1
```

**Comment by therecipe** [comment]
Yes, the initial idea was that you run the `setup.sh` for desktop development (to get the cgo* files) and then `setup.sh android` some time later for android development (which just builds the examples with qtdeploy).

But if now `setup.sh android` would re-generate the binding (and cgo* files), then you would also have to install the binding for desktop development again with `setup/install.go` to get go-code auto-completion.

I planned to check the `cgo*` files for the current environmental paths like: utils.QT_DIR() and utils.QT_ANDROID_NDK() to decide whether they would have to be regenerated (and installed) or not. But I didn't had time for that yet.

Also now, because the `cgo*` files are removed from the repo by default we could simply check if they exists and then generate (and maybe also install) them if needed.
That would make the installation process for non desktop targets easier.

**Comment by bclermont** [comment]
Maybe you can clean those files after `go install` convert C++/Go into binaries?
Those files won't be required all the time and let go just use the binaries

But... in mean time, if I want to build something for Android, how can I do that?

**Comment by therecipe** [comment]
Yes, I'm currently working on stub source code which hopefully can be used along with binary-only packages. This was intentionally started to be used on machines with fewer ram and for the docker images https://github.com/therecipe/qt/issues/78#issuecomment-255889074.

If you want to build something for android, you currently need to:

1. Install Qt + everything needed for a normal desktop installation
2. Install the Java DevKit (JDK)
3. Install the Android SDK (+ the dependencies needed with the /android-sdk/tools/android application)
4. Install the Android NDK
5. Export env variables if needed ((QT_DIR), JDK_DIR, ANDROID_SDK, ANDROID_NDK)
6. Run `setup.sh && setup.sh android`
7. Deploy applications with `qtdeploy build android path/to/project`

There will be also a

**Comment by bclermont** [comment]
I could build and deploy on Android

**Comment by therecipe** [comment]
qtdeploy now always builds a second set of cgo_* files which then will be used during the deployment.

That allows you to change all the environment variables without the need to re-run the setup.
And also solves the problem you had while setting up the android target.
Because it's now not required anymore to run the desktop setup before running the android setup.
