### ISSUE TITLE
ConnectResizeEvent doesn't seem to work

### ISSUE THREAD

**Issue by krispyk84** [therecipe/qt#834]
Hi,

I'm trying to write an app that has a QTableView in it that should have different sized column headers (right now, they are uniform across). 

To do this, I need to set the column widths and then make sure the proportion stays on window resizing. I'm trying to attach a listener to my code for window resizing, but it never fires! I can't, for the life of me, figure out what's wrong with it. 

Here's my code:

```
package views

import ...

var tableView *widgets.QTableView

func InitBookTable(mainWindow *widgets.QMainWindow, tableViewName string) (*widgets.QTableView, *models.BookModel) {
	tableView = widgets.NewQTableViewFromPointer(mainWindow.FindChild(tableViewName, core.Qt__FindChildrenRecursively).Pointer())

	model := models.NewBookModel(nil)

	mainWindow.ConnectResizeEvent(func(event *gui.QResizeEvent) {
		fmt.Println("resize event was called")
		tableView.SetColumnWidth(0, 77)
		mainWindow.ResizeEvent(event)
	})

	//Hides row index on left column
	tableView.VerticalHeader().SetVisible(false)

	tableView.SetModel(model)
	return tableView, model
}
```

This initializer function definitely gets called, and the ConnectResizeEvent function on mainwindow gets called. The code inside however never gets called when I resize the window. Anything I might be missing or doing wrong? Thanks!

**Comment by therecipe** [comment]
Hey

How did you create the mainWindow?
Did you create it using widgets.NewQMainWindow()?
It looks like you are using *.ui files or something, that's why I'm asking.

If you did create the window inside some *.ui file, then maybe try to use a filterObject
```go
filter := core.NewQObject(nil)
filter.ConnectEventFilter(func(watched *core.QObject, event *core.QEvent) bool {
	if watched.Pointer() == mainWindow.Pointer() {
		if event.Type() == core.QEvent__Resize {
			tableview.SetColumnWidth(0, mainWindow.Width()/3)
		}
	}
	return filter.EventFilterDefault(watched, event)
})
mainWindow.InstallEventFilter(filter)
```

because the resizeEvent is just a plain virtual function https://doc.qt.io/qt-5/qwidget.html#resizeEvent
which can't be connected/intercepted at runtime if it wasn't created with widgets.NewQMainWindow() in the first place.


If not, then maybe try to use `mainWindow.ResizeEventDefault(event)` inside your ConnectResizeFunction instead, otherwise the resizeEvent will fall into endless recursion.

And btw, you can also use something like this:
```go
tableview.HorizontalHeader().SetSectionResizeMode(widgets.QHeaderView__Stretch)
```
if you just want to have your columns sized equally.

**Comment by krispyk84** [comment]
That's exactly it! I was using a *.ui file. Thank you so much. And thanks once again for the great binding!
