### ISSUE TITLE
BackgroundRole & BackgroundColorRole seem to not work

### ISSUE THREAD

**Issue by krispyk84** [therecipe/qt#837]
Hi,

I'm trying to set the background colour of a cell in a QTableView using QVariants, and it doesn't seem to work. ForegrondRole and FontRole work just fine, but BackgroundRole (or BackgroundColorRole) do not. I'm attempting this in the model's data function. Here's my code:

```
func (model *BookModel) data(index *core.QModelIndex, role int) *core.QVariant {
	switch (core.Qt__ItemDataRole(role)) {
	case core.Qt__ForegroundRole:
		if index.Column() == 0 || index.Column() == 1 || index.Column() == 2 || index.Column() == 3 {
			color := gui.NewQBrush3(gui.QColor_FromRgb2(211,0, 0, 255), core.Qt__BrushStyle(0))
			return color.ToVariant()
		} else {
			color := gui.NewQBrush3(gui.QColor_FromRgb2(22,191, 0, 255), core.Qt__BrushStyle(0))
			return color.ToVariant()
		}
	case core.Qt__BackgroundRole:
		if index.Column() == 2 && index.Row() == 2 {
			color := gui.NewQBrush3(gui.QColor_FromRgb2(0,211,0,255), core.Qt__BrushStyle(0))
			return color.ToVariant()
		}
	case core.Qt__FontRole:
		if index.Column() == 2 {
			font := gui.NewQFont()
			font.SetBold(true)
			return font.ToVariant()
		}
	}

	return core.NewQVariant()
}
```

Any idea why ForegroundRole and FontRole work just fine but BackgroundRole does not?

Thank you!

**Comment by therecipe** [comment]
Hey

I think you are just using a wrong [brush style](https://doc.qt.io/qt-5/qt.html#BrushStyle-enum).
Try to use `core.Qt__SolidPattern` instead. `core.Qt__BrushStyle(0)` is basically `core.Qt__NoBrush` which makes the painter ignore the brush.
It's probably working for the ForegroundRole, because there the painter is ignoring the brush style.
At least using a different style had no effect for me, that's probably because fonts are handled differently.

**Comment by krispyk84** [comment]
That's exactly it! Thanks again! You're awesome.
