### ISSUE TITLE
Creating a message box from goroutines

### ISSUE THREAD

**Issue by tapir** [therecipe/qt#841]
Is there a way to achieve this? Currently when I try to do it I get this error and sometimes a crash

```
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
```

**Comment by therecipe** [comment]
Hey

Yeah the problem is that all visual changes will need to be done on the main thread.
Otherwise you will run into these thread issues.

For this to work you will need to create a signal or slot, to be able to call functions on the main thread from a go routine.

Maybe take a look here
https://doc.qt.io/qt-5/signalsandslots.html
and
https://github.com/therecipe/qt/wiki/Available-Tools#qtmoc

But basically you only need to create some moc struct with a helper function and use that function to wrap all the calls you want to have run on the main thread.
There are also some other use cases for these moc structs, but to make it possible to simply "cross" threads will the help of signals/slots is probably the most important one.

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

type mainThreadHelper struct {
	core.QObject

	_ func(f func()) `signal:"runOnMain,auto`
}

func (*mainThreadHelper) runOnMain(f func()) { f() }

var MainThreadRunner = NewMainThreadHelper(nil)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	println("main thread:", core.QThread_CurrentThread().Pointer())

	go func() { println("some other thread:", core.QThread_CurrentThread().Pointer()) }()

	go MainThreadRunner.RunOnMain(func() {
		println("again on main thread:", core.QThread_CurrentThread().Pointer())

		widgets.QMessageBox_Information(nil, "OK", "Hello from main thread", widgets.QMessageBox__Ok, widgets.QMessageBox__Ok)
	})

	widgets.QApplication_Exec()
}
```

To test this example, use either `qtdeploy` or use `qtmoc && go build`
