### ISSUE TITLE
How to use third-party Qt libraries, like QZXing?

### ISSUE THREAD

**Issue by eliezedeck** [therecipe/qt#848]
Hi,

I'd like to use third-party Qt libraries, namely `QZXing`. A sample `*.pri` file is at https://github.com/ftylitak/qzxing/blob/master/src/QZXing.pri

And while at it, what's the easiest way to re-use one's old C++ Qt-based libraries with your new Golang+Qt app? These two are closely related I suppose.

How does one use libraries like these?

Thanks.

**Comment by therecipe** [comment]
Hey

It depends from library to library, but it's generally easier to compile them into a static or shared library and then manually bind the functions you need to access from go.
(But depending on the structure of your library, you can also directly mix your c++ and go code and skip the compilation into a static or shared library step)

Unfortunately it's not easily possible to automatically bind 3rdparty libs yet, so you will need to write some glue code by hand. However, if you have Qml Apis then you can reuse them without any issues.

I looked into QZXing and ported two of the examples [here](https://github.com/therecipe/qt/tree/master/internal/examples/3rdparty/qzxing)

For this to work you will need to run the `init.go` file once, to download the repo and compile it into a static library for each target. (You might need to fix the path's and/or export `QT_DIR` in init.go first)

Then, if everything compiled successfully you should be able to compile the two examples with `qtdeploy` as usual.

Also maybe take a look at the three `qzxing.*` files to see how I bound `QZXing::registerQMLTypes` and `QZXing::registerQMLImageProvider`


I tested the demos on macOS, iOS and the Android Emulator but to get it working for iOS you will need to hack `qtdeploy` with this atm:

```diff
diff --git a/internal/cmd/deploy/bundle.go b/internal/cmd/deploy/bundle.go
index 16087b04..2ea78621 100644
--- a/internal/cmd/deploy/bundle.go
+++ b/internal/cmd/deploy/bundle.go
@@ -577,7 +577,7 @@ func bundle(mode, target, path, name, depPath string, tagsCustom string, fast bo
 		if utils.ExistsFile(filepath.Join(depPath, target+"_qml_plugin_import.cpp")) {
 			cmd.Args = append(cmd.Args, target+"_qml_plugin_import.cpp")
 		}
-		cmd.Args = append(cmd.Args, "-o", "build/main", "-u", "_qt_registerPlatformPlugin", "-Wl,-e,_qt_main_wrapper", "-I../..", "-L.", "-lgo")
+		cmd.Args = append(cmd.Args, "-o", "build/main", "-u", "_qt_registerPlatformPlugin", "-Wl,-e,_qt_main_wrapper", "-I../..", "-L.", "-lgo", "-L/Users/user/go/src/github.com/therecipe/qt/internal/examples/3rdparty/qzxing/qzxing/src/ios/", "-lQZXing")
 		cmd.Dir = depPath
 		cmd.Args = append(cmd.Args, newArgs...)
 		utils.RunCmd(cmd, fmt.Sprintf("compile wrapper for %v (%v) on %v", target, t, runtime.GOOS))
```

I will try to fix this tomorrow, so that 3rd party libs will be picked up for iOS builds automatically as well.

Also btw, maybe take a look [here](https://github.com/therecipe/qt/tree/master/internal/examples/3rdparty) as well (especially the sparkle examples) these will give you an impression on how to bind c++ code in general.

**Comment by eliezedeck** [comment]
Thanks @therecipe!

I'll report back once I get mine going as well. Hope you get time so we don't to no longer hijack the main Go library. Good luck!

**Comment by eliezedeck** [comment]
Hi again,

I have tried to build the QZXingLive app, and it worked great (only tried iOS). I had to make some changes on my side though, and I'm not sure what I did wrong and why I had to add that, and you didn't have to on your side. I'm compiling from macOS 10.13.6.

So, in the `github.com/therecipe/qt/internal/examples/3rdparty/qzxing/qzxing.go` file, I added a second line as `stub2`, so I now have this:

```golang
type stub struct{ core.QObject } //needed to make QtCore available to qzxing/src/QZXing.h
type stub2 struct{ core.QMetaObject } // <== New line
```

Without this, it would complain about undefined `QMetaObject` symbol. @therecipe, can you check that yours do compile fine without this second line?

**Comment by therecipe** [comment]
I tested it again after cleaning the cache, for iOS + macOS and it did work without the stub2 struct for me. I'm using Qt 5.13.0 on macOS 10.14.4 with Xcode 10.2.1, but it should theoretically work with any older Qt/macOS versions as well.

Could you maybe post the error message, if you can still reproduce it?
Also this docker file works for android and the android emulator builds as well.
```Dockerfile
FROM therecipe/qt:android
RUN apt-get install --no-install-recommends -y ca-certificates git make
ENV ANDROID_NDK_DIR $HOME/android-ndk-r18b
RUN cd $GOPATH/src/github.com/therecipe/qt/internal/examples/3rdparty/qzxing && \
	sed -i -e 's!{runtime.GOOS!{"android", "android_emulator"}{//!g' init.go && go run init.go
RUN cd $GOPATH/src/github.com/therecipe/qt/internal/examples/3rdparty/qzxing/demo/QZXingLive && \
	qtdeploy build android && qtdeploy build android-emulator
```

So chances are high, that's probably just some env issue.

**Comment by eliezedeck** [comment]
My mistake, sorry @therecipe ... stub2 was not required indeed. I was using Qt 5.12.3 and Xcode 10.1. I think the problem was because I was not compiling from the `github.com/therecipe/qt/internal/examples/3rdparty/qzxing/demo/QZXingLive` folder (?).

I just tried again, cleared everything, and went to the folder to compile it, and it was flawless.

Just a small suggestion, in the `init.go` file, I changed to use `iCmd := exec.Command("make", "-j8")` because the compilation was too slow. May be we should automatically use all CPUs?

Regarding `qtdeploy`, have you got a chance to fix it? Would prefer to run to normal `qtdeploy` to ensure reproducible builds. Thanks again.

**Comment by therecipe** [comment]
No worry, and yes qtdeploy-ing should work now with https://github.com/therecipe/qt/commit/746779e4c012d961bc4fad16cfe6228b1b112215#diff-16e44658fb89a392fbb49ad74fdc4570 out of the box.

About the `-j` flag, yeah thats a good idea, I will change it.

**Comment by eliezedeck** [comment]
Indeed, `qtdeploy` is working without any hack now. Thanks a lot!

**Comment by therecipe** [comment]
Added the `-j` flag and cleaned up the scanner example with https://github.com/therecipe/qt/commit/9f97258ffefd28c6ab898732051ffcea666e451e
