### ISSUE TITLE
Go run vs qtdeploy - file references

### ISSUE THREAD

**Issue by TCB13** [therecipe/qt#850]
Hello,

I've been playing around with this project and it works very well however I must be missing something. From what I've come to read and experienced whenever I'm referencing files it must be done differently for `go run file.go` an `qtdeploy ...`.

Example, if I'm `go run file.go` this will work:
`````
var icon = gui.NewQIcon5("./qml/icon.ico")
`````
But this wont:
`````
var icon = gui.NewQIcon5(":/qml/icon.ico")
`````
In order to `go run` I need it set to `./qml/icon.ico` and for deployments I need `:/qml/icon.ico`. Why? 

Is there a way I can use to reference the file that will work in both scenarios? If not, can I detect whenever the code is a deployment and replace the dot by colon?

Thank you.

**Comment by therecipe** [comment]
Hey

Yeah, `var icon = gui.NewQIcon5("./qml/icon.ico")` will not directly work after qtdeploy-ing because the binary is compiled into `deploy/*` while the qml/icons/assets files haven't moved. And so the relative paths are broken.

`var icon = gui.NewQIcon5(":/qml/icon.ico")`
or better
`var icon = gui.NewQIcon5("qrc:/qml/icon.ico")`
works, because the qml/icons/assets got embed into the binary (if they go placed into the `qml` dir) and so the paths are still valid.

What you can do is to alway use `qrc:` and then use `qtrcc && go run .` to build your application during development. But this will also require you to always re-run `qtrcc` again in case you made chances to the files in the qml dir. (to re-generate these rcc* files)

This will become quite tedious over time, if you often edit `qml/*.qml` files and so its generally recommended to use something like this:
```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/quick"
	"github.com/therecipe/qt/widgets"
)

var PREF string = "."

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	view := quick.NewQQuickView(nil)
	view.SetResizeMode(quick.QQuickView__SizeRootObjectToView)
	view.SetSource(core.NewQUrl3(PREF+"/qml/main.qml", 0))
	view.Show()
	widgets.QApplication_Exec()
}
``` 

and then you can, either manually change the `PREF` value before actual deployments.

Or set `PREF` at compile time with
`go run -ldflags="-X main.PREF=qrc:" .`
or
`qtdeploy -ldflags="-X main.PREF=qrc:" build`

**Comment by TCB13** [comment]
Great solution using `ldflags`! Thank you.
