### ISSUE TITLE
Forms App with Material Design style example has some weird issues..

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#87]
I made an example to try out a typical QML Application form with Material Design / Universal Design. All i did was copy the existing /example/qml/application code.

Here is the code in my fork:
https://github.com/joeblew99/qt/commit/0332ac4b1c1c7bb6576aa431c45a3e9aed94b1af

I changed nothing inside the QML except for the imports. I did this on purpose so we have a apple for apple comparison.

I am curious if you know any answers to this ?

Some weird things:
1. How can i work out what QML import versions i can use ? I use brew to install QT, but have no idea how to find out where versions of for example QtQuick.Layouts 1.3 i have available locally.
BTW do you use a QML Designer to help ??

```
//import QtQuick 2.0
import QtQuick 2.2
import QtQuick.Controls 2.0
import QtQuick.Layouts 1.3
import QtQuick.Controls.Material 2.0
import QtQuick.Controls.Universal 2.0
```
1. The scroll bars for the text areas is not appearing.
2. the text areas scroll down pushing the controls under is off the screen. Not what the non MD style does.

**Comment by therecipe** [comment]
I usually look into the [Qt docs](http://doc.qt.io/qt-5/qml-qtquick-controls-button.html) to find out what I have to import. As far as I know there is no overview about which version is available for which module :( but I would love to have one.

Some modules seem to have the same minor version as the current Qt release, for example there was QtQuick 2.6 in Qt 5.6 and now there is QtQuick 2.7 in Qt 5.7. But that is only valid for a few modules ...

I googled a bit and found [this answer](http://stackoverflow.com/questions/32010530/how-to-find-the-latest-versions-of-all-qml-modules) on SO, which pretty much sums it up.

I just took a look at the QML Designer and it looks good, especially because it seems to directly produce QML files. I normally don't like visual designers, but this one looks good. And I probably would have saved some time if I know about this when I needed it.

I can only guess about the issues you have with the example (it looks exactly like on your screenshot for me as well). 

The example probably uses some elements which are not available for the Material/Universal design yet. And the Material design is **not** the Google Material design in Qt 5.7, the Google Material design will IIRC be available with Qt 5.8.

Btw, I think there are some preview modules available in the QML module Qt.labs.*** maybe you can find some early version of the Google Material design there. (I will look into this and report back)

**Comment by joeblew99** [comment]
thanks for your feedback. Boys its a bit hit and miss...

i just installed qt-creator via homebrew and played around with it.
Then i  loaded the application-md.qml file to see how it handles it.
In the "edit" model, you get import intellisense kind of.... It gives you incorrect numbers..
In the "Design" mode, it tells you if you guessed a bad import sometimes. lots of false positives

also it cant show you the Material Design look in the designer it seems.

its pretty shacky thats for sure.

playing around with it did not enlighten me about how to make the Material Design aspects work properly. For example a text box having the correct vertical scroll showing, and simple things like that.

Not sure what else to do for now..

https://github.com/papyros/qml-material. Its a dead project..

I guess the QT org is still gettig things to wokr properly with Material.



qml-material from the papyros team i know. Its a dead project.

Mhhh. kind of wondering how shacky this is going to be once its passed across to IOS and android with the Material look. I guess i need to find more examples.

I might have to start using web GUI (like Polymer) where i need Material look.

**Comment by therecipe** [comment]
I did also try to load a custom qml file with the designer and there were a lot of errors ...
Sorry, I just tried the provided examples and it worked really good with them.

But I looked into the TextArea ScrollBar problem and I have figured out what went wrong :)

The `Basics Layout` example is a QtQuick 1 example.
In QtQuick 1 the TextArea is scrollable by default. http://doc.qt.io/qt-5/qml-qtquick-controls-textarea.html

But if you want to use the Material theme, you are forced to use QtQuick 2.
In QtQuick 2 the TextArea is **not** scrollable by default http://doc.qt.io/qt-5/qml-qtquick-controls2-textarea.html

So if you simply change `QtQuick.Controls 1.2` to `QtQuick.Controls 2.0` the TextArea stops beeing scrollable ...

But I also managed to make the TextArea scrollable again (the instruction is in the QtQuick 2 TextArea docs)

Just replace the GroupBox with this:

```qml
GroupBox {
    id: gridBox
    title: "Grid layout"
    Layout.fillWidth: true

    GridLayout {
        id: gridLayout
        rows: 3
        flow: GridLayout.TopToBottom
        anchors.fill: parent

        Label { text: "Line 1" }
        Label { text: "Line 2" }
        Label { text: "Line 3" }

        TextField { }
        TextField { id: textField }
        TextField { }

        Flickable {
            anchors {
                top: parent.top
                left: textField.right
                right: parent.right
                bottom: parent.bottom
            }
            contentHeight: texti.width
            contentWidth: texti.height

            TextArea.flickable: TextArea {
                id: texti
                text: "This widget spans over three rows in the GridLayout.\n"
                    + "All items in the GridLayout are implicitly positioned from top to bottom."
                wrapMode: TextArea.Wrap
            }

            ScrollBar.vertical: ScrollBar { }
        }
    }
}
```

**Comment by joeblew99** [comment]
wow impressive hunting.
How about updating the demo in the main repo to reflect it ?
Does it still work with non Material i wonder :) ?
therecipe/qt/tree/master/internal/examples/qml/material

i also saw the refactoring to move everything into cmd. 
Looking forward kicking the tires.

**Comment by therecipe** [comment]
Updated the example with https://github.com/therecipe/qt/commit/1631e7ef2a4275d3d7702a86f245336c5dff22b3 as you suggested :)

It seems to work without any theme (material or universal) as well.
IIRC the themes only change the appearance and don't alter the functionality.

**Comment by joeblew99** [comment]
@therecipe  thank you.

i think next is to try out IOS and android.
Hows the docker and retooling going to use cmd, etc ? Should i wait a bit ??

**Comment by therecipe** [comment]
It should work already.
So you just need to install docker, pull the needed image and share your gopath with docker.

Then you can build you app for android with `qtdeploy build android path/to/project docker`
Please let me know if you run into any issues :)
