### ISSUE TITLE
The further fate of this project

### ISSUE THREAD

**Issue by proninyaroslav** [therecipe/qt#88]
Hello. I'm very happy to find a decent Qt binding for Go. Thank you very much for so big great work. 
I want to use your developments for create my applications, but I'm concerned about future of the project. 
One time this project has grown rapidly, but now its activity faded https://github.com/go-qml/qml . 
I would not want that your project has gone this route, since our community is still not native GUI lib, this is a very big problem for the promotion of language as an independent and self-sufficient.

**Comment by slier81** [comment]
yep, i want response from author too

**Comment by therecipe** [comment]
Hey

This is somewhat hard to answer.

I'm planning to at least keep the binding up to date with the latest Qt version.
And will try to solve all upcoming issues and clean up the code.

I'm already investing much of my free time into this, but currently can't justify investing even more.
Even through I would love to do so, as I got an idea how this project could look like.
But like everything that requires work, this project needs either more time (work hours) or more money.

I tend to favour the latter, because it can also be used to obtain the former.
But money comes along with terms and before that conditions have to be met.

I'm working on those conditions, because I belive Go and Qt can complement each other and this project could be usefull even for those who just started with Go (or programming in general) and for those who want to start with Qt but don't want to use C++ or Python.

So, I know there is potential and this is a long road and I'm not sure how much time it will take.
But I'm working on it :)

**Comment by proninyaroslav** [comment]
I'll hope that your project will find those people who will be interested in its further support.

Thank you for your work and happy hacking!

**Comment by bclermont** [comment]
I plan to contribute myself (and everyone else on my time) to this project as soon as I'm more comfortable with the whole binding part.

**Comment by therecipe** [comment]
@bclermont 
That's awesome :)
I'm gladly appreciate any help I can get.
