### ISSUE TITLE
Potential Missing SetPos, SetPos2 methods on QGraphicsTextItem

### ISSUE THREAD

**Issue by rashwell** [therecipe/qt#89]
First this binding is absolutely awesome!!  

I might be missing something, but I have a hard time casting as I don't completely understand the pointer stuff as implemented here.

But here is my issue:

Placing a **QGraphicsItem** in a specific location in a scene there exists, **SetPos**, **SetPos2**, but when you want to add text to a scene with **QGraphicsTextItem** or **QGraphicsSimpleTextItem** the helpers of **SetPos** and **SetPos2** don't exist.  

So what I would expect is in widgets:

``` go
func (ptr *QGraphicsTextItem) SetPos(pos core.QPointF_ITF) { ... }
func (ptr *QGraphicsTextItem) SetPos2(x float64, y float64) { ... }
func (p *QGraphicsSimpleTextItem) SetPos(pos core.QPointF_ITF) { ... }
func (p *QGraphicsSimpleTextItem) SetPos2(x float64, y float64) { ... }
```

to be available.  Rather than just complaining, If someone can confirm that this is also what they would expect, I can do a PR and try and add the above implemented.  

But it might also be possible that I just don't know how to in go, cast about the pointers, etc, back to the QGraphicsItem where the **SetPos**, **SetPos2** methods do exist.

Basically I want to achieve this type of thing a chessboard like example:

``` go
squareSize := 100 // Pixel Size of each Square
scene := widgets.NewQGraphicsScene(window)
gpen := gui.NewQPen2(core.Qt__NoPen)
gpen2 := gui.NewQPen2(core.Qt__SolidLine)
gbrushgrey := gui.NewQBrush4(core.Qt__darkGray, core.Qt__SolidPattern)
gbrushblack := gui.NewQBrush4(core.Qt__black, core.Qt__SolidPattern)
gbrushwhite := gui.NewQBrush4(core.Qt__white, core.Qt__SolidPattern)
for i := 0; i < 8; i++ {
    for j := 0; j < 8; j++ {
        if i%2 == j%2 {
            scene.AddRect2(float64(j*squareSize), float64(i*squareSize), float64(squareSize), float64(squareSize), gpen, gbrushwhite)
        } else {
            scene.AddRect2(float64(j*squareSize), float64(i*squareSize), float64(squareSize), float64(squareSize), gpen, gbrushgrey)
        }
    }
}
// Borders Around Chess Board
scene.AddRect2(-10.0, -10.0, 10, float64(squareSize*8+20), gpen2, gbrushblack)
scene.AddRect2(-10.0, -10.0, float64(squareSize*8+20), 10.0, gpen2, gbrushblack)
scene.AddRect2(float64(squareSize*8), -10, 10, float64(squareSize*8+20), gpen2, gbrushblack)
scene.AddRect2(-10.0, float64(squareSize*8), float64(squareSize*8+20), 10, gpen2, gbrushblack)

// Add Some Labels specifically on Chessboard just one for this example
labelfont := gui.NewQFont2("Arial", 15, 100, false)
squarelabel := scene.AddText("A8", labelfont)
// Stuck here because what I want to do is
squarelabel.SetPos2(float64(squareSize-20), float64(squareSize-2)) // Place label in right hand corner of top left square
```

But since conceptually QGraphicsTextItem in the QT portion inherits from QGraphicsItem perhaps instead this isn't anything missing other than my knowledge of how to cast in go with this library to get back to the methods of QGraphicsItem.

**Comment by 5k3105** [comment]
I use this, where 'p' is the *gui.QPainter in the paint function:

```go

	var font = gui.NewQFont2("verdana", 20, 1, false)
	p.SetFont(font)

	var qpf = core.NewQPointF3(r.X+10.0, r.Y+r.H-10.0)

	p.DrawText(qpf, r.Name) //+" "+strconv.Itoa(r.Node.Id))

```

**Comment by therecipe** [comment]
Hey

Thank you :)

I looked into this and fixed it with https://github.com/therecipe/qt/commit/390ab5b29f4a63b82037bfb12acad17402d5d842
But while doing so, I found another related problem which is going to be a bit more tedious to fix.

As you said `QGraphicsTextItem` inherits `QGraphicsItem` and therefore already has `SetPos` and `SetPos2`.
You can simply call `squarelabel.SetPos2` as you did and it should have worked. (It called the `QGraphicsItem.SetPos2` implemention under the hode) http://doc.qt.io/qt-5/qgraphicsitem.html#setPos

But in this particular case `QGraphicsObject` should have overriden the `SetPos` functions with a property setter function http://doc.qt.io/qt-5/qgraphicsobject.html#pos-prop.

This didn't happen and therefore the `squarelabel.SetPos2` called the wrong `QGraphicsItem.SetPos2` implementation. (And it had no effect or crashed)

But now `QGraphicsTextItem.SetPos2` calls the setter function `QGraphicsObject.SetPos2` and it works.

```go
type QGraphicsObject struct {
	core.QObject
	QGraphicsItem //SetPos is a normal member function (which was falsely called from QGraphicsTextItem)
}

type QGraphicsTextItem struct {
	QGraphicsObject //SetPos is a property setter function (which wasn't created previously but is now called from QGraphicsTextItem)
}
```

I made a few changes in the `binding/parser/*.go` files to allow the code generator to recognize properties, and create setter and getter functions for them if needed.
This was necessary, because the the *.index files that are used to generate the code are imperfect.


And about the casting.
In Go there is no need to downcast to call a parent class function, if the inherided class is subclassed anonymously. (Like shown above)
But you can call a specific parent class implementation by calling for example `squarelabel.QGraphicsObject.SetPos2(100, 20)` or `squarelabel.QGraphicsItem.SetPos2(100, 20)`

If you however want to cast, you probably should use the binding helper functions like this: `widgets.NewQGraphicsObjectFromPointer(squarelabel.Pointer())` (because the normal Go cast probably won't work)


Here is a full example that should work now:

```go
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var (
		view  = widgets.NewQGraphicsView(nil)
		scene = widgets.NewQGraphicsScene3(0, 0, 300, 300, nil)
		font  = gui.NewQFont2("Meiryo", 20, 2, false)
	)
	view.SetScene(scene)

	var test = scene.AddText("Test 1 Pos", font)
	test.SetPos(core.NewQPointF3(100, 0))

	test = scene.AddText("Test 1 Pos2", font)
	test.SetPos2(100, 20)
	//test.QGraphicsObject.SetPos2(100, 20) //same as test.SetPos2
	//test.QGraphicsItem.SetPos2(100, 20) //doesn't work, because of the property setter problem

	/*
		var test2 = widgets.NewQGraphicsTextItem2("Test 2 Pos", nil)
		test2.SetFont(font)
		scene.AddItem(test2)
		test2.SetPos(core.NewQPointF3(100, 40))

		test2 = widgets.NewQGraphicsTextItem2("Test 2 Pos 2", nil)
		test2.SetFont(font)
		scene.AddItem(test2)
		test2.SetPos2(100, 60)

		scene.AddItem(widgets.NewQGraphicsWidget(nil, 0))
	*/

	var test3 = widgets.NewQGraphicsSimpleTextItem2("Test 3 Pos", nil)
	test3.SetFont(font)
	scene.AddItem(test3)
	test3.SetPos(core.NewQPointF3(100, 80))

	test3 = widgets.NewQGraphicsSimpleTextItem2("Test 3 Pos2", nil)
	test3.SetFont(font)
	scene.AddItem(test3)
	test3.SetPos2(100, 100)

	view.Show()

	widgets.QApplication_Exec()
}
```

The functions in the middle are commented out, because those are related to the problem I talked about in the beginning.

Currently all pointers are static_casted from `void*` into `QGraphicsItem*` before calling the `QGraphicScene.AddItem` function in C++.
This works for subclasses like `QGraphicsSimpleTextItem` and similar which are **not** polymorphic, but is a problem for classes such as `QGraphicsTextItem`.
I will therefore have to sanitize all functions that possibly get polymorphic classes as input parameters with dynamic_cast.

**Comment by 5k3105** [comment]
Hi,

I attempted to use QGraphicsProxyWidget:

```go
package main

import (
"os"

"github.com/therecipe/qt/widgets"
)

func main() {
	var (
		view  = widgets.NewQGraphicsView(nil)
		scene = widgets.NewQGraphicsScene3(0, 0, 300, 300, nil)
	)

	widgets.NewQApplication(len(os.Args), os.Args)
	
	line := widgets.NewQLineEdit2("wtf",nil)
	pw := scene.AddWidget(line,0)
	pw.SetPos2(100, 20)

	view.SetScene(scene)
	view.Show()

	widgets.QApplication_Exec()
}
```

This returned a popup window during compile:

Microsoft Visual C++ Runtime Library
  This application has requested the Runtime to terminate it in an unusual way.
  Please contact the application's support team for more information.

Running Win7 64bit.

**Comment by therecipe** [comment]
@5k3105
Got this error on macOS: `QWidget: Must construct a QApplication before a QWidget`
So you just need to call `widgets.NewQApplication` first before creating the other QWidgets.

And it works :)
```go
package main

import (
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	var (
		view  = widgets.NewQGraphicsView(nil)
		scene = widgets.NewQGraphicsScene3(0, 0, 300, 300, nil)
	)

	line := widgets.NewQLineEdit2("wtf", nil)
	pw := scene.AddWidget(line, 0)
	pw.SetPos2(100, 20)

	view.SetScene(scene)
	view.Show()

	widgets.QApplication_Exec()
}
```

**Comment by 5k3105** [comment]
Excellent! Thank you!

**Comment by therecipe** [comment]
The example above https://github.com/therecipe/qt/issues/89#issuecomment-257661479 should work with 11aa6b1 now.
