### ISSUE TITLE
undefined: core.QMetaObject_ConnectSlotsByName

### ISSUE THREAD

**Issue by muyuballs** [therecipe/qt#899]
> go version go1.12.6 linux/amd64
> qt 5.13.0
> xubuntu 18.10 with xfce4

I found the `QMetaObject` define in 
**5.13.0/qtcore/qtcore.index:13175**
```
<struct name="QMetaObject" href="qmetaobject.html" status="active" access="public" location="qobjectdefs.h" filepath="/home/qt/work/build/qtbase/include/QtCore/../../../../qt/tqtc-qt5/qtbase/src/corelib/kernel/qobjectdefs.h" lineno="337" module="QtCore" groups="objectmodel" brief="Contains meta-information about Qt objects">
```

**Comment by MDobak** [comment]
Bindings for QMetaObject was removed from core.go in commit 9e0d30121645ef928ee504958d1548996c30396d.

@therecipe it was intentional?

**Comment by therecipe** [comment]
@MDobak 
No, sorry it just slipped through somehow.
The problem was that the xml struct tag for the QMetaObject class in the qtcore.index file changed from `class` to `struct` for some unknown reason.
It should now be fixed with https://github.com/therecipe/qt/commit/7a4e353ce4354977fe6001f8aa91ff0a1a721b73 though.

@muyuballs
Sorry for the wait, the `core.QMetaObject_ConnectSlotsByName` function should now be available again.

**Comment by muyuballs** [comment]
@therecipe thanks for your work
