### ISSUE TITLE
Updating a TableView programmatically to show new rows of data (sql/masterdetail_qml example)

### ISSUE THREAD

**Issue by amlwwalker** [therecipe/qt#926]
I am modifying/using the [sql/masterdetail_qml](https://github.com/therecipe/qt/tree/master/internal/examples/sql/masterdetail_qml) example as a basis of a project. I have adjusted it to be the front end of a project that watches for changes to a file using the [go watcher](github.com/radovskyb/watcher) project. When a change is noticed to a file, it adds details about the change to a boltdb database, which is the basis for the model to populate the TableView.
When I first load the application, the TableView is populated correctly with any information that is in the database - i.e the model is correctly linked to the database. However the sql/masterdetail_qml example shows how to add to the TableView model if the user initiates the process. I have another package (that contains the aforementioned watcher) that is populating the database and it fires a `Op_NewChange` message on a channel that the UI controller is listening on (and detects successfully). 
What I am struggling to do then is to get the model to update based on the new data in the database.

I have tried to do a 

```
select {
case op := <-c.information:
  switch op {
  case logic.Op_NewDiff:
    model.SortFilterModel.BeginResetModel()
    model.SortFilterModel.EndResetModel()
```

However this causes an error in the terminal

```
QObject::connect: Cannot queue arguments of type 'QQmlChangeSet'
(Make sure 'QQmlChangeSet' is registered using qRegisterMetaType().)
```
Reading around this is due to trying to change the model on a thread that is not the UI thread and that the change must occur from qml, so then I tried to do something similar to the above, however a slight adjustment:
```
model.SortFilterModel.BeginResetModel()
c.DiffAdded()
model.SortFilterModel.EndResetModel()
```
Where DiffAdded is a signal to the frontend to do:
```
  onDiffAdded: {
    tableView.selection.clear()
    tableView.selection.select(tableView.rowCount - 1)
    showDiffDetails(tableView.model.index(tableView.rowCount - 1, 0))
  }
```
However that causes the same error. I realise this is due to the `BeginResetModel()` and `EndResetModel()`, however when I do do this, even with the error, the TableView flickers informing me that I must be _close_ to success, but no cigar. When I don't have the `Begin/End` I don't get the equivalent flicker.

Now, I know that in the sql/masterdetail_qml example there is

```
go func() {
  count := 0
  for range time.NewTicker(5 * time.Second).C {
    c.AddAlbum("goRoutineArtist", fmt.Sprint(count), 2017, "")
    count++
  }
}()
```

which is successfully adding to the TableView, however this adds to the database, rather than the model reading again from the database. In my instance, the database write is happening elsewhere (in a package that has no idea of a UI etc) and therefore I can't ask it to reset the model etc before it begins the write.

One thought I had was I get it to fire a message on the channel stating it was about to write to the database, then the UI begins the model reset and says "ok write to database", then it fires another message when it's complete, then the model ends the reset. That however seems very convoluted rather than just one message "the database has changed" and the model updates, but perhaps that would be automagic?

**Comment by amlwwalker** [comment]
@therecipe any ideas on this by any chance, still struggle to get a good approach to get this working

**Comment by therecipe** [comment]
Hey

Sorry for the wait, I extended my vacation last month and now I have quite the backlog to work through :D

About the issues, I think you were on the right track with something like this:

```go
select {
case op := <-c.information:
  switch op {
  case logic.Op_NewDiff:
    model.SortFilterModel.BeginResetModel()
    model.SortFilterModel.EndResetModel()
```

the problem is just that you need to call `BeginResetModel` and `EndResetModel` from within the main thread.

If you aren't calling these functions from the main thread then you will get errors like these:
```
QObject::connect: Cannot queue arguments of type 'QQmlChangeSet'
(Make sure 'QQmlChangeSet' is registered using qRegisterMetaType().)
```

and you application will either crash, or nothing happens at all.

I made some changes to this example here: https://github.com/therecipe/examples/blob/master/advanced/qml_quick/listview/main.go

```diff
diff --git a/advanced/qml_quick/listview/main.go b/advanced/qml_quick/listview/main.go
index 9c88776..28cac3c 100644
--- a/advanced/qml_quick/listview/main.go
+++ b/advanced/qml_quick/listview/main.go
@@ -3,6 +3,7 @@ package main
 import (
 	"fmt"
 	"os"
+	"time"
 
 	"github.com/therecipe/qt/core"
 	"github.com/therecipe/qt/quick"
@@ -16,6 +17,8 @@ type ListItem struct {
 	lastName  string
 }
 
+var globalModel *CustomListModel
+
 type CustomListModel struct {
 	core.QAbstractListModel
 
@@ -25,10 +28,13 @@ type CustomListModel struct {
 	_ func(obj []*core.QVariant)              `signal:"add,auto"`
 	_ func(firstName string, lastName string) `signal:"edit,auto"`
 
+	_ func() `signal:"update,auto"`
+
 	modelData []ListItem
 }
 
 func (m *CustomListModel) init() {
+	globalModel = m
 	m.modelData = []ListItem{{"john", "doe"}, {"john", "bob"}}
 
 	m.ConnectRowCount(m.rowCount)
@@ -71,7 +77,33 @@ func (m *CustomListModel) edit(firstName string, lastName string) {
 	m.DataChanged(m.Index(len(m.modelData)-1, 0, core.NewQModelIndex()), m.Index(len(m.modelData)-1, 0, core.NewQModelIndex()), []int{int(core.Qt__DisplayRole)})
 }
 
+func (m *CustomListModel) update() {
+	m.BeginResetModel()
+	m.EndResetModel()
+}
+
 func main() {
+
+	go func() {
+		var count int
+		for range time.Tick(2 * time.Second) {
+			if globalModel == nil {
+				continue
+			}
+			count++
+			globalModel.modelData = append(globalModel.modelData, ListItem{"NEW", fmt.Sprint(count)})
+		}
+	}()
+
+	go func() {
+		for range time.Tick(1 * time.Second) {
+			if globalModel == nil {
+				continue
+			}
+			globalModel.Update()
+		}
+	}()
+
 	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
 
 	app := widgets.NewQApplication(len(os.Args), os.Args)
```

which is somewhat similar to your setup.

In the example the first go routine edits the database (stored inside the model struct), while the second go routine periodically updates/resets the model to update the view.
To make this work, I just needed to create a helper signal (or slot) and wrap the `BeginResetModel` and `EndResetModel` calls inside.

**Comment by amlwwalker** [comment]
Thanks for getting back to me, yes I've been stalking your holiday by watching the commit dates 😂
I guessed you extended your holiday so it must have been good. I tried to take on a couple of the easier questions people had while you were away but I think ended up asking three of my own so no net profit there!
I guess you are just crunching through the issues so don't panic on the others I have, this was an implementation the others were slightly more philosophical...

**Comment by amlwwalker** [comment]
Ok... So the issue I have with using this approach:

```
func init() { CustomListModel_QmlRegisterType2("CustomQmlTypes", 1, 0, "CustomListModel") }
```

is that this then uses the 

```
func (m *CustomListModel) init() {
```
to initialise the CustomListModel, however I need (as you can see from above to pass in my manager object (which you can see from my above example). I can't do this with the init() approach.

I attempted to use the controller global object to set the manager, however based on the way its configured, I end up with circular referencing. Is there a way to set a signal using the 

```
func NewListModel(manager *logic.Manager) *core.QAbstractItemModel {
ListModel = &listModel{core.NewQAbstractListModel(nil), manager}
```
approach?

**Comment by amlwwalker** [comment]
Ok, it's taken me a frankly embarrassing amount of time to get this working, but I have. All the clues were in your diff and the existing code (mainly looking at how the controller was initialised). My error was to try and make a Qt module out of the model as per your example, which meant that the initialisation was not occurring in the correct order and I was getting the nil pointer exceptions. I now understand why it wasn't working, and why it now does work. This is fantastic. By coming back to the code with large coffee breaks in between I finally clocked what I was not understanding.
I will leave my post above as a gravestone of my thought process, rather than editing it. 

If @therecipe does get a chance to answer some of the points from a general perspective, that would be handy but its no longer causing me any issue to move forward.

Here is my final listView model for anyone who comes to the same issue as I did. 

```
package model

import (
	"github.com/amlwwalker/pickleit/logic"
	"github.com/therecipe/qt/core"
)

var ListModel *listModel

type listModel struct {
	*core.QAbstractListModel
	manager *logic.Manager
	_       func() `signal:"Update,auto"`
}

func NewListModel(manager *logic.Manager) *core.QAbstractItemModel {
	ListModel = &listModel{}
	ListModel.QAbstractListModel = core.NewQAbstractListModel(nil)
	ListModel.manager = manager
	ListModel.ConnectRowCount(ListModel.rowCount)
	ListModel.ConnectData(ListModel.data)

	return ListModel.QAbstractItemModel_PTR()
}

func (m *listModel) Update() {
	m.BeginResetModel()
	m.EndResetModel()
}
func (m *listModel) rowCount(parent *core.QModelIndex) int {
	return m.manager.GetFileCount()
}

func (m *listModel) data(index *core.QModelIndex, role int) *core.QVariant {
	if role != int(core.Qt__DisplayRole) {
		return core.NewQVariant()
	}
	return core.NewQVariant1(m.manager.GetFileForID(index.Row() + 1).Name)
}

```

I'll close this in a week or so.

**Comment by therecipe** [comment]
Sorry again for the delay, and yeah the vacation was very relaxing but also long overdue.
I actually planned to get some work done in the second half of it, but that didn't work out at all :D
Also thanks for helping out with some of the issue, I really appreciate it.
I will try to slowly work myself through the backlog now, but it will take some time.



And about this issue, it seems like you did solve it in the meantime :)
Here is what I prepared yesterday though.
(I also appended my take on the masterdetail_sql example)

---


>how do I define it when its a blank identifier? I thought it wouldn't be bothered by that.

You could use something like:
```go
&listModel{core.NewQAbstractListModel(nil), manager, nil}
```
or use something like
```go
&listModel{QAbstractListModel: core.NewQAbstractListModel(nil), manager: manager}
```

>I wonder if when you want to add signals you have to create a Qml type with the equivalent of
>...
>so that the front end (the main thread) registers the model rather than registering it as part of the backend/not main thread....?

No, you don't need to register the Qml Type with `QmlRegisterType`, this is only necessary if you want to instantiate the type from Qml. 

For example, here the type is registered: https://github.com/therecipe/examples/blob/master/advanced/qml_quick/listview/main.go#L12 and here it's later instantiated in Qml https://github.com/therecipe/examples/blob/master/advanced/qml_quick/listview/qml/main.qml#L19


>Ok... So the issue I have with using this approach:
>...
>is that this then uses the
>...
>to initialise the CustomListModel ...

Not directly, you can register a type with `QmlRegisterType` but you will still need to create/instantiate it from either Go or Qml to trigger the `init` (constructor) function.

>As this is a data model, it doesn't seem I should necessarily register it as a type that the front end (qml) has as a type?

If you don't create/instantiate the type from Qml, then there is no need to register it.
(I think that there might be cases where you would need to register it, so that it can be passed between Qml and Go, but IIRC most of the time there is no need to do this)


>I'm not quite sure when to use which.

You can use `*` if you don't want to extend the class with custom properties/signals/slots.
If you omit the `*` then the struct is processed by qtmoc and will generate c++ code so that you can extend it with your own properties/signals/slots, which can then be used from/with Qml for example.


>init() {} is called when the model package is instantiated. In this case from the controller package.

Yes, that's correct.

>listModel_QmlRegisterType2("ListModel", 1, 0, "ListModel") results in a new listModel instance to be created and that then in turn....

No, this just registers the type and makes it available to Qml
You will still need to create the type with something like `ListModel{}` in Qml


>Due to _ func() constructor:"init"`` results in (m *listModel) init() being called.

Yes, that's correct.
The init function is called when running `NewListModel` (from go) or `ListModel{}` (from qml)

>Finally, from the controller's initWith() function I can call (m *listModel) ...

Yes, checkout the diff I posted below.



>which means that the init()'s aren't called at all. I wonder whether this is because this model has no qml import on it?
>... so I'm not sure why I get the nil pointer refererence.

Maybe you did forgot to re-run `qtmoc` or `qtdeploy` after adding the constructor to the struct?


---


(I couldn't use `github.com/amlwwalker/pickleit/logic`, so I just made the `manager` a string)

`listmodel.go`
```go
package model

import (
	"fmt"

	"github.com/therecipe/qt/core"
)

var ListModel *listModel

type listModel struct {
	core.QAbstractListModel

	manager      string
	ManagerCount int

	_ func() `constructor:"init"`
	_ func() `signal:"update,auto"`
}

func (m *listModel) init() {
	ListModel = m
	m.ConnectRowCount(m.rowCount)
	m.ConnectData(m.data)
}

func (m *listModel) ConfigureModel(manager string) {
	m.manager = manager
}

func (m *listModel) update() {
	m.BeginResetModel()
	m.EndResetModel()
}

func (m *listModel) rowCount(parent *core.QModelIndex) int {
	return m.ManagerCount
}

func (m *listModel) data(index *core.QModelIndex, role int) *core.QVariant {
	if role != int(core.Qt__DisplayRole) {
		return core.NewQVariant()
	}
	return core.NewQVariant1("someManagerString-" + fmt.Sprint(index.Row()))
}
```

`controller/controller.go`
```diff
diff --git a/internal/examples/sql/masterdetail_qml/controller/controller.go b/internal/examples/sql/masterdetail_qml/controller/controller.go
index 8385b043..897d41c6 100644
--- a/internal/examples/sql/masterdetail_qml/controller/controller.go
+++ b/internal/examples/sql/masterdetail_qml/controller/controller.go
@@ -56,7 +56,7 @@ func (c *Controller) init() {
 	Instance = c
 	c.albumData = xml.NewQDomDocument()
 
-	c.SetArtistModel(model.NewListModel())
+	c.SetArtistModel(model.NewListModel(nil))
 	c.SetAlbumModel(model.NewSortFilterModel())
 
 	//<-view
@@ -83,6 +83,14 @@ func (c *Controller) init() {
 func (c *Controller) InitWith(file *core.QFile, qApp *widgets.QApplication) {
 	c.readalbumData(file)
 	c.qApp = qApp
+	model.ListModel.ConfigureModel("someManagerConfig")
+
+	go func() {
+		for range time.Tick(1 * time.Second) {
+			model.ListModel.ManagerCount++
+			model.ListModel.Update()
+		}
+	}()
 }
 
 func (c *Controller) changeArtist(row int) {
```

**Comment by amlwwalker** [comment]
Fantastic, as you spotted I did indeed solve it, however your answer helps general understanding and I'm sure someone else coming across this. Let's close this to help your list of work to do. I'm sure I'll return but I'm definitely on the road to mastery (albeit a long way off!)
Yes. I did the same. Took all my tech on holiday, and didn't turn a single device on. Perfect.
