### ISSUE TITLE
Get child of widget

### ISSUE THREAD

**Issue by ttimt** [therecipe/qt#944]
With `qtmoc` we can automatically set the constructor, signal and slots etc.

But how can we do it for a widget's child?
Let's say a widget own pushButtonA and I want to do widget.pushButtonA without using FindChild.

Like in this example:
I see InputSpinBox1 and InputSpinBox2 are already known
https://github.com/therecipe/qt/blob/master/internal/examples/uitools/calculator/ui/calculatorform.go

**Comment by therecipe** [comment]
Hey

The binding is not tracking the parent-child relationship by itself, so you would need to manually create and keep a reference to your widget's children with something like this:

```go
package main

import (
	"os"

	"github.com/therecipe/qt/widgets"
)

//

type widget struct {
	*widgets.QWidget

	child *widgets.QPushButton
}

func NewWidget() *widget {
	w := &widget{
		QWidget: widgets.NewQWidget(nil, 0),
		child:   widgets.NewQPushButton2("widget", nil),
	}
	w.SetLayout(widgets.NewQHBoxLayout())
	w.Layout().AddWidget(w.child)
	return w
}

//

type mocWidget struct {
	widgets.QWidget

	_ func() `constructor:"init"`

	child *widgets.QPushButton
}

func (w *mocWidget) init() {
	w.child = widgets.NewQPushButton2("mocWidget", nil)
	w.SetLayout(widgets.NewQHBoxLayout())
	w.Layout().AddWidget(w.child)
}

//

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	w := NewWidget()
	w.child.ConnectClicked(func(bool) { w.Hide() })
	w.Show()

	mw := NewMocWidget(nil, 0)
	mw.child.ConnectClicked(func(bool) { mw.Hide() })
	mw.Show()

	widgets.QApplication_Exec()
}
```

The `uitools/calculator` example is special in that regard, because the child name is known before compile time ([here](https://github.com/therecipe/qt/blob/master/internal/examples/uitools/calculator/ui/calculatorform.ui#L80)), and so the `qtrcc` tool can generate go code that automatically finds the child by it's name (with the help of the findChild function) or it generates code that automatically assigns the child to the parent struct.
(maybe try running `qtrcc` or `qtrcc -uic=false` inside the `calculator` dir and then checkout the `calculator/ui/uic_calculatorform.go` file each time)

**Comment by ttimt** [comment]
I see, thanks for answering!
