### ISSUE TITLE
Can I debug program with golang ide, such as Goland?

### ISSUE THREAD

**Issue by BenDerPan** [therecipe/qt#950]
Is there any way to debug therecipe/qt program with IDE(visual studio code or goland)?

**Comment by therecipe** [comment]
Hey

I don't know about visual studio, but debugging with goland seems to work on macOS.
You just need to add `-tags=minimal` to the go tools arguments, and edit your config so that qtminimal runs before each build. qtminimal needs no arguments, just set the working dir to `$FileDir$` or something and you are good to go.

**Comment by BenDerPan** [comment]
@therecipe  I am almost there, but there is still something not work, when I start debug, there just output `build github.com/therecipe/qt/widgets: cannot load github.com/therecipe/qt/widgets: no Go source files`, then compilation exit.

![image](https://user-images.githubusercontent.com/10903567/64661173-42980800-d476-11e9-8f9d-ce4907d0826c.png)


![image](https://user-images.githubusercontent.com/10903567/64661160-28f6c080-d476-11e9-8f87-d387af8e4e5f.png)

![image](https://user-images.githubusercontent.com/10903567/64661138-0cf31f00-d476-11e9-88a4-59879a2dbea3.png)

**Comment by therecipe** [comment]
Does the `github.com/therecipe/qt/widgets` dir contain files called `widgets-minimal.*`?
Also do you use go modules? (if yes, then you might need to also add `-mod=vendor` to the go tool  arguments)

**Comment by BenDerPan** [comment]
@therecipe  yes, I am use go modules, it's ok now when I add -mod=vendor to the go tool arguments, really great! :) thankns !!!
