### ISSUE TITLE
Run with "go run" after using qtmoc?

### ISSUE THREAD

**Issue by l0hn** [therecipe/qt#967]
Hi,

Is there something that needs to be done to allow go run / go build to work after using qtmoc?

If I use qtdeploy the application builds and runs correctly but 'go run' and 'go build' fail with an error about an undefined method (a method generated by qtmoc)

Thanks

**Comment by therecipe** [comment]
Hey

No, there are no additional steps needed.
`qtmoc && go run .` should work just fine.

Could you maybe post the error log so I can look into this?

Also since I assume you develop on windows (because of your other windows related issue).
Did you run the `qtenv.bat` script before using `go run/build`?

**Comment by l0hn** [comment]
Hi,

Yes it seems I was trying to use "go run main.go" instead of "go run ." so this is actually working fine :)
