### ISSUE TITLE
.ui parser/code generation syntax error

### ISSUE THREAD

**Issue by zanitee** [therecipe/qt#976]
There seems to be an error with the code generation when using qtdeploy and the QToolBox, the code generated is:

`widgets.NewQToolBox(w.CentralWidget)
w.ToolBox.AddItem(w.General, "General")`

Which are both missing arguments.
Build output:

`# github.com/zanitee/uitest/ui
ui\uic_mainwindow.go:328:33: not enough arguments in call to widgets.NewQToolBox
        have (*widgets.QWidget)
        want (widgets.QWidget_ITF, core.Qt__WindowType)
ui\uic_mainwindow.go:362:19: not enough arguments in call to w.ToolBox.AddItem
        have (*widgets.QWidget, string)
        want (widgets.QWidget_ITF, gui.QIcon_ITF, string)
ui\uic_mainwindow.go:366:19: not enough arguments in call to w.ToolBox.AddItem
        have (*widgets.QWidget, string)
        want (widgets.QWidget_ITF, gui.QIcon_ITF, string)
ui\uic_mainwindow.go:370:19: not enough arguments in call to w.ToolBox.AddItem
        have (*widgets.QWidget, string)
        want (widgets.QWidget_ITF, gui.QIcon_ITF, string)
ui\uic_mainwindow.go:374:19: not enough arguments in call to w.ToolBox.AddItem
        have (*widgets.QWidget, string)
        want (widgets.QWidget_ITF, gui.QIcon_ITF, string)`

specifically using: qtdeploy test desktop <path>

since qtdeploy is generating the code I'm not sure how to fix this for the time being.

EDIT: specifying -uic=false successfully builds the UI, however I'd still like to get/fix code generation.

I will also ask, how would one use an hybrid of UI embedding but also build/extend some of the UI in Go code?

**Comment by therecipe** [comment]
Hey

I looked into the code generation issue and https://github.com/therecipe/qt/commit/98ccee3b6f0daedfa14611df0a3c7ef3ebd4bb2d#diff-3248c2fc5c64cd64238e8d58233b73f7 should fix this now.

And about the extending of the ui, you can use an "init" function to do this.
Take a look here: https://github.com/therecipe/qt/tree/master/internal/examples/uitools/calculator/ui

To make it work, simply create a go file alongside your ui file and write a "init" function similar to what is shown in the `calculatorform.go` file.
The init function is then later automatically called when creating the widget with "NewXYZ" and can be used to connect signals/slots or otherwise setup the widget.

But to "really" extend the widget with new signals/slots/properties or something, you would need to subclass it with `qtmoc`, but I just figured that this is not possible without some ugly work around.
I will look into this though.

**Comment by zanitee** [comment]
Thanks for the quick fix, issue fixed.

I wasn't aware of the init() so thanks for that too.
