### ISSUE TITLE
QBuffer with QByteArray

### ISSUE THREAD

**Issue by gen2brain** [therecipe/qt#98]
Hi,

I am trying to get raw bytes from QImage/QPixmap. There is example for that in docs http://doc.qt.io/qt-5/qimage.html#save-1 . Now, in bindings, there is only NewQByteArrayFromPointer, but NewQBuffer2 accepts only byteArray string param, can I create QBuffer like it is in docs?

Bellow is example of what I tried, data from QBuffer is of same length but it is not valid image:
```
package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)

	widget := widgets.NewQWidget(nil, 0)
	label := widgets.NewQLabel(widget, 0)

	layout := widgets.NewQVBoxLayout()
	layout.SetSpacing(0)
	layout.SetContentsMargins(0, 0, 0, 0)

	// desktop screenshot
	desktop := widgets.QApplication_Desktop()
	screen := gui.QGuiApplication_PrimaryScreen()
	pixmap := screen.GrabWindow(0, 0, 0, desktop.Width(), desktop.Height())

	image := pixmap.ToImage()
	label.SetPixmap(pixmap)

	// valid image
	path1 := filepath.Join(os.TempDir(), "test1.jpg")
	ok := image.Save(path1, "JPG", -1)
	fmt.Println("Save", path1, ok)

	s, err := os.Stat(path1)
	if err != nil {
		fmt.Println(err.Error())
	}
	fmt.Println("len:", s.Size())

	// buffer
	buff := core.NewQBuffer(widget)
	buff.Open(core.QIODevice__ReadWrite)
	ok = image.Save2(buff, "JPG", -1)
	fmt.Println("Save2", ok)

	data := buff.Data()
	fmt.Println("len2:", len(data))

	buff.Close()

	path2 := filepath.Join(os.TempDir(), "test2.jpg")
	err = ioutil.WriteFile(path2, []byte(data), 0644)
	fmt.Println("WriteFile", path2, err)

	layout.AddWidget(label, 0, 0)
	widget.SetLayout(layout)
	widget.Show()

	widgets.QApplication_Exec()
}
```

**Comment by therecipe** [comment]
Hey

It works for me, if I use `qtdeploy` or `qtminimal && go run/build -tags=minimal ...` but fails with the plain `go run/build ...`

But I will look into this.

**Comment by gen2brain** [comment]
Thanks. Yes, I used plain go build, I will try with qtdeploy.

**Comment by therecipe** [comment]
It's fixed with https://github.com/therecipe/qt/commit/2ac66d23735c7cb2b0b1270941e41913c0702cd0

The issue was similar to https://github.com/therecipe/qt/issues/64, but this time the data was expected to contain 0 bytes.
So I had to tell Go the lenght of the data, so that it wouldn't stop reading the data with the first 0 byte.

I also removed the (QByteArray == string) mapping, so you can now use `core.NewQByteArray()` as well.
This had to be done, as many functions that expect to receive a QByteArray were useless if I feed them a plain string, such as `core.NewQBuffer2()`.
I hope this change doesn't break much of you code.


Just replace `data := buff.Data()` with `data := buff.Data().ConstData()` and the code above should work.

**Comment by gen2brain** [comment]
It is fixed :) This also fixes random crashes I had with QNetworkReply.ReadAll on Linux , and probably more. Everything seems stable now. Great work. Btw I really like recent changes where qtsetup is binary, much much better. Thanks!

**Comment by therecipe** [comment]
You are welcome :)
I will probably focus on the usability of the tooling and make everything pretty straight fort from now on.
