### ISSUE TITLE
Possible conversion issue from string to QString

### ISSUE THREAD

**Issue by rhaidiz** [therecipe/qt#980]
Hi there, 

I'm having a bit of a trouble trying to display some string in a `QPlainTextEditor` and retrieve the value from it. Essentially, I receive some string representing raw data and I want to display it in a `QPlainTextEditor` because some chars might need to be manually edited. Then, after pressing a button, I retrieve the data in the `QPlainTextEditor` and send it back. However, some non-printable chars change after I get the string with `ToPlainText`.

Here is an example code:

```golang
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {

	app := widgets.NewQApplication(len(os.Args), os.Args)

	window := widgets.NewQMainWindow(nil, 0)
	window.SetMinimumSize2(250, 200)
	window.SetWindowTitle("Test")

	widget := widgets.NewQWidget(nil, 0)
	widget.SetLayout(widgets.NewQVBoxLayout())
	window.SetCentralWidget(widget)

	input := widgets.NewQTextEdit(nil)
	a := string([]uint8{116, 142})

	fmt.Printf("%x\n", a) // output here is 748e

	input.SetPlainText(a)
	widget.Layout().AddWidget(input)

	button := widgets.NewQPushButton2("Button", nil)
	button.ConnectClicked(func(bool) {
		print(fmt.Sprintf("%x\n", input.ToPlainText())) // output here is 74efbfbd
	})
	widget.Layout().AddWidget(button)

	window.Show()

	app.Exec()
}
```

The first `fmt.Printf` prints `748e` (correct) while the second `fmt.Printf` prints `74efbfbd` (not correct). I'm not sure what `bfbd` is, it looks like a trailing sequence. However, the main issue is that instead of `8e` I get `ef`.

Any idea what might cause this behavior? can it be because of the conversion from `string` to `QString`?

**Comment by therecipe** [comment]
Hey

I looked into this and I'm sorry but I'm not sure if you can display "raw data" in the plain text editor.
The problem is that the `SetPlainText` function as well as the `ToPlainText` function convert your string to a valid utf8 string before/after calling the underlying C function.
I tried to work around this an directly passed your data to the `SetPlainText` function, but I assume that the QPlainTextEditor is converting your string to utf8 under the hood as well and so it didn't really made a difference.

What you could to however would be to encode the parts of your raw data that aren't valid utf8 into hex and work with that instead.

**Comment by rhaidiz** [comment]
Thank you very much for your help, at least now I'm sure it's something with the `QPlainTextEditor`. I guess I'll convert it into hex as you suggested and display it in hex, at least for the time being.

Thanks again.
