### ISSUE TITLE
qtdeploy very slow use go1.13

### ISSUE THREAD

**Issue by rocket049** [therecipe/qt#987]
## go version
go version go1.13.3 linux/amd64

## Issue:
Run qtdeploy very slow when use go1.13.

**Comment by therecipe** [comment]
Hey

How much slower is Go 1.13 in opposite to Go 1.12 for you?

Also could you test if `qtdeploy` is faster with a GOPATH that just contains therecipe/qt, your project and all the necessary dependencies?

Because it seems like `go list` (which is used extensively by qtdeploy) gets pretty slow if you have a lot of stuff in your GOPATH.

**Comment by rocket049** [comment]
Very very slow, seems more than 10 times.

But if run `go build .` , the speed is normal.

I  study the output of `ps aux`, It takes a lot of time to compile packages such as core, gui, widgets.

**Comment by rocket049** [comment]
Resulved by newest qtdeploy version.
