### ISSUE TITLE
program compiled with go1.13 is much bigger than the one compiled with go1.12.

### ISSUE THREAD

**Issue by rocket049** [therecipe/qt#991]
My code is `github.com/rocket049/secret-diary`, the QT version is 5.12.5 (shared), the executable file is compiled with command `qtdeploy build`.

With go1.12.10, the size of file `deploy/linux/secret-diary` is 16315832.

With go1.13.3, the size fo it  is 60462024.

I feel something is wrong.

**Comment by therecipe** [comment]
Hey

Can you maybe update the binding to the latest version and try again?
I did work around some Go 1.13 bug some time ago (https://github.com/therecipe/qt/commit/d6c64b2b9081a7c277fdb450722272312a9d004f), which caused qtdeploy to compile against the "full" version of the binding instead of the "minimal" subset generated by qtdeploy.

This is probably also the cause of https://github.com/therecipe/qt/issues/987 and explains why qtdeploy is so much slower for you when using Go 1.13

**Comment by rocket049** [comment]
I am sorry, the prgram is not compatible with qt5.13.
Some qwidgets API will change when I update QT to 5.13.

**Comment by therecipe** [comment]
You can export `QT_API=5.12.0` to keep it working with newer versions of the binding and/or Qt.
Just export `QT_API=5.12.0` before running qtsetup/qtdeploy and it should continue to work.

**Comment by rocket049** [comment]
I have update the newest `qtsetup`, and I found it's no longer support `QT_API=5.12.0` now.

**Comment by therecipe** [comment]
Thank you :)

And yeah, this is probably because `go mod vendor` won't copy the `*.index` files needed for `QT_API`
If you want to get `QT_API=5.12.0` working, then you can use something like this (with `GO111MODULE=on`) before or after runnning `cp -ru vendor/github.com/* ~/go/src/github.com/`

```
cp -r $(go list -f {{.Dir}} github.com/therecipe/qt/internal/binding/files/docs/5.12.0) ~/go/src/github.com/therecipe/qt/internal/binding/files/docs/5.12.0
```

But using Qt 5.12.x and then only setting `QT_VERSION` should work as well, since it will then use the index files from `$QT_DIR/Docs` instead.
